table 'Measures Table'
	lineageTag: dbbb9155-dace-4a22-8ada-0f0cd8e87b43

	measure Sales_YTD_Actual = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [Sales_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        ),
			        FACT_Consol[Account] = "AZZZZZ",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: Sales
		lineageTag: 4df92126-a394-4968-8d77-ec5fcc787571

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "AZZZZZ"
			    )
			```
		displayFolder: Sales
		lineageTag: 00164ce2-902b-4afb-a3a4-089ce03291e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_MTH_Actual = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "AZZZZZ",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: Sales
		lineageTag: 4b955164-03e0-470c-87b7-70d9f4c2ce89

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Sales_MTH],
			        "YTD", [Sales_YTD]
			    )
		formatString: #,##0.0
		displayFolder: Sales
		lineageTag: 6757911e-d87f-4110-a7b4-bacc65217e28

	measure Sales_Selector_LineGraph_FC3 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE(
			    [Sales_Selector], 
			    KEEPFILTERS(previousDates), 
			    REMOVEFILTERS('DIM_Calendar'), 
			    USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			    // DIM_Country[Country] = "Finance Consol without EPIL",
			    DIM_Scenario[Scenario] = "FC3 (2nd Cut Final)")
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: f3045a7e-9558-47ae-a110-dc9b11c779a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_PrevYear = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE(
			    [Sales_Selector], 
			    KEEPFILTERS(previousDates), 
			    REMOVEFILTERS('DIM_Calendar'), 
			    USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			    // DIM_Country[Country] = "Finance Consol without EPIL",
			    DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr")
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: 78631955-b386-44d7-b976-b41902013ccc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [Sales_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Sales
		lineageTag: 27c3091b-b904-42ea-b525-548360e61342

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_FC2 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE(
			    [Sales_Selector], 
			    KEEPFILTERS(previousDates), 
			    REMOVEFILTERS('DIM_Calendar'), 
			    USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			    // DIM_Country[Country] = "Finance Consol without EPIL",
			    DIM_Scenario[Scenario] = "FC2 (2nd Cut Final)")
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: 9e44073c-551f-4ca0-b42d-30c7089aedea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_FC1 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE(
			    [Sales_Selector], 
			    KEEPFILTERS(previousDates), 
			    REMOVEFILTERS('DIM_Calendar'), 
			    USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			    // DIM_Country[Country] = "Finance Consol without EPIL",
			    DIM_Scenario[Scenario] = "FC1 (2nd Cut Final)")
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: ad4765c9-ad38-4704-9161-18fd2c4e9b55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_FC0 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE([Sales_Selector], 
			    KEEPFILTERS(previousDates), 
			    REMOVEFILTERS('DIM_Calendar'), 
			    USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			    // DIM_Country[Country] = "Finance Consol without EPIL",
			    DIM_Scenario[Scenario] = "FC0")
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: c889f156-9304-433a-a6f3-581a25c5ef26

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_BP = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE(
			    [Sales_Selector], 
			    KEEPFILTERS(previousDates), 
			    REMOVEFILTERS('DIM_Calendar'), 
			    USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			    // DIM_Country[Country] = "Finance Consol without EPIL",
			    DIM_Scenario[Scenario] = "BP (Final cut)")
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: b90ed581-2c1d-4236-97e8-632881a27ab1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_Actual = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [Sales_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        // DIM_Country[Country] = "Finance Consol without EPIL",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: 245b1d5f-3dca-4cb4-a37f-1953476c7656

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Sales_MTH_Actual],
			        "YTD", [Sales_YTD_Actual]
			    )
		formatString: #,0.0
		displayFolder: Sales
		lineageTag: 782bb3f3-0b2f-49bf-87d0-6e41bd8a1f69

	measure BusinessProfit_MTH =
			
			var F2ZZZZ =
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "F2ZZZZ"
			    )
			
			var C20622 =
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "C20622"
			    )
			
			return F2ZZZZ + C20622
		displayFolder: Business Profit
		lineageTag: e990755f-74b7-4ab9-a2bb-00f37eb3031c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit_MTH_Actual =
			
			var F2ZZZZ =
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "F2ZZZZ",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			var C20622 =
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "C20622",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			return F2ZZZZ + C20622
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Business Profit
		lineageTag: 5b878e12-c128-4cf6-94d4-3c1c1edfc3b1

	measure BusinessProfit_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [BusinessProfit_MTH],
			        "YTD", [BusinessProfit_YTD]
			    )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Business Profit
		lineageTag: 8ff6eefa-0f6f-4613-9c26-0981818d421c

	measure BusinessProfit_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [BusinessProfit_MTH_Actual],
			        "YTD", [BusinessProfit_YTD_Actual]
			    )
		formatString: #,##0.0
		displayFolder: Business Profit
		lineageTag: 9851b048-8f75-48e7-b618-93f45ec0fea8

	measure BusinessProfit_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [BusinessProfit_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Business Profit
		lineageTag: d4902a40-dacd-4305-8067-7ae628da23b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit_YTD_Actual = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [BusinessProfit_MTH_Actual],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Business Profit
		lineageTag: a00fb066-d2e6-4a1b-b0e9-ca63f83cec90

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfitRatio_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", DIVIDE([BusinessProfit_MTH], [Sales_MTH_WOElim]),
			        "YTD", DIVIDE([BusinessProfit_YTD], [Sales_YTD_WOElim])
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Business Profit
		lineageTag: 67eadffb-f187-4ea9-beeb-565fec5f5a20

	measure BusinessProfitRatio_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", DIVIDE([BusinessProfit_MTH_Actual], [Sales_MTH_Actual_WOElim]),
			        "YTD", DIVIDE([BusinessProfit_YTD_Actual], [Sales_YTD_Actual_WOElim])
			    )
		formatString: 0.0%;-0.0%
		displayFolder: Business Profit
		lineageTag: 56f1416a-7f77-41ae-a854-5ca40f422987

		annotation PBI_FormatHint = {"isCustom":true}

	measure Sales_Achievement_MTH =
			
			VAR selected_fc =
			    SELECTEDVALUE ( 'Selector Table - Scenario'[Scenario] )
			VAR sales_mth_actual = [Sales_MTH_Actual]
			VAR sales_mth_fc =
			    CALCULATE (
			        [Sales_MTH],
			        DIM_Scenario[Scenario] = selected_fc
			    )
			RETURN
			    IF (
			        sales_mth_fc = 0,
			        BLANK (),
			        sales_mth_actual / sales_mth_fc
			    )
		displayFolder: Sales Achievement
		lineageTag: 74585133-d54c-49b2-a516-f992a2094988

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Achievement_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Sales_Achievement_MTH],
			        "YTD", [Sales_Achievement_YTD]
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales Achievement
		lineageTag: 353fb7ca-fc14-4b13-a142-981913e3cc1e

	measure Sales_Achievement_Selector_Lookup = ```
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			return 
			    CALCULATE(
			        [Sales_Achievement_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales Achievement
		lineageTag: 249cef05-5439-40fd-ad20-9cea1b98e627

	measure Sales_Achievement_YTD =
			
			VAR selected_fc = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR sales_ytd_actual = [Sales_YTD_Actual]
			VAR sales_ytd_fc =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Scenario[Scenario] = selected_fc
			    )
			
			return sales_ytd_actual / sales_ytd_fc
		displayFolder: Sales Achievement
		lineageTag: d7e41033-e974-415c-beff-1cb4364ff1c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "EZZZZZ"
			    )
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: SGA
		lineageTag: 0a40130d-3722-4878-ba5a-7c5f599b7be6

	measure SGA_MTH_Actual = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "EZZZZZ",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: SGA
		lineageTag: e063593d-7f81-4728-8fbc-1c310d8390f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [SGA_MTH],
			        "YTD", [SGA_YTD]
			    )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: SGA
		lineageTag: 11eabf2d-7586-4de6-840f-1f95885609b9

	measure SGA_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [SGA_MTH_Actual],
			        "YTD", [SGA_YTD_Actual]
			    )
		formatString: #,##0.0
		displayFolder: SGA
		lineageTag: 10d1703d-ea17-4641-99c3-34c03ea82db7

	measure SGA_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [SGA_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA
		lineageTag: 77c76eda-652b-4846-ae19-2b7c12a68aa2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_YTD_Actual = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [SUM_Value],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        ),
			        FACT_Consol[Account] = "EZZZZZ",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: SGA
		lineageTag: 2e061a1f-ae83-4083-8f67-77b32e87edd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ESC_Revenue_Waterfall =
			
			
			var selectedScenario = SELECTEDVALUE(DIM_Scenario[Scenario])
			var selectedCountry = SELECTEDVALUE('Selector Table - Country'[Alias])
			var userSelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			return
			    SWITCH(selectedScenario,
			        userSelectedScenario,
			            SWITCH(selectedCountry,
			                "ESD", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "ETH", CALCULATE([Sales_Selector], DIM_Country[Country] = selectedCountry, DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "IDC", CALCULATE([Sales_Selector], DIM_Country[Country] = selectedCountry, DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "EPC", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "EMSB", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "EIN-IDR", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "Others Dir", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "Total EVNL", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Total EVNL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "MD", CALCULATE([Sales_MD_Selector], HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L8] = "ED - PH16"),
			                CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20")
			            ),
			        "Actual",
			            SWITCH(selectedCountry,
			                "ESD", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "ETH", CALCULATE([Sales_Selector], DIM_Country[Country] = selectedCountry, DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "IDC", CALCULATE([Sales_Selector], DIM_Country[Country] = selectedCountry, DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "EPC", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "EMSB", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "EIN-IDR", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "Others Dir", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "Total EVNL", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Total EVNL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"),
			                "MD", CALCULATE([Sales_MD_Selector], HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L8] = "ED - PH16"),
			                CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20")
			            )
			    )
		formatString: #,#0.##;-#,#0.##
		displayFolder: Waterfall
		lineageTag: d9cbdd7b-bbf3-4a3a-81ab-83b8d6706c05

		annotation PBI_FormatHint = {"isCustom":true}

	measure ProductCategory_Revenue_Waterfall =
			
			
			var selectedScenario = SELECTEDVALUE(DIM_Scenario[Scenario])
			var selectedProductCategory = SELECTEDVALUE('Selector Table - Product Category'[Product Category])
			var userSelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			return
			    SWITCH(selectedScenario,
			        userSelectedScenario,
			            SWITCH(selectedProductCategory,
			                "CISS", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "CISS_FY20"),
			                "SIDM", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "SIDM/PLQ (Local)"),
			                "SP", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Small Printer (Local)"),
			                "Corporate BU", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Corporate BU"),
			                "Printer others", CALCULATE([Sales_PrinterOthers_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario),
			                "LFP (excl Corp)", CALCULATE([Sales_LFP_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario),
			                "VI", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "VI - PH16"),
			                "IIJ", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "IIJ"),
			                "RS", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "FA - PH16"),
			                CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20")
			            ),
			        "Actual",
			            SWITCH(selectedProductCategory,
			                "CISS", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "CISS_FY20"),
			                "SIDM", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "SIDM/PLQ (Local)"),
			                "SP", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "Small Printer (Local)"),
			                "Corporate BU", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "Corporate BU"),
			                "Printer others", CALCULATE([Sales_PrinterOthers_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual"),
			                "LFP (excl Corp)", CALCULATE([Sales_LFP_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual"),
			                "VI", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "VI - PH16"),
			                "IIJ", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "IIJ"),
			                "RS", CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "FA - PH16"),
			                CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20")
			            )
			    )
		formatString: #,#0.##;-#,#0.##
		displayFolder: Waterfall
		lineageTag: 625550db-8f96-4be7-8a43-4598d71d6ab6

		annotation PBI_FormatHint = {"isCustom":true}

	measure Sales_LFP_Selector =
			
			VAR lfp_local = CALCULATE([Sales_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "LFP (Local) - FY20")
			VAR corporate_local = CALCULATE([Sales_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Corporate (Local) - FY20")
			
			return lfp_local - corporate_local
		displayFolder: Waterfall
		lineageTag: cd1fb26a-2cb2-4921-b84f-6f0f05913d30

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_MD_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Sales_MTH_MD],
			        "YTD", [Sales_YTD_MD]
			    )
		displayFolder: Waterfall
		lineageTag: 56d55ffc-97ad-4d5e-997c-d2dd91b2ca67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_MTH_MD = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "AZZZZZ",
			        HIER_ProfitCenter[ProfitCenter_L8] = "ED - PH16",
			        DIM_Country[Country] = "Finance Consol without EPIL"
			    )
			```
		displayFolder: Waterfall
		lineageTag: a4fffe98-e2b0-4be7-bd9b-248ac16e6349

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_PrinterOthers_Selector =
			
			VAR cp_local = CALCULATE([Sales_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "CP (Local) - FY20")
			VAR media_others = CALCULATE([Sales_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Media Others - PH16")
			VAR liatris = CALCULATE([Sales_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Liatris (Local) - FY20")
			VAR colour_label = CALCULATE([Sales_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Colour Label/LW (Local)")
			
			return cp_local + media_others + liatris + colour_label
		displayFolder: Waterfall
		lineageTag: 1f921ebe-5ccf-4976-923d-999412a0b77f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_YTD_MD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [Sales_MTH_MD],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Waterfall
		lineageTag: 1d4f94b9-4aa0-4551-849d-d9a2f14db26a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Ratio_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", DIVIDE([SGA_MTH], [Sales_MTH]),
			        "YTD", DIVIDE([SGA_YTD], [Sales_YTD])
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA Ratio
		lineageTag: 3e7150d3-483b-4971-9277-43280023c02d

	measure SGA_Ratio_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", DIVIDE([SGA_MTH_Actual], [Sales_MTH_Actual]),
			        "YTD", DIVIDE([SGA_YTD_Actual], [Sales_YTD_Actual])
			    )
		formatString: 0.0%;-0.0%
		displayFolder: SGA Ratio
		lineageTag: 58981d2b-b190-49a0-9f3b-1a6676a37ee5

		annotation PBI_FormatHint = {"isCustom":true}

	measure SalesMinus_MTH = ```
			
			// VAR vA00020A = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00020A")
			// VAR vA00020B = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00020B")
			// VAR vA00020C = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00020C")
			// VAR vA00020D = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00020D")
			// VAR vA00020E = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00020E")
			// VAR vA00021A = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00021A")
			// VAR vA00021B = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00021B")
			// VAR vA00021C = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00021C")
			// VAR vA00021D = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "A00021D")
			
			// // 21110300   SALES OF GOODS-Discount*
			// VAR v21110300 = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "21110300")
			
			// // 21110400   SALES OF GOODS-Price Protection*
			// VAR v21110400 = CALCULATE(SUM('FACT_Consol'[Value]), FACT_Consol[Account] = "21110400")
			
			// // 21110200   SALES OF GOODS-Rebate*
			// VAR v21110200 = vA00020A + vA00020B + vA00020C + vA00020D + vA00020E
			
			// // 21110201   SALES OF GOODS-2nd Tier Rebate*
			// VAR v21110201 = vA00021A + vA00021B + vA00021C + vA00021D
			
			    CALCULATE(
			        [SUM_Value], 
			        FACT_Consol[Account] = "Sales Minus"
			        // HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			```
		displayFolder: Sales\Sales Minus
		lineageTag: 9308053c-90e6-49a3-9923-a5d88e96e350

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus_YTD = ```
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [SalesMinus_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Sales\Sales Minus
		lineageTag: 1e2f896a-4d22-46fa-886c-2f330bad6756

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [SalesMinus_MTH],
			        "YTD", [SalesMinus_YTD]
			    )
		formatString: #,##0.0
		displayFolder: Sales\Sales Minus
		lineageTag: 3c5dc40f-e8c4-4aa5-a823-6a88cf513e4e

	measure SalesMinus%_MTH = [SalesMinus_MTH] / [GrossSale_MTH]
		displayFolder: Sales\Sales Minus
		lineageTag: c1c80c3a-4c53-4d42-a2b4-db3f2e241ed0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus%_YTD = [SalesMinus_YTD] / [GrossSale_YTD]
		displayFolder: Sales\Sales Minus
		lineageTag: bc43ec15-f7f0-4f00-97c4-b2f7ac3c20e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus%_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [SalesMinus%_MTH],
			        "YTD", [SalesMinus%_YTD]
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Sales Minus
		lineageTag: 2643f9ed-6d95-4081-80d4-28ae13a64a1d

	measure TrafficLightCircle = UNICHAR(11044)
		lineageTag: cb27633f-5a1a-4fb9-a4db-36e1da3e53d2

	measure Sales_Achievement_MTH_vsPrevYear =
			
			VAR sales_mth_actual = [Sales_MTH_Actual]
			VAR sales_mth_prevYear =
			    CALCULATE(
			        [Sales_MTH],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			
			return sales_mth_actual / sales_mth_prevYear
		displayFolder: Sales Achievement
		lineageTag: 34dd3b02-17ee-4a4f-9787-d68232df5120

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Achievement_YTD_vsPrevYear =
			
			VAR sales_ytd_actual = [Sales_YTD_Actual]
			VAR sales_ytd_prevYear =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			
			return sales_ytd_actual / sales_ytd_prevYear
		displayFolder: Sales Achievement
		lineageTag: e5c3d7ab-bb2e-4628-b377-c1dd69a20940

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Achievement_vsPrevYear_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Sales_Achievement_MTH_vsPrevYear],
			        "YTD", [Sales_Achievement_YTD_vsPrevYear]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales Achievement
		lineageTag: 0cd07d4b-a07b-49d6-bbe8-4ebff548ff0d

	measure TrafficLight_HariMeri =
			
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsPrevYear =
			    IF([Sales_Achievement_vsPrevYear_Selector] >= 1,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsFC =
			    IF([Sales_Achievement_Selector] >= 1,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return ActualvsPrevYear + ActualvsFC
		formatString: 0
		lineageTag: 4c0d1f79-5572-46cc-aa6d-783473317264

	measure 1stRebateTRB_MTH =
			
			// TRB stans for Tactical Rebates Program
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00020B",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
		displayFolder: Rebates
		lineageTag: 6c0ebf07-397b-498e-b857-27208e1db4f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebateTRB_MTH =
			
			// TRB stans for Tactical Rebates Program
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00021B",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
		displayFolder: Rebates
		lineageTag: 97a63bb4-e843-443d-866c-31ddd0694d98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRebate_MTH = [1stRebateTRB_MTH] + [2ndRebateTRB_MTH]
		displayFolder: Rebates
		lineageTag: ef21ddbd-63f0-4c9c-b47c-dab06599ca5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebateTRB_YTD = ```
			
			// TRB stands for Tactical Rebates Program
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [1stRebateTRB_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Rebates
		lineageTag: e1c236a7-27b4-4de0-a015-64ebbd3b9789

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebateTRB_YTD = ```
			
			// TRB stands for Tactical Rebates Program
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [2ndRebateTRB_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Rebates
		lineageTag: ccf1293a-9817-4fbd-a89b-357c2dad3108

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRebate_YTD = [1stRebateTRB_YTD] + [2ndRebateTRB_YTD]
		displayFolder: Rebates
		lineageTag: 34500130-3006-4adc-adca-832dbd335625

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRebate_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalRebate_MTH],
			        "YTD", [TotalRebate_YTD]
			    )
		displayFolder: Rebates
		lineageTag: a557a298-cc74-43a8-99fe-318e812dee2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_MTH_Actual = ```
			
			    CALCULATE(
			        [GrossSale_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: Gross Sales
		lineageTag: 8b97f2dc-d574-495b-8eff-becaf8e53800

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [GrossSale_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Gross Sales
		lineageTag: 335d8b5b-85a0-4c14-b2af-6aeaabd844b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [GrossSale_MTH],
			        "YTD", [GrossSale_YTD]
			    )
		displayFolder: Gross Sales
		lineageTag: 80c3c3bf-e8fd-4ed3-b281-b9dbb229ceaf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_YTD_Actual = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [GrossSale_MTH_Actual],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Gross Sales
		lineageTag: ba0a14ab-8799-4482-8961-043c327dc931

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_MTH =
			
			VAR A00000 = CALCULATE([SUM_Value], FACT_Consol[Account] = "A00000")
			VAR A00002 = CALCULATE([SUM_Value], FACT_Consol[Account] = "A00002")
			VAR A00010 = CALCULATE([SUM_Value], FACT_Consol[Account] = "A00010")
			
			RETURN A00000 + A00002 - A00010
		displayFolder: Gross Sales
		lineageTag: 03705bcf-90e8-4e35-bfed-b5a7310bc9d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [GrossSale_MTH_Actual],
			        "YTD", [GrossSale_YTD_Actual]
			    )
		displayFolder: Gross Sales
		lineageTag: 6a76fe0d-a17b-4854-b248-67b80a7b764d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_Selector_FC =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        SWITCH(SelectedType, "Month", [GrossSale_MTH], "YTD", [GrossSale_YTD]),
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		displayFolder: Gross Sales
		lineageTag: 213345d7-3aa4-4c9d-9a5b-a321aef5d4ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus_Selector_Actual = ```
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR result = 
			CALCULATE(
			    SWITCH(SelectedType, "Month", [SalesMinus_MTH], "YTD", [SalesMinus_YTD]),
			    DIM_Scenario[Scenario] = "Actual"
			)
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
			    
			```
		displayFolder: Sales\Sales Minus
		lineageTag: b23c1d11-da7f-4b79-a445-3d6349b54037

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus%_Selector_Actual =
			
			VAR result =
			CALCULATE(
			    [SalesMinus%_Selector],
			    DIM_Scenario[Scenario] = "Actual"
			)
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Sales Minus
		lineageTag: 5b67fa63-4fc5-4dc4-ab3d-613d3a08e1a4

	measure SalesMinus_Selector_FC =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        SWITCH(SelectedType, "Month", [SalesMinus_MTH], "YTD", [SalesMinus_YTD]),
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
		displayFolder: Sales Minus
		lineageTag: 18475e2e-3346-4c5e-8e52-7b00ff5fca0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus%_Selector_FC =
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR result =
			    CALCULATE(
			        [SalesMinus%_Selector],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Sales Minus
		lineageTag: bae72304-ad00-4fa8-8bed-1250327a1500

	measure SalesMinus%_Variance = [SalesMinus%_Selector_Actual] - [SalesMinus%_Selector_FC]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Sales Minus
		lineageTag: 7335b569-23f0-42a0-8a39-7f982b0d1a62

	measure SalesMinus%_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SalesMinus%_Selector_Actual_Line], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus
		lineageTag: e57e8712-3620-4adb-ae0a-368476c0b771

	measure SalesMinus%_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([SalesMinus%_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales Minus
		lineageTag: 556c120a-3cb1-40ef-a823-76a5dd5b74c1

	measure 1stRebateTRB_MTH_Actual =
			
			// TRB stans for Tactical Rebates Program
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00020B",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20",
			        DIM_Scenario[Scenario] = "Actual"
			    )
		displayFolder: Rebates
		lineageTag: 0e36154a-70c0-416b-98f8-28e57ca9087c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebateTRB_YTD_Actual = ```
			
			// TRB stands for Tactical Rebates Program
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [1stRebateTRB_MTH_Actual],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Rebates
		lineageTag: 734cc9d7-1df6-41be-8674-04fe52b1d284

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebateTRB_MTH_Actual =
			
			// TRB stans for Tactical Rebates Program
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00021B",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20",
			        DIM_Scenario[Scenario] = "Actual"
			    )
		displayFolder: Rebates
		lineageTag: a84a0483-e2f1-4457-a7f0-30222d2dbf14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebateTRB_YTD_Actual = ```
			
			// TRB stands for Tactical Rebates Program
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [2ndRebateTRB_MTH_Actual],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Rebates
		lineageTag: e637d86b-3b2a-4dce-ab1e-a91a364adf38

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRebate_MTH_Actual = [1stRebateTRB_MTH_Actual] + [2ndRebateTRB_MTH_Actual]
		displayFolder: Rebates
		lineageTag: 6dcb3257-27de-42c5-aa30-ad52af9f17da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRebate_YTD_Actual = [1stRebateTRB_YTD_Actual] + [2ndRebateTRB_YTD_Actual]
		displayFolder: Rebates
		lineageTag: f91225a7-7a53-42cd-afd2-f06aad86cbf4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRebate_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalRebate_MTH_Actual],
			        "YTD", [TotalRebate_YTD_Actual]
			    )
		displayFolder: Rebates
		lineageTag: 91fda448-65d0-466c-a5ab-7a07a319bebc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalRebate_Selector_FC =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			RETURN
			    CALCULATE(
			        SWITCH(
			            SelectedType,
			            "Month", [TotalRebate_MTH],
			            "YTD", [TotalRebate_YTD]
			        ),
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
		displayFolder: Rebates
		lineageTag: dfffc051-3165-4feb-994c-6e687afe2613

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_MTH = ```
			
			// VAR vAdvertisement = 
			//     CALCULATE(
			//         SUM(FACT_Consol[Value]),
			//         FACT_Consol[Account] IN {"25210000", "25210100", "25210200", "25210300", "25210400", "25210500"},
			//         HIER_ProfitCenter[ProfitCenter_L9] = "Finance - PH20"
			//     )
			// VAR vPromotion = 
			//     CALCULATE(
			//         SUM(FACT_Consol[Value]),
			//         FACT_Consol[Account] IN {"25220000", "25220100", "25220200"},
			//         HIER_ProfitCenter[ProfitCenter_L9] = "Finance - PH20"
			//     )
			// VAR vIncentive =
			//     CALCULATE(
			//         SUM(FACT_Consol[Value]),
			//         FACT_Consol[Account] = "25220300",
			//         HIER_ProfitCenter[ProfitCenter_L9] = "Finance - PH20"
			//     )
			// RETURN vAdvertisement + vPromotion + vIncentive
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "Total A&P"
			        // HIER_ProfitCenter[ProfitCenter_L9] = "Finance - PH20"
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 0a4ff077-e3a4-4273-8989-ae3586afccaa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalASCost_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        HIER_InStMeasure[InStMeasure_L1] = "AS Cost"
			        // HIER_ProfitCenter[ProfitCenter_L9] = "Finance - PH20"
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 92ff6ba3-c707-46fb-a7d9-1cdb6a4a48b9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        HIER_InStMeasure[InStMeasure_L1] = "Total Logistics 2"
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: af72f160-179b-48ad-abf8-effb4c0a8c79

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Salaries_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "Salaries"
			        // HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20"
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 28517141-3982-4832-9522-2d7faf1bfd0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGAOthers_MTH =
			
			VAR vSGA =
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "EZZZZZ"
			    )
			
			RETURN vSGA - ([TotalA&P_MTH] + [TotalLogistics_MTH] + [TotalASCost_MTH] + [Salaries_MTH])
		displayFolder: SGA\SGA Position
		lineageTag: 0ac06a35-ee54-48b3-9d1b-4d29a62b5c8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [ASCost_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: e749a837-cd4c-47fa-a081-e7a5f74c98d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Salaries_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [Salaries_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: b6cfd711-0fef-4be9-b29a-57c53f96c161

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGAOthers_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [SGAOthers_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 7551d99c-dcf2-483c-ad98-9aeebbf6d48b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [TotalA&P_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 39a12800-e7cc-4352-9aa0-32dcc85e30cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [TotalLogistics_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 0c0d74f7-830f-49a9-8835-9d712b428113

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR TotalAP_Actual = 
			    CALCULATE(
			        [TotalA&P_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR TotalAP_FC =
			    CALCULATE(
			        [TotalA&P_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN TotalAP_Actual / TotalAP_FC
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA\SGA Position
		lineageTag: a586ceb2-6a65-4360-bdab-0e5a2eaaf080

	measure TotalA&P_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR TotalAP_Actual = 
			    CALCULATE(
			        [TotalA&P_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR TotalAP_FC =
			    CALCULATE(
			        [TotalA&P_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN TotalAP_Actual / TotalAP_FC
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA\SGA Position
		lineageTag: db86fc0e-9046-4688-9cf3-f24518815f92

	measure TotalA&P_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalA&P_MTH_ActualvsFC],
			        "YTD", [TotalA&P_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 398aab6f-5fb0-4412-81fe-9c12d0f8e013

	measure TotalLogistics_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR TotalLogistics_Actual = 
			    CALCULATE(
			        [TotalLogistics_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR TotalLogistics_FC =
			    CALCULATE(
			        [TotalLogistics_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN TotalLogistics_Actual / TotalLogistics_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: d6e11d8f-c6f9-44aa-a222-f5b1640d36fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR TotalLogistics_Actual = 
			    CALCULATE(
			        [TotalLogistics_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR TotalLogistics_FC =
			    CALCULATE(
			        [TotalLogistics_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN TotalLogistics_Actual / TotalLogistics_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 1141b7c7-fbfd-4aec-9b1e-814c64334212

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalLogistics_MTH_ActualvsFC],
			        "YTD", [TotalLogistics_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 36528fc8-db24-40c4-9a1d-31e6dbb8e7dd

	measure TotalASCost_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR ASCost_Actual = 
			    CALCULATE(
			        [TotalASCost_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR ASCost_FC =
			    CALCULATE(
			        [TotalASCost_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN ASCost_Actual / ASCost_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 6ea3ed80-b2a9-4625-9129-257b6b7fc8a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalASCost_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR ASCost_Actual = 
			    CALCULATE(
			        [ASCost_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR ASCost_FC =
			    CALCULATE(
			        [ASCost_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN ASCost_Actual / ASCost_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: e1bf410a-f25d-4f7d-9fe2-4ccaa3a77840

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalASCost_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalASCost_MTH_ActualvsFC],
			        "YTD", [TotalASCost_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 34611187-8062-445b-ad5e-20500ec77977

	measure Salaries_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR Salaries_Actual = 
			    CALCULATE(
			        [Salaries_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR Salaries_FC =
			    CALCULATE(
			        [Salaries_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN Salaries_Actual / Salaries_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 28359f1a-2ee0-4acc-b5fe-f7dc1a141bc9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Salaries_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR Salaries_Actual = 
			    CALCULATE(
			        [Salaries_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR Salaries_FC =
			    CALCULATE(
			        [Salaries_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN Salaries_Actual / Salaries_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: c01d1755-35e8-4d29-a0e7-40bfd1b0b507

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Salaries_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Salaries_MTH_ActualvsFC],
			        "YTD", [Salaries_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 12b19744-aab3-4dd0-903a-a521eb6c1c01

	measure SGAOthers_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR SGAOthers_Actual = 
			    CALCULATE(
			        [SGAOthers_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR SGAOthers_FC =
			    CALCULATE(
			        [SGAOthers_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN SGAOthers_Actual / SGAOthers_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 89a9ce8e-15bc-4c56-a4bc-b6785504a78e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGAOthers_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR SGAOthers_Actual = 
			    CALCULATE(
			        [SGAOthers_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR SGAOthers_FC =
			    CALCULATE(
			        [SGAOthers_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN SGAOthers_Actual / SGAOthers_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: e6c09ba1-aeb7-4ff3-90eb-cee42f5f3a2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGAOthers_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [SGAOthers_MTH_ActualvsFC],
			        "YTD", [SGAOthers_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 14f284e3-6e5e-4e81-b0f0-7f96d0e0b2ff

	measure HariTotalAP_MTH =
			
			VAR vProfitCenter = "Hari (BPD) - FY24"
			RETURN
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "Total A&P",
			        HIER_ProfitCenter[ProfitCenter_L9] = vProfitCenter
			    )
		displayFolder: SGA\SGA Position
		lineageTag: dc8876c0-db9b-4d0a-8133-8dc89f1bff7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HariTotalAP_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [HariTotalAP_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: ba827657-e90b-44c4-88fe-b16e218ea677

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HariTotalAP_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR HariTotalAP_Actual = 
			    CALCULATE(
			        [HariTotalAP_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR HariTotalAP_FC =
			    CALCULATE(
			        [HariTotalAP_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN HariTotalAP_Actual / HariTotalAP_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 033337b9-f9a6-4c81-b264-e16412b401ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HariTotalAP_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR HariTotalAP_Actual = 
			    CALCULATE(
			        [HariTotalAP_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR HariTotalAP_FC =
			    CALCULATE(
			        [HariTotalAP_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN HariTotalAP_Actual / HariTotalAP_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 76e2aac9-cb11-443e-a831-f4a6e2697607

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HariTotalAP_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [HariTotalAP_MTH_ActualvsFC],
			        "YTD", [HariTotalAP_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 451fe35d-112b-433d-b595-15eea777ba1c

	measure MeriTotalAP_MTH =
			
			VAR vProfitCenter = "Meri (BPD) - FY24"
			RETURN
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "Total A&P",
			        HIER_ProfitCenter[ProfitCenter_L9] = vProfitCenter
			    )
		displayFolder: SGA\SGA Position
		lineageTag: b14bda67-5a34-4afd-86c5-158c313e0b4a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MeriTotalAP_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR MeriTotalAP_Actual = 
			    CALCULATE(
			        [MeriTotalAP_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR MeriTotalAP_FC =
			    CALCULATE(
			        [MeriTotalAP_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN MeriTotalAP_Actual / MeriTotalAP_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 8dfb8ae8-0dc9-4932-bd16-ad22579f39bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MeriTotalAP_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [MeriTotalAP_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 8c6d3718-228f-4065-8b4a-84ed0a861e67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MeriTotalAP_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR MeriTotalAP_Actual = 
			    CALCULATE(
			        [MeriTotalAP_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR MeriTotalAP_FC =
			    CALCULATE(
			        [MeriTotalAP_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN MeriTotalAP_Actual / MeriTotalAP_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: f72793ae-79a3-4224-bad9-6579dc77c723

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MeriTotalAP_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [MeriTotalAP_MTH_ActualvsFC],
			        "YTD", [MeriTotalAP_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 383cd6c3-8937-48c2-ba20-f9e32f388cca

	measure MDTotalAP_MTH =
			
			VAR vProfitCenter = "ED - PH16"
			RETURN
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "Total A&P",
			        HIER_ProfitCenter[ProfitCenter_L9] = vProfitCenter
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 9638928d-57eb-4e94-8342-276cd6841122

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MDTotalAP_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [MDTotalAP_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: b63cde80-c656-4ef9-87f4-6dad5f1e71fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MDTotalAP_MTH_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR MDTotalAP_Actual = 
			    CALCULATE(
			        [MDTotalAP_MTH],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR MDTotalAP_FC =
			    CALCULATE(
			        [MDTotalAP_MTH],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN MDTotalAP_Actual / MDTotalAP_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 3e180575-22eb-437a-a05f-106ae4c9da1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MDTotalAP_YTD_ActualvsFC = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR MDTotalAP_Actual = 
			    CALCULATE(
			        [MDTotalAP_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR MDTotalAP_FC =
			    CALCULATE(
			        [MDTotalAP_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN MDTotalAP_Actual / MDTotalAP_FC
			```
		displayFolder: SGA\SGA Position
		lineageTag: 0a10af74-58e3-4337-9066-977610ded983

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MDTotalAP_ActualvsFC_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [MDTotalAP_MTH_ActualvsFC],
			        "YTD", [MDTotalAP_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 78c4fdc4-ba70-4904-ad47-e2d5c83b4455

	measure Scorecard_Sales_MTH_Actual =
			
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([Sales_MTH], REMOVEFILTERS(HIER_ProfitCenter[ProfitCenter_L9]), HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual"),
			        "ETH", CALCULATE([Sales_MTH], HIER_Country[Country_L0] = selectedCountry, DIM_Scenario[Scenario] = "Actual"),
			        "IDC", CALCULATE([Sales_MTH], HIER_Country[Country_L0] = selectedCountry, DIM_Scenario[Scenario] = "Actual"),
			        CALCULATE([Sales_MTH], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual")
			    )
		displayFolder: Scorecard
		lineageTag: 7e1790e9-5a69-4ee3-a8fd-edf9f3ea4101

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_YTD_Actual =
			
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([Sales_YTD], REMOVEFILTERS('DIM_ProfitCenter - Alias & Ordering'), HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual"),
			        CALCULATE([Sales_YTD], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual")
			    )
		displayFolder: Scorecard
		lineageTag: 5255662f-af98-4cd7-aa3c-ae42deb22596

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_Selector_ActualvsFC =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Scorecard_Sales_MTH_ActualvsFC],
			        "YTD", [Scorecard_Sales_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: 8d1d6827-42cf-4435-8cb3-95adae203180

	measure Scorecard_Sales_MTH_FC =
			
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([Sales_MTH], REMOVEFILTERS(HIER_ProfitCenter[ProfitCenter_L9]), HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = selectedScenario),
			        "ETH", CALCULATE([Sales_MTH], HIER_Country[Country_L0] = selectedCountry, DIM_Scenario[Scenario] = selectedScenario),
			        "IDC", CALCULATE([Sales_MTH], HIER_Country[Country_L0] = selectedCountry, DIM_Scenario[Scenario] = selectedScenario),
			        CALCULATE([Sales_MTH], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = selectedScenario)
			    )
		displayFolder: Scorecard
		lineageTag: f354ab64-ee72-406c-b478-e925289b3639

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_YTD_FC =
			
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([Sales_YTD], REMOVEFILTERS('DIM_ProfitCenter - Alias & Ordering'), HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = selectedScenario),
			        CALCULATE([Sales_YTD], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = selectedScenario)
			        // CALCULATE([Sales_YTD], DIM_Country[Country] = selectedCountry, DIM_Scenario[Scenario] = selectedScenario)
			    )
		displayFolder: Scorecard
		lineageTag: 4641eaeb-94de-4cbf-9e15-e94955ebbc6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_MTH_ActualvsFC = [Scorecard_Sales_MTH_Actual] / [Scorecard_Sales_MTH_FC]
		displayFolder: Scorecard
		lineageTag: 675f2b17-12d2-47ac-a70f-f4d31582fdf4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_YTD_ActualvsFC = [Scorecard_Sales_YTD_Actual] / [Scorecard_Sales_YTD_FC]
		displayFolder: Scorecard
		lineageTag: 2c7f1272-6407-493c-9466-7d18f9745860

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_HariRatio_MTH =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR vHari =
			    CALCULATE(
			        [Sales_MTH],
			        HIER_Country[Country_L1] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L8] = "Hari (BPD) - FY24"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_MTH],
			        HIER_Country[Country_L1] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20"
			    )
			
			RETURN vHari / vBPD
		formatString: 0
		displayFolder: Scorecard
		lineageTag: e555408a-b206-4f06-b5ed-5185753cd262

	measure Scorecard_Sales_MTH_PrevYear =
			
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([Sales_MTH], REMOVEFILTERS(HIER_ProfitCenter[ProfitCenter_L9]), HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"),
			        CALCULATE([Sales_MTH], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr")
			    )
		displayFolder: Scorecard
		lineageTag: 56eaa682-81f3-41e4-9d5f-07a7b6aa6881

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_YTD_PrevYear =
			
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([Sales_YTD], REMOVEFILTERS('DIM_ProfitCenter - Alias & Ordering'), HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"),
			        CALCULATE([Sales_YTD], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr")
			    )
		displayFolder: Scorecard
		lineageTag: bc558c7e-13b9-4152-b29a-8b68cd26db4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_MTH_ActualvsPrevYear = [Scorecard_Sales_MTH_Actual] / [Scorecard_Sales_MTH_PrevYear]
		displayFolder: Scorecard
		lineageTag: b530937a-dcac-447b-a8e6-ea526aba7ceb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_YTD_ActualvsPrevYear = [Scorecard_Sales_YTD_Actual] / [Scorecard_Sales_YTD_PrevYear]
		displayFolder: Scorecard
		lineageTag: 029fe5f7-452a-4d3e-abee-49e5bb173aef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_Sales_Selector_ActualvsPrevYear =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Scorecard_Sales_MTH_ActualvsPrevYear],
			        "YTD", [Scorecard_Sales_YTD_ActualvsPrevYear]
			    )
		displayFolder: Scorecard
		lineageTag: 63e8eba4-891e-4138-8433-59d852a63c2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TrafficLight_Scorecard_Sales =
			
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsPrevYear =
			    IF([Scorecard_Sales_Selector_ActualvsPrevYear] >= 1,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsFC =
			    IF([Scorecard_Sales_Selector_ActualvsFC] >= 1,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return ActualvsPrevYear + ActualvsFC
		formatString: 0
		lineageTag: 62f57fb3-190e-4f12-9f6c-447f5c2a8f20

	measure temp_hari =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Scorecard_Sales_MTH_ActualvsFC],
			        "YTD", [Scorecard_Sales_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: 65380bbe-ca85-47ce-8450-039a3eb2d235

	measure temp_sga =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Scorecard_Sales_MTH_ActualvsFC],
			        "YTD", [Scorecard_Sales_YTD_ActualvsFC]
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Scorecard
		lineageTag: 96123b02-a415-4b7b-b4cd-34fef3352605

	measure temp_inven =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Scorecard_Sales_MTH_ActualvsFC],
			        "YTD", [Scorecard_Sales_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: 9875f74a-1723-44f8-a1b3-58c7f28f0624

	measure temp_bp =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Scorecard_Sales_MTH_ActualvsFC],
			        "YTD", [Scorecard_Sales_YTD_ActualvsFC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: 807c276d-c779-4897-a499-26dc95378ef3

	measure temp_sales = 0.9
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: 04e1a6d0-e343-4889-ac72-83a6ad1d22a1

	measure temp_sga2 = 0.9
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: 0e9d7f4a-eb52-4257-a70d-834aacf856a9

	measure temp_anp = 0.9
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: 59406e4a-373f-4284-b9d9-3e147e315733

	measure temp_inven2 = 0.9
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scorecard
		lineageTag: f7c7d612-4d91-4f82-8771-7e0ee7f08bcc

	measure BusinessProfit_Selector_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([BusinessProfit_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales\LineGraph
		lineageTag: c48ba92e-2209-4136-8a42-5ae6870a3475

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure temp_value = 999999
		formatString: 0
		displayFolder: Scorecard
		lineageTag: 92a2fcf8-f030-4c14-b4ac-d1a86caafdf6

	measure temp_value2 = 999999
		formatString: 0
		displayFolder: Scorecard
		lineageTag: d865604d-64a6-47d0-bbe8-2ad3c3ec79b3

	measure temp_value3 = 999999
		formatString: 0
		displayFolder: Scorecard
		lineageTag: 3c3854f2-efda-407c-aa7b-385bb6a6186a

	measure Pareto_Country =
			
			VAR allSelectedCountry = ALLSELECTED('Selector Table - Country')
			VAR countryTable = ADDCOLUMNS(allSelectedCountry, "@Count", [Pareto_ESC_Revenue_Country])
			VAR currentCount = [Pareto_ESC_Revenue_Country]
			VAR cumulCountryTable = FILTER(countryTable, [@Count] >= currentCount)
			VAR cumulCountry = sumx(cumulCountryTable, [@Count])
			VAR totalCountry = sumx(countryTable, [@Count])
			RETURN cumulCountry / totalCountry
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Pareto
		lineageTag: 30a4d85c-d7e0-4936-b15d-517e0cd194f9

	measure Min = 0
		formatString: 0
		displayFolder: Bullet
		lineageTag: df6c196f-1d16-4986-83ed-b28dcda10b1a

	measure Good = 1500000
		formatString: 0
		displayFolder: Bullet
		lineageTag: 52076fb9-6d63-426f-9eb8-40e416fc6fd9

	measure Max = 10000000000
		formatString: 0
		displayFolder: Bullet
		lineageTag: 77104697-ed31-4990-984f-c6ab74a7d069

	measure 'Needs Improvement' = 500000
		formatString: 0
		displayFolder: Bullet
		lineageTag: 1f7da3cd-2176-4568-ab82-5926b8524125

	measure Satisfactory = 1000000
		formatString: 0
		displayFolder: Bullet
		lineageTag: 2fc53051-b53c-4f5a-a391-ed596a0c1f85

	measure Target = 1500000
		formatString: 0
		displayFolder: Bullet
		lineageTag: 78c613cb-6c26-4561-ac99-66eb683c7e9d

	measure 'Very Good' = 2000000
		formatString: 0
		displayFolder: Bullet
		lineageTag: 3f779ad2-21cc-443b-b5a0-f72b091c0c7c

	measure Sales_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [Sales_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		formatString: #,##0.0
		displayFolder: Sales
		lineageTag: c5210816-19bf-4a4d-a453-0c205a735a39

	measure SGA_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [SGA_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		formatString: #,##0.0
		displayFolder: SGA
		lineageTag: e3cc0cf2-45a3-41ce-9d43-bd512aa7a5ca

	measure SGA_Ratio_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [SGA_Ratio_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		formatString: 0.0%;-0.0%
		displayFolder: SGA Ratio
		lineageTag: 3c9ae2d4-2a88-41b0-ade2-8bd00da02954

		annotation PBI_FormatHint = {"isCustom":true}

	measure BusinessProfit_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [BusinessProfit_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		formatString: #,##0.0
		displayFolder: Business Profit
		lineageTag: 7ab261cf-767c-483b-9525-5642f18da21b

	measure BusinessProfitRatio_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [BusinessProfitRatio_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		formatString: 0.0%;-0.0%
		displayFolder: Business Profit
		lineageTag: 76675487-fa49-4ebb-bd01-3d96c0b15ed3

		annotation PBI_FormatHint = {"isCustom":true}

	measure Sales_FC_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [Sales_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		formatString: #,##0.0
		displayFolder: Sales
		lineageTag: 8f5e61b6-1769-48b1-9e7e-aade72a6e13a

	measure SGA_FC_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [SGA_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		formatString: #,##0.0
		displayFolder: SGA
		lineageTag: 50ea75da-edea-4511-b7df-1215fc3c34d5

	measure SGA_Ratio_FC_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [SGA_Ratio_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		formatString: 0.0%;(0.0%)
		displayFolder: SGA Ratio
		lineageTag: 59e9da0e-753f-4913-9ce1-717ef7473c1a

		annotation PBI_FormatHint = {"isCustom":true}

	measure BusinessProfit_FC_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [BusinessProfit_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		formatString: #,##0.0
		displayFolder: Business Profit
		lineageTag: d1c1cfb2-4ab3-4fb4-934f-696a3b2f1cac

	measure BusinessProfitRatio_FC_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [BusinessProfitRatio_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		formatString: 0.0%;-0.0%
		displayFolder: Business Profit
		lineageTag: ae2b68be-ceca-47b6-90d2-b42f9b2ccdde

		annotation PBI_FormatHint = {"isCustom":true}

	measure SGA_Selector_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SGA_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Overview\LineGraph
		lineageTag: 43c122ed-f540-414a-8cfc-9c0e174ca741

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Selector_LineGraph_PrevYearActual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SGA_PrevYearActual_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Overview\LineGraph
		lineageTag: 4e04d47a-bc97-4ae3-8ca5-7512ea7e7d98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Selector_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SGA_FC_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Overview\LineGraph
		lineageTag: b5d1dd63-8096-48ba-9369-ac35a621607c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_PrevYearActual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([Sales_PrevYearActual_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Overview\LineGraph
		lineageTag: ebc594fd-c8fd-4d2b-b34a-d945519ee52d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([Sales_FC_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Overview\LineGraph
		lineageTag: 254c8c50-282e-4eee-afc2-84cfb45a1e03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Ratio_Selector_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SGA_Ratio_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Overview\LineGraph
		lineageTag: 592f3221-ed84-4ba2-a09c-7bb8d9b22ad7

	measure SGA_Ratio_Selector_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SGA_Ratio_FC_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Overview\LineGraph
		lineageTag: 717a4673-65ca-4bc5-abc7-c938039f30b9

	measure SGA_Ratio_Selector_LineGraph_PrevYearActual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SGA_Ratio_PrevYearActual_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Overview\LineGraph
		lineageTag: 60b79688-6bd9-497c-96ab-ae4215c2b831

	measure BusinessProfit_Selector_LineGraph_PrevYearActual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([BusinessProfit_PrevYearActual_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Overview\LineGraph
		lineageTag: 312028ea-b602-4e35-9a50-f0ed0ed27c29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit_Selector_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([BusinessProfit_FC_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Overview\LineGraph
		lineageTag: a0f36e56-d528-4c5b-a7b5-c714bc73e459

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfitRatio_Selector_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([BusinessProfitRatio_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Overview\LineGraph
		lineageTag: 326792e3-23f8-47c8-88c0-44c959cedc27

	measure BusinessProfitRatio_Selector_LineGraph_PrevYearActual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([BusinessProfitRatio_PrevYearActual_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Overview\LineGraph
		lineageTag: f3ed60d0-843e-413c-9146-95397e2cda71

	measure BusinessProfitRatio_Selector_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([BusinessProfitRatio_FC_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Overview\LineGraph
		lineageTag: bdf8840c-02d1-4532-a07b-3cc303b75635

	measure ASCost_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        HIER_InStMeasure[InStMeasure_L1] = "AS Cost"
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 752e0c75-3294-45af-867b-bc87ca40aba2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Ratio_Selector_Scorecard_Actual =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([SGA_Ratio_Selector], REMOVEFILTERS(DIM_ProfitCenter[ProfitCenter]), REMOVEFILTERS(HIER_ProfitCenter), REMOVEFILTERS('DIM_ProfitCenter - Alias & Ordering'), 'DIM_ProfitCenter - Alias & Ordering'[ProfitCenter] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual"),
			        CALCULATE([SGA_Ratio_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual")
			    )
		displayFolder: 13Mar\SGA Ratio
		lineageTag: 28cb7512-8af2-405c-9a59-796cd2e3c0d7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Ratio_Selector_Scorecard_FC =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([SGA_Ratio_Selector], REMOVEFILTERS(DIM_ProfitCenter[ProfitCenter]), REMOVEFILTERS(HIER_ProfitCenter), REMOVEFILTERS('DIM_ProfitCenter - Alias & Ordering'), 'DIM_ProfitCenter - Alias & Ordering'[ProfitCenter] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = selectedScenario),
			        CALCULATE([SGA_Ratio_Selector], HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = selectedScenario)
			    )
		displayFolder: 13Mar\SGA Ratio
		lineageTag: 0e6ee40f-ab13-4fd7-9956-de36caaa2b13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Ratio_Selector_Scorecard_ActualvsFC = [SGA_Ratio_Selector_Scorecard_Actual] / [SGA_Ratio_Selector_Scorecard_FC]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\SGA Ratio
		lineageTag: 1ac8779b-bd8d-4550-bb70-bdb0ef2de66a

	measure Scorecard_HariRatio_MTH_Actual =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR vHari =
			    CALCULATE(
			        [Sales_MTH],
			        DIM_Country[Country] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L8] = "Hari (BPD) - FY24",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_MTH],
			        DIM_Country[Country] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L8] = "BPD (Local) - FY20",
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			RETURN vHari / vBPD
		displayFolder: 13Mar\Scorecard
		lineageTag: ca0c8cdf-2356-4010-82e4-62f519f70b96

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_HariRatio_YTD =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR vHari =
			    CALCULATE(
			        [Sales_YTD],
			        HIER_Country[Country_L1] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_YTD],
			        HIER_Country[Country_L1] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			
			RETURN vHari / vBPD
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: 089a9668-fdfb-4df1-ba58-daa4faf03fd5

	measure Scorecard_HariRatio_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Scorecard_HariRatio_MTH],
			        "YTD", [Scorecard_HariRatio_YTD]
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 69e6ae57-9203-4ddb-a7de-bb7499f38c97

	measure BusinessProfit%_Selector_Actual =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([BusinessProfitRatio_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual"),
			        CALCULATE([BusinessProfitRatio_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual")
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: 2c474eb4-f9b7-4d04-84c5-b942a207e497

	measure BusinessProfit%_Selector_FC =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([BusinessProfitRatio_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = selectedScenario),
			        CALCULATE([BusinessProfitRatio_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "BPD - PH18", DIM_Country[Country] = selectedCountry, DIM_Scenario[Scenario] = selectedScenario)
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 95583671-c325-4281-b33c-bed1588b4e53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit%_Selector_ActualvsFC = [BusinessProfit%_Selector_Actual] / [BusinessProfit%_Selector_FC]
		displayFolder: 13Mar\Scorecard
		lineageTag: 030efb2f-4dd7-4b6d-9bf9-89b73fb5a32a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBU_SalesAchievement%_Selector =
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			
			RETURN
			    CALCULATE([Sales_Achievement_Selector], HIER_ProfitCenter[ProfitCenter_L9] = selectedBU, DIM_Country[Country] = "Finance Consol without EPIL")
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: 81a2da98-d898-4a7f-8791-d241022bc0ac

	measure ScorecardBU_SGARatio_Selector_ActualvsFC = [ScorecardBU_SGARatio_Selector_Actual] / [ScorecardBU_SGARatio_Selector_FC]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: 480e11d1-f97d-44c0-9e47-2b87d13e00f6

	measure ScorecardBU_SGARatio_Selector_Actual = ```
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			
			RETURN
			    CALCULATE(
			        [SGA_Ratio_Selector], 
			        HIER_ProfitCenter[ProfitCenter_L9] = selectedBU, 
			        DIM_Country[Country] = "Finance Consol without EPIL", 
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: 13Mar\Scorecard
		lineageTag: 14313443-4aa7-4542-9ae9-e8078976d56b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBU_SGARatio_Selector_FC = ```
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [SGA_Ratio_Selector], 
			        HIER_ProfitCenter[ProfitCenter_L9] = selectedBU, 
			        DIM_Country[Country] = "Finance Consol without EPIL", 
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			```
		displayFolder: 13Mar\Scorecard
		lineageTag: c93737a2-b757-41fb-88e2-a7ca5b57cc2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Pareto_ESC_Revenue_Country = ```
			
			
			var selectedPC = SELECTEDVALUE(HIER_ProfitCenter[ProfitCenter_L9])
			var selectedScenario = "Actual"
			var selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			var userSelectedScenario = "Actual"
			 
			// var result =
			RETURN
			    SWITCH(selectedCountry,
			        "ESD", CALCULATE([Sales_Achievement_Selector], HIER_Country[Country_L1] = "ESD", DIM_Scenario[Scenario] = userSelectedScenario),
			        // "ETH_Total", CALCULATE([Sales_Achievement_MTH], HIER_Country[Country_L1] = "ETH_Total", DIM_Scenario[Scenario] = userSelectedScenario),
			        "ETH", CALCULATE([Sales_Achievement_Selector], DIM_Country[Country] = "ETH", DIM_Scenario[Scenario] = userSelectedScenario),
			        "EPC", CALCULATE([Sales_Achievement_Selector], HIER_Country[Country_L1] = "EPC", DIM_Scenario[Scenario] = userSelectedScenario),
			        "EMSB", CALCULATE([Sales_Achievement_Selector], HIER_Country[Country_L1] = "EMSB", DIM_Scenario[Scenario] = userSelectedScenario),
			        "IDC", CALCULATE([Sales_Achievement_Selector], DIM_Country[Country] = "IDC", DIM_Scenario[Scenario] = userSelectedScenario),
			        "EIN-IDR", CALCULATE([Sales_Achievement_Selector], HIER_Country[Country_L1] = "EIN-IDR", DIM_Scenario[Scenario] = userSelectedScenario),
			        "Others Dir", CALCULATE([Sales_Achievement_Selector], HIER_Country[Country_L1] = "Others Dir", DIM_Scenario[Scenario] = userSelectedScenario),
			        "Total EVNL", CALCULATE([Sales_Achievement_Selector], HIER_Country[Country_L1] = "Total EVNL", DIM_Scenario[Scenario] = userSelectedScenario),
			        "MD", 
			        IF(
			            OR(selectedPC = "Finance (Local) - FY20", selectedPC = "ED - PH16"),
			            CALCULATE([Sales_Achievement_Selector], HIER_Country[Country_L1] = "Finance Consol without EPIL", 'DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias] = "MD", DIM_Scenario[Scenario] = userSelectedScenario),
			            0
			        ),    
			        BLANK()
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13Mar\Pareto
		lineageTag: 083db79a-da9e-44c6-a55f-837cfd4aa413

	measure Currency_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", "IDR",
			        "EMSB", "MYR",
			        "EPC", "PHP",
			        "ETH_Total", "THB",
			        "Total EVNL", "VND",
			        "MD", "SGD",
			        "ESP", "SGD"
			    )
		displayFolder: 13Mar
		lineageTag: 83a4417e-3e8a-4b93-ae5d-acf52d470219

	measure Pareto_ProductGroup =
			
			VAR allProductGroup = ALLSELECTED('Selector Table - Product Category'[Product Category])
			VAR productGroupTable = ADDCOLUMNS(allProductGroup, "@Count", [ESC_Revenue_ProductGroup])
			VAR currentCount = [ESC_Revenue_ProductGroup]
			VAR cumulProductGroupTable = FILTER(productGroupTable, [@Count] >= currentCount)
			VAR cumulProductGroup = sumx(cumulProductGroupTable, [@Count])
			VAR totalProductGroup = sumx(productGroupTable, [@Count])
			RETURN cumulProductGroup / totalProductGroup
		displayFolder: Pareto
		lineageTag: 591f8ae8-a73b-4037-9453-134791f2c28f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ESC_Revenue_ProductGroup = ```
			
			 
			var selectedScenario = "Actual"
			var selectedProductGroup = SELECTEDVALUE('Selector Table - Product Category'[Product Category])
			var actualScenario = "Actual"
			 
			return
			            SWITCH(selectedProductGroup,
			                "CISS", CALCULATE([Sales_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "CISS_FY20"),
			                "SIDM", CALCULATE([Sales_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "SIDM/PLQ (Local)"),
			                "SP", CALCULATE([Sales_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Small Printer (Local)"),
			                "Corporate BU", CALCULATE([Sales_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Corporate BU"),
			                "Printer others", CALCULATE([Sales_PrinterOthers_Selector], DIM_Scenario[Scenario] = actualScenario),
			                "LFP (excl Corp)", CALCULATE([Sales_LFP_Selector], DIM_Scenario[Scenario] = actualScenario),
			                "VI", CALCULATE([Sales_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "VI - PH16"),
			                "IIJ", CALCULATE([Sales_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "IIJ"),
			                "RS", CALCULATE([Sales_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "FA - PH16")
			            )
			```
		formatString: #,0
		displayFolder: Pareto
		lineageTag: e92fe8dd-7f44-492f-9598-455686918ead

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ASCost_YTD_Actual = ```
			
			    CALCULATE(
			        [ASCost_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 2b84f94a-0d50-4f27-bd5a-764f2f0d40c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_YTD_FC =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [ASCost_YTD],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 594bff31-a45d-48ee-b9b2-2cd04c75eb22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_YTD_VarianceValue = ([ASCost_YTD_Actual] - [ASCost_YTD_FC])
		displayFolder: SGA\SGA Position
		lineageTag: 5a72a3f9-4308-4221-99d8-25bfc21c644a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_YTD_VariancePercent = [ASCost_YTD_Actual] / [ASCost_YTD_FC]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA\SGA Position
		lineageTag: d50bf696-40d7-43c3-8a41-350586eca9b2

	measure ASCostDivideSales_Actual =
			
			VAR ASCost =
			    CALCULATE(
			        [ASCost_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR Sales =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			RETURN ASCost / Sales
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA\SGA Position
		lineageTag: a9bcf0e6-f909-4f43-be3a-67a649a090d3

	measure ASCostDivideSales_FC =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR ASCost =
			    CALCULATE(
			        [ASCost_YTD],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			
			VAR Sales =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			
			RETURN ASCost / Sales
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA\SGA Position
		lineageTag: 4620f052-c768-45b8-8119-056ef16ff0e0

	measure ASCostDivideSales_ActualMinusFC = ([ASCostDivideSales_Actual] - [ASCostDivideSales_FC])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA\SGA Position
		lineageTag: d7b907fa-43f2-4f45-8a06-f13669a14100

	measure ASCost_Country_YTD_Actual = ```
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR esp_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = "Actual", DIM_Country[Country] = "ESP")
			VAR esd_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = "Actual", DIM_Country[Country] = "ESD")
			VAR espEVNL_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = "Actual", DIM_Country[Country] = "ESP-EVNL")
			
			VAR ETH_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = "Actual", DIM_Country[Country] = "ETH")
			VAR IDC_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = "Actual", DIM_Country[Country] = "IDC")
			
			RETURN    
			    SWITCH(
			        selectedCountry,
			        "RHQ", (esp_ASCost - esd_ASCost - espEVNL_ASCost),
			        "ETH_Total", (ETH_ASCost + IDC_ASCost),
			        "Total EVNL", CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = "Actual", HIER_Country[Country_L1] = selectedCountry),
			        CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = "Actual", DIM_Country[Country] = selectedCountry)
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 5fa3b279-83bd-4cec-a40a-9687445f17cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_Country_YTD_FC = ```
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR esp_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = selectedScenario, DIM_Country[Country] = "ESP")
			VAR esd_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = selectedScenario, DIM_Country[Country] = "ESD")
			VAR espEVNL_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = selectedScenario, DIM_Country[Country] = "ESP-EVNL")
			
			VAR ETH_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = selectedScenario, DIM_Country[Country] = "ETH")
			VAR IDC_ASCost = CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = selectedScenario, DIM_Country[Country] = "IDC")
			
			RETURN    
			    SWITCH(
			        selectedCountry,
			        "RHQ", (esp_ASCost - esd_ASCost - espEVNL_ASCost),
			        "ETH_Total", (ETH_ASCost + IDC_ASCost),
			        "Total EVNL", CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = selectedScenario, HIER_Country[Country_L1] = selectedCountry),
			        CALCULATE([ASCost_YTD], DIM_Scenario[Scenario] = selectedScenario, DIM_Country[Country] = selectedCountry)
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: acbd5b3a-6fd3-467b-843c-c6d9663e3ccf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_Country_YTD_ActualMinusFC = [ASCost_Country_YTD_Actual] - [ASCost_Country_YTD_FC]
		displayFolder: SGA\SGA Position
		lineageTag: 1ddf84e1-52e7-4fc1-a0c9-ad650f0b6bd5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_Country_YTD_ActualDivideFC = [ASCost_Country_YTD_Actual] / [ASCost_Country_YTD_FC]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA\SGA Position
		lineageTag: 0d661674-59e2-4bc4-a4cd-2fb80f371cdf

	measure ScorecardBU_TotalA&P_Selector =
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			
			RETURN
			    CALCULATE(
			        [TotalA&P_YTD_ActualvsFC],
			        HIER_ProfitCenter[ProfitCenter_L9] = selectedBU,
			        DIM_Country[Country] = "Finance Consol without EPIL"
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: a694f601-7f07-4ea2-9868-bc9592ec34df

	measure ScorecardBP_Sales_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE([Sales_YTD_Actual_WOElim], HIER_Country[Country_L1] = "EIN-IDR"),
			        "EMSB", CALCULATE([Sales_YTD_Actual_WOElim], HIER_Country[Country_L1] = "EMSB"),
			        "EPC", CALCULATE([Sales_YTD_Actual_WOElim], HIER_Country[Country_L1] = "EPC"),
			        "ETH_Total", CALCULATE([Sales_YTD_Actual_WOElim], HIER_Country[Country_L1] = "ETH_Total"),
			        "Total EVNL", CALCULATE([Sales_YTD_Actual_WOElim], HIER_Country[Country_L1] = "Total EVNL"),
			        "MD", CALCULATE([Sales_YTD_Actual_WOElim], HIER_Country[Country_L1] = "ESP", HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16"),
			        "ESP", CALCULATE([Sales_YTD_Actual_WOElim], DIM_Country[Country] = "ESP")
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 9da9a60a-d43e-4669-a5dd-9d2062bf71b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBP_BusinessProfit_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE([BusinessProfit_YTD_Actual], HIER_Country[Country_L1] = "EIN-IDR"),
			        "EMSB", CALCULATE([BusinessProfit_YTD_Actual], HIER_Country[Country_L1] = "EMSB"),
			        "EPC", CALCULATE([BusinessProfit_YTD_Actual], HIER_Country[Country_L1] = "EPC"),
			        "ETH_Total", CALCULATE([BusinessProfit_YTD_Actual], HIER_Country[Country_L1] = "ETH_Total"),
			        "Total EVNL", CALCULATE([BusinessProfit_YTD_Actual], HIER_Country[Country_L1] = "Total EVNL"),
			        "MD", CALCULATE([BusinessProfit_YTD_Actual], DIM_Country[Country] = "ESP", HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16"),
			        "ESP", CALCULATE([BusinessProfit_YTD_Actual], DIM_Country[Country] = "ESP")
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: aca1da9f-cb9e-4db6-ba6f-5530d92cb1e5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBP_BusinessProfitDivideSales = [ScorecardBP_BusinessProfit_Selector] / [ScorecardBP_Sales_Selector]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: 52aedc7c-3b9a-4f40-92dc-8901913cfea5

	measure SGARatio_Selector_LineGraph_EINIDR = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EIN-IDR"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f6205dd0-4982-4160-a4ef-fcc39d27af24

	measure TotalA&P_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalA&P_MTH],
			        "YTD", [TotalA&P_YTD]
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 7fbd9f46-b0ef-40b0-8ad4-1bd73bce242e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_Selector_LineGraph =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([TotalA&P_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		lineageTag: 028b135b-e024-420e-84c8-6d66e64f18bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGARatio_Selector_LineGraph_EMSB = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EMSB"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ed0ed516-7554-41d0-a670-ec5b8dfe6209

	measure TotalA&P_Selector_LineGraph_EINIDR = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalA&P_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EIN-IDR"
			    )
			return result
			```
		formatString: #,0.00
		lineageTag: b8b92703-eee7-444a-9e17-73ed36ec4cf9

	measure TotalA&P_Selector_LineGraph_EMSB = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalA&P_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EMSB"
			    )
			return result
			```
		formatString: #,0.00
		lineageTag: e3cee47a-acc9-4f82-8f77-043809482ca3

	measure SGARatio_Selector_LineGraph_EPC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EPC"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9afb2105-5bac-4ae2-aef0-7c6c99ab674d

	measure SGARatio_Selector_LineGraph_ETHTotal = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        HIER_Country[Country_L1] = "ETH_Total"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 07670ddc-1f5e-40b5-828e-fa55ddb3fd9d

	measure SGARatio_Selector_LineGraph_ESD = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "ESD"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 0ce5a67e-320a-46ec-be2f-ea12116fae8e

	measure SGARatio_Selector_LineGraph_EVNL = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EVNL"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6fc5da9c-e357-48d7-985e-0d1b1612761f

	measure TotalA&P_Selector_LineGraph_EPC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalA&P_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EPC"
			    )
			return result
			```
		formatString: 0.00
		lineageTag: 11dec7fd-da64-41e5-bede-48cf4dd92adc

	measure TotalA&P_Selector_LineGraph_ETH = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalA&P_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "ETH"
			    )
			return result
			```
		lineageTag: 5159df44-7367-4e91-967c-031cf82acbfc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_Selector_LineGraph_IDC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalA&P_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "IDC"
			    )
			return result
			```
		lineageTag: 8b0f4eef-e826-4e62-98bd-0aaf65bac9ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_Selector_LineGraph_ESD = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalA&P_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "ESD"
			    )
			return result
			```
		lineageTag: 42cc5581-7341-4f0f-8b64-5a189b6cdda8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_Selector_LineGraph_EVNL = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalA&P_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EVNL"
			    )
			return result
			```
		lineageTag: 7e60ee36-aad9-400d-beb0-1bcb6f38da4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_ActualvsPrevYear_Selector = ([Sales_Selector_Actual] / [Sales_PrevYearActual_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: 5b990c2e-4898-467a-b3a8-dcd330309ae6

	measure testrev = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual")
		lineageTag: 1019e1ec-27c8-410c-ab93-a99771c0db40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_ActualvsFC_Selector = ([Sales_Selector_Actual] / [Sales_FC_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: e9bd2842-12d1-45a8-8f34-e878209fd9b1

	measure SGA_ActualvsPrevYear_Selector = ([SGA_Selector_Actual] / [SGA_PrevYearActual_Selector])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA
		lineageTag: f369c985-ddb4-41ff-9644-aba0efeb959e

	measure SGA_ActualvsFC_Selector = ([SGA_Selector_Actual] / [SGA_FC_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA
		lineageTag: a2892028-fe41-4893-9582-18d94103b2c3

	measure BusinessProfit_ActualvsPrevYear_Selector = ([BusinessProfit_Selector_Actual] / [BusinessProfit_PrevYearActual_Selector])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Business Profit
		lineageTag: d23f481c-10f3-4ec9-9da0-61cdc95a4330

	measure BusinessProfit_ActualvsFC_Selector = ([BusinessProfit_Selector_Actual] / [BusinessProfit_FC_Selector])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Business Profit
		lineageTag: 8755dbec-77fa-4c4b-9159-58f8e70ec6be

	measure TotalA&P_test = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR TotalAP_Actual = 
			    CALCULATE(
			        [TotalA&P_YTD],
			        DIM_Scenario[Scenario] = "Actual",
			        FACT_Consol[Account] = "Total A&P"
			    )
			
			VAR TotalAP_FC =
			    CALCULATE(
			        [TotalA&P_YTD],
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
			
			RETURN TotalAP_Actual
			```
		displayFolder: SGA\SGA Position
		lineageTag: 46d2c758-3898-475d-8e48-7d18d54b719e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Ratio_ActualvsPrevYear_Selector = ([SGA_Ratio_Selector_Actual] / [SGA_Ratio_PrevYearActual_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA Ratio
		lineageTag: e98e0c0f-9e33-4106-9b7b-863aafa49337

	measure SGA_Ratio_ActualvsFC_Selector = ([SGA_Ratio_Selector_Actual] / [SGA_Ratio_FC_Selector])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: SGA Ratio
		lineageTag: 634c6bdc-00a1-4772-8abe-2dbc8bbc0387

	measure BusinessProfitRatio_ActualvsPrevYear_Selector = ([BusinessProfitRatio_Selector_Actual] / [BusinessProfitRatio_PrevYearActual_Selector])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Business Profit
		lineageTag: b72b89b7-3448-4dc6-abae-cf691aef0681

	measure BusinessProfitRatio_ActualvsFC_Selector = ([BusinessProfitRatio_Selector_Actual] / [BusinessProfitRatio_FC_Selector])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Business Profit
		lineageTag: 66455495-e596-4f03-b8ff-77b5355e5d79

	measure Sales_PC_ActualvsFC_Selector = ```
			
			VAR selectedPC = SELECTEDVALUE('Selector Table - TotalCo BPD ED'[ProfitCenter_Name])
			VAR vTotalCo = 
			    CALCULATE(
			        [Sales_ActualDivideFC_Selector],
			        HIER_Country[Country_L1] = "Finance Consol without EPIL",
			        HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_ActualDivideFC_Selector],
			        HIER_Country[Country_L1] = "Finance Consol without EPIL",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			
			VAR vED =
			    CALCULATE(
			        [Sales_ActualDivideFC_Selector],
			        HIER_Country[Country_L1] = "Finance Consol without EPIL",
			        HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16"
			    )
			
			RETURN
			    SWITCH(
			        selectedPC,
			        "Total Co", vTotalCo,
			        "BPD", vBPD,
			        "MD", vED
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: ddd1a4ec-7ed4-4e45-9e0d-ada2ecf0203a

	measure Sales_ActualDivideFC_Selector = [Sales_Selector_Actual] / [Sales_FC_Selector]
		displayFolder: Sales
		lineageTag: c9d5eced-ec51-4be7-92f5-c0e5805f11b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven%_MTH = ```
			
			VAR vSlowInven =
			    CALCULATE(
			        SUMX(FACT_Inventory, FACT_Inventory[ACT_EXRATE_SGD] * FACT_Inventory[Value]),
			        NOT FACT_Inventory[SMS] IN {"<30Days", ">=30&<60Days", ">=60Days", ">=90Days", ">=120Days", ">=150Days"},
			        NOT LEFT(FACT_Inventory[ProfitCenter], 3) = "P14",
			        NOT FACT_Inventory[Exclude_SKU_Filter] = "Reporting"
			    )
			
			VAR vRollingAvgSales =
			    CALCULATE(
			        CALCULATE([SUM_Value], 'Selector Table - Currency'[Currency] = "SGD"),
			        DATESINPERIOD('DIM_Calendar'[Year Month], LASTDATE(DIM_Calendar[Year Month]), -12, MONTH), 
			        NOT LEFT(FACT_Consol[ProfitCenter], 3) = "P14",
			        LEN(FACT_Consol[ProfitCenter]) < 7, 
			        FACT_Consol[Account] = "AZZZZZ",
			        FACT_Consol[Scenario] = "Actual"
			    )
			
			// RETURN
			//     SWITCH(
			//         SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA General]),
			//         "Consol", 
			//         CALCULATE(
			//             vSlowInven / (vRollingAvgSales/12), 
			//             REMOVEFILTERS(FACT_Consol[Country]), 
			//             FACT_Consol[Country] = "Finance Consol without EPIL", 
			//             REMOVEFILTERS(FACT_Inventory[Country])
			//         ),
			//         vSlowInven / (vRollingAvgSales/12)
			//     )
			RETURN vSlowInven / (vRollingAvgSales/12)
			// RETURN vRollingAvgSales/12
			```
		lineageTag: 9f0a606b-509a-43aa-aeea-9d75cffcdb2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven%_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [SlowInven%_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		lineageTag: c064650c-4c0c-469d-92e8-245aa40bbfae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven%_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [SlowInven%_MTH],
			        "YTD", [SlowInven%_YTD]
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 55bd1108-a329-4397-9971-21fc68b28e30

	measure SlowInven%_Selector_LineGraph_EIN = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			// var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var previousDates = DATESINPERIOD('Presentation Calendar'[Year Month], ReferenceDate, -12, MONTH)
			var result = 
			    CALCULATE(
			        [SlowInven%_MTH], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Country[Country] = "EIN-IDR"
			    )
			return result
			```
		lineageTag: f1cdf95d-c6ae-4083-bc45-d57c1110967a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven%_Selector_LineGraph_EMSB = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			// var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var previousDates = DATESINPERIOD('Presentation Calendar'[Year Month], ReferenceDate, -12, MONTH)
			var result = 
			    CALCULATE(
			        [SlowInven%_MTH], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Country[Country] = "EMSB"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 51cfb84a-313b-4bda-b6af-57aab9bd20be

	measure SlowInven%_Selector_LineGraph_EPC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			// var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var previousDates = DATESINPERIOD('Presentation Calendar'[Year Month], ReferenceDate, -12, MONTH)
			var result = 
			    CALCULATE(
			        [SlowInven%_MTH], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Country[Country] = "EPC"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 589aa299-2e73-4be0-a8e5-d047304b6ac0

	measure SlowInven%_Selector_LineGraph_ESP = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			var previousDates = DATESINPERIOD('Presentation Calendar'[Year Month], ReferenceDate, -12, MONTH)
			
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			// VAR StartYTDDate =
			//      IF(
			//          CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			//          DATE(CurrentYearCY - 1, 4, 1),
			//          DATE(CurrentYearCY, 4, 1)
			//      )
			// VAR StartDate = DATE(CurrentYearCY - 1, CurrentMonthCY, 1)
			
			// var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SlowInven%_MTH], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Country[Country] = "ESP"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 195b0036-1b20-42e5-9f64-2e5cfe0ed9fe

	measure SlowInven%_Selector_LineGraph_ESPCONSO = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			// var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var previousDates = DATESINPERIOD('Presentation Calendar'[Year Month], ReferenceDate, -12, MONTH)
			var result = 
			    CALCULATE(
			        [SlowInven%_MTH], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        REMOVEFILTERS(FACT_Consol[Country]),
			        FACT_Consol[Country] = "Finance Consol without EPIL",
			        REMOVEFILTERS(FACT_Inventory[Country])
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 69f7e9bb-526d-44a9-8cd3-cbe38e6427b4

	measure SlowInven%_Selector_LineGraph_ETH = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			// var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var previousDates = DATESINPERIOD('Presentation Calendar'[Year Month], ReferenceDate, -12, MONTH)
			var result = 
			    CALCULATE(
			        [SlowInven%_MTH], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        FACT_Consol[Country] IN {"ETH", "IDC"},
			        FACT_Inventory[Country] = "ETH"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4fefdf06-af0d-4c58-853d-c437176d5159

	measure SlowInven%_Selector_LineGraph_EVNL = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			// var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var previousDates = DATESINPERIOD('Presentation Calendar'[Year Month], ReferenceDate, -12, MONTH)
			var result = 
			    CALCULATE(
			        [SlowInven%_MTH], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Country[Country] = "EVNL"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 56217af7-39cb-45e3-b175-3ce3e2361e4f

	measure 'Overview Actual' =
			
			SELECTEDVALUE(DIM_Calendar[FY Year]) & " " & SELECTEDVALUE(DIM_Calendar[Month])
		displayFolder: Dynamic Text
		lineageTag: 81564238-8b24-4d98-ae88-f7c3e1c8354f

	measure 'Overview Scenario' =
			
			SELECTEDVALUE(DIM_Calendar[FY Year]) & " " & SELECTEDVALUE('Selector Table - Scenario'[Alias])
		displayFolder: Dynamic Text
		lineageTag: d523f6ba-8283-47be-bc96-fb81760db78f

	measure 'Overview PY' =
			
			Var SelectedFY = SELECTEDVALUE(DIM_Calendar[FY Year])
			VAR SelectedYearMonth = FORMAT(SELECTEDVALUE(DIM_Calendar[FY Year Month]), "Mmm YY")
			VAR FiscalYear = RIGHT(SelectedYearMonth, 2)
			VAR SelectedMonth = SELECTEDVALUE(DIM_Calendar[Month])
			VAR PY = FiscalYear - 1
			RETURN
			"FY" & CONVERT(PY, STRING) & " " & SelectedMonth
		displayFolder: Dynamic Text
		lineageTag: 968453a9-36ab-47b2-bc1d-5e19d4f5b9cc

	measure 'OverviewByPG Sales' = ```
			
			    "Sales - " & 
			    IF(
			        ISFILTERED('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),
			        IF(
			            HASONEVALUE('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),
			            SELECTEDVALUE('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),
			            CONCATENATEX(VALUES('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),'DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias],", ")
			        ),
			        "All Product Groups")
			```
		displayFolder: Dynamic Text
		lineageTag: a6eb8a14-495d-4e47-ba72-9383f8eebf56

	measure 'SalesbyESC KPICard Comparison' = ```
			
			    IF(
			        HASONEVALUE('Selector Table - Scenario'[Scenario]),
			        SELECTEDVALUE('Selector Table - Scenario'[Alias]),
			        "Please select comparison")
			
			```
		displayFolder: Dynamic Text
		lineageTag: 27492569-524e-42a4-9ad6-5a230c66098f

	measure 'SalesbyESC KPICard PY' =
			
			"FY" &
			    VAR SelectedYear = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			    Var YearOnly = RIGHT(SelectedYear, 2)
			    VAR PY = VALUE(YearOnly)-1
			    RETURN
			    CONVERT(PY, STRING)
		displayFolder: Dynamic Text
		lineageTag: b430df2f-74f9-45e8-aac5-fe0d04e2fa93

	measure 'OverviewByPG Revenue Bar' = ```
			
			    "Revenue by ESC - " & 
			    IF(
			        ISFILTERED('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),
			        IF(
			            HASONEVALUE('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),
			            SELECTEDVALUE('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),
			            CONCATENATEX(VALUES('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias]),'DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias],", ")
			        ),
			        "All Product Groups")
			```
		displayFolder: Dynamic Text
		lineageTag: 95822096-8b84-4dde-9bbd-6c7aaf4454ae

	measure 'SalesbyESC Revenue Bar' = ```
			
			    "Revenue by Product Groups - " & 
			    IF(
			        ISFILTERED(DIM_Country[Country]),
			        IF(
			            HASONEVALUE(DIM_Country[Country]),
			            SELECTEDVALUE(DIM_Country[Country]),
			            CONCATENATEX(VALUES(DIM_Country[Country]),DIM_Country[Country],", ")
			        ),
			        "All ESCs")
			```
		displayFolder: Dynamic Text
		lineageTag: 57589f85-2902-4586-be1c-07ac717b4f04

	measure SalesMinus =
			
			"FY"&
			VAR SelectedYearMonth = SELECTEDVALUE(DIM_Calendar[Year Month])
			VAR YearOnly = RIGHT(SelectedYearMonth, 2)
			VAR PY = VALUE(YearOnly) -1
			RETURN
			CONVERT(PY,STRING)
			&
			" Sales Minus"
		displayFolder: Dynamic Text
		lineageTag: f10d177b-42dd-46ec-a592-4d2a51c3f408

	measure TacticalRebate =
			
			SELECTEDVALUE('Selector Table - Scenario'[Alias])
		displayFolder: Dynamic Text
		lineageTag: 2af823d8-3227-4ff9-8b8b-606a5053ab63

	measure 'OverviewbyPG KPICard Comparison' = ```
			
			    IF(
			        HASONEVALUE('Selector Table - Scenario'[Alias]),
			        SELECTEDVALUE('Selector Table - Scenario'[Alias]),
			        "Please select comparison")
			
			```
		displayFolder: Dynamic Text
		lineageTag: 56e0a22e-5472-4d64-a8d6-cd5ff78fa06c

	measure 'SGAOverview Comparison' = ```
			
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Alias], "No scenario selected")
			RETURN SelectedScenario
			
			```
		displayFolder: Dynamic Text
		lineageTag: f9d30d02-25bd-4fdd-8df4-8b30b783f93c

	measure 'SGAOverview Date' = ```
			
			    "YTD " &
			    SELECTEDVALUE(DIM_Calendar[FY Year]) & " " & SELECTEDVALUE(DIM_Calendar[Month])
			```
		displayFolder: Dynamic Text
		lineageTag: 9116890d-44db-484e-bf8c-4e627f967ec0

	measure 'SGAOverview ComparisonTarget' =
			
			VAR PeriodDate = SELECTEDVALUE(DIM_Calendar[FY Year]) & " " & SELECTEDVALUE(DIM_Calendar[Month])
			RETURN
			IF(ISBLANK(PeriodDate), "No period selected", PeriodDate & " ")
		displayFolder: Dynamic Text
		lineageTag: c47b73eb-6eb0-4a8a-aa7a-9f6e5fe44ca1

	measure 'Previous Month Display' = ```
			
			VAR SelectedYearMonth = SELECTEDVALUE(DIM_Calendar[FY Year Month], "Jan 2020")
			VAR CleanYearMonth = LEFT(SelectedYearMonth, LEN(SelectedYearMonth) - 2)
			VAR DateValue = DATEVALUE(CleanYearMonth)
			VAR PreviousMonthDate = EDATE(DateValue, -1)
			RETURN
			FORMAT(PreviousMonthDate, "MMM YYYY")
			
			```
		displayFolder: Dynamic Text
		lineageTag: ef4e1d82-ad6a-4902-8076-9b437dc0bce5

	measure 'SGAOverview PreviousMonth' =
			
			VAR SelectedMonth = SELECTEDVALUE(DIM_Calendar[Year Month])
			VAR FirstDayOfSelectedMonth = DATE(YEAR(SelectedMonth), MONTH(SelectedMonth), 1)
			VAR FirstDayOfPreviousMonth = EDATE(FirstDayOfSelectedMonth, -1)
			VAR FYFirstDayOfPreviousMonth = LOOKUPVALUE(DIM_Calendar[FY Year Month], DIM_Calendar[Year Month],FirstDayOfPreviousMonth)
			RETURN SELECTEDVALUE(DIM_Calendar[FY Year]) & " " & FORMAT(FYFirstDayOfPreviousMonth, "Mmm")
		displayFolder: Dynamic Text
		lineageTag: 2703048e-074d-4bed-a770-771287efe650

	measure 'SGABreakdown Selector' = ```
			
			    "Actual Spending vs " &
			    SELECTEDVALUE('Selector Table - Scenario'[Alias])
			    & " - "
			    & SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			```
		displayFolder: Dynamic Text
		lineageTag: f6c1f198-7c39-4f00-b848-35722aaadb72

	measure SalesMinus_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [SalesMinus_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		displayFolder: Sales\Sales Minus
		lineageTag: dffa1d95-d476-4bce-bac3-d79fbfa14b4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus_ActualvsPrevYear_Selector = ([SalesMinus_Selector_Actual] / [SalesMinus_PrevYearActual_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales\Sales Minus
		lineageTag: 463fe383-3144-4987-be81-483be1129386

	measure SalesMinus_FC_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [SalesMinus_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		displayFolder: Sales\Sales Minus
		lineageTag: d2f6cd96-4b46-45de-ae48-cfc16cc3ff43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus_ActualvsFC_Selector = ([SalesMinus_Selector_Actual] / [SalesMinus_FC_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales Minus
		lineageTag: 2f38ff47-c09a-44c2-9a2d-efaa5209eae3

	measure Sales_Country_Actual_LCY = ```
			
			
			var selectedPC = SELECTEDVALUE(HIER_ProfitCenter[ProfitCenter_L9])
			var selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			var actualScenario = "Actual"
			 
			var result =
			    SWITCH(selectedCountry,
			        "ESD", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "ESD", DIM_Scenario[Scenario] = actualScenario),
			        // "ETH_Total", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "ETH_Total", DIM_Scenario[Scenario] = actualScenario),
			        "ETH", CALCULATE([Sales_Selector], DIM_Country[Country] = "ETH", DIM_Scenario[Scenario] = actualScenario),
			        "EPC", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "EPC", DIM_Scenario[Scenario] = actualScenario),
			        "EMSB", CALCULATE([Sales_Selector], DIM_Country[Country] = "EMSB", DIM_Scenario[Scenario] = actualScenario),
			        "IDC", CALCULATE([Sales_Selector], DIM_Country[Country] = "IDC", DIM_Scenario[Scenario] = actualScenario),
			        "EIN-IDR", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "EIN-IDR", DIM_Scenario[Scenario] = actualScenario),
			        "Others Dir", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Others Dir", DIM_Scenario[Scenario] = actualScenario),
			        "Total EVNL", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Total EVNL", DIM_Scenario[Scenario] = actualScenario),
			        "MD", 
			        IF(
			            OR(selectedPC = "Finance (Local) - FY20", selectedPC = "ED - PH16"),
			            CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", 'DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias] = "MD", DIM_Scenario[Scenario] = actualScenario),
			            0
			        ),     
			        CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = actualScenario)
			    )
			
			return
			    IF(
			        ISBLANK(result),
			        0,
			        ROUND(result, 3)
			    )
			    
			```
		displayFolder: Sales
		lineageTag: 55da4132-896e-4307-b01b-c0cc56433afc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Country_FC_LCY = ```
			
			 
			VAR selectedPC = SELECTEDVALUE(HIER_ProfitCenter[ProfitCenter_L9])
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR result = 
			    SWITCH(selectedCountry,
			        "ESD", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "ESD", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "SGD"),
			        "ETH", CALCULATE([Sales_Selector], DIM_Country[Country] = "ETH", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "THB"),
			        "EPC", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "EPC", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "PHP"),
			        "EMSB", CALCULATE([Sales_Selector], DIM_Country[Country] = "EMSB", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "MYR"),
			        "IDC", CALCULATE([Sales_Selector], DIM_Country[Country] = "IDC", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "IDR"),
			        "EIN-IDR", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "EIN-IDR", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "IDR"),
			        "Others Dir", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Others Dir", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "SGD"),
			        "Total EVNL", CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Total EVNL", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "VND"),
			        "MD", 
			        IF(
			            OR(selectedPC = "Finance (Local) - FY20", selectedPC = "ED - PH16"),
			            CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", 'DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias] = "MD", DIM_Scenario[Scenario] = selectedScenario),
			            0
			        ),     
			        CALCULATE([Sales_Selector], HIER_Country[Country_L1] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = selectedScenario, DIM_Currency[Currency] = "SGD")
			    )
			    
			return
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
			```
		formatString: #,0
		displayFolder: Sales
		lineageTag: 45780664-ed03-46eb-acbd-f5d27eb1e6fb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Sales_Country_LCY_Achievement = ```
			
			    IF(
			        OR([Sales_Country_Actual_LCY] = 0, [Sales_Country_FC_LCY] = 0),
			        0,
			        [Sales_Country_Actual_LCY] / [Sales_Country_FC_LCY]
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: a6934ebb-a9ed-47bf-b5b4-f97c4ec88d92

	measure 1stRebateTRB_Selector_Actual = ```
			
			 // TRB stans for Tactical Rebates Program
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [1stRebateTRB_MTH_Actual],
			        "YTD", [1stRebateTRB_YTD_Actual]
			    )
			```
		displayFolder: Rebates
		lineageTag: 4a2526e3-fee5-44c0-95f1-43db3bf33766

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebateTRB_Selector_Actual =
			
			// TRB stans for Tactical Rebates Program
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [2ndRebateTRB_MTH_Actual],
			        "YTD", [2ndRebateTRB_YTD_Actual]
			    )
		displayFolder: Rebates
		lineageTag: 9e087d40-722f-4d6c-8afb-4333fec6f9a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebateTRB_Selector_FC =
			
			// TRB stans for Tactical Rebates Program
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			RETURN
			    CALCULATE(
			        SWITCH(
			            SelectedType,
			            "Month", [1stRebateTRB_MTH],
			            "YTD", [1stRebateTRB_YTD]
			        ),
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
		displayFolder: Rebates
		lineageTag: 5758b8de-4fb2-456b-8a6a-f2e845791359

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebateTRB_Selector_FC =
			
			// TRB stans for Tactical Rebates Program
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR SelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			RETURN
			    CALCULATE(
			        SWITCH(
			            SelectedType,
			            "Month", [2ndRebateTRB_MTH],
			            "YTD", [2ndRebateTRB_YTD]
			        ),
			        DIM_Scenario[Scenario] = SelectedScenario
			    )
		displayFolder: Rebates
		lineageTag: aff277ec-478f-4fbd-9479-523031f0e6a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tactical_Selection_Actual = ```
			
			VAR selectedTactical = SELECTEDVALUE('Selector Table - Tactical'[Tactical])
			VAR result = 
			        SWITCH(
			            selectedTactical,
			            "Total Tactical", [TotalRebate_Selector_Actual],
			            "1st Tier Tactical", [1stRebateTRB_Selector_Actual],
			            "2nd Tier Tactical", [2ndRebateTRB_Selector_Actual]
			        )
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
			```
		displayFolder: Rebates
		lineageTag: 422e7d22-716f-4081-8ed3-b990e5036d9f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tactical_Selection_FC =
			
			VAR selectedTactical = SELECTEDVALUE('Selector Table - Tactical'[Tactical])
			
			VAR result =
			    SWITCH(
			        selectedTactical,
			        "Total Tactical", [TotalRebate_Selector_FC],
			        "1st Tier Tactical", [1stRebateTRB_Selector_FC],
			        "2nd Tier Tactical", [2ndRebateTRB_Selector_FC]
			    )
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
		displayFolder: Rebates
		lineageTag: 3bdba663-690f-4031-b50a-eea53ed66e86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus%_Selector_PrevYear =
			
			CALCULATE(
			    [SalesMinus%_Selector],
			    DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Sales Minus
		lineageTag: 296ed47a-36aa-4873-9bd5-f64bf5ca53d8

	measure SalesMinus%_ActualvsPrevYr_Selector =
			
			// ([SalesMinus%_Selector_Actual] / [SalesMinus%_Selector_PrevYear])
			[SalesMinus_Selector_Actual] / [SalesMinus_Selector_PrevYear]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales\Sales Minus
		lineageTag: 30ae5e7a-e795-4b7c-93df-59d322ad8b8b

	measure SalesMinus%_ActualvsFC_Selector =
			
			// ([SalesMinus%_Selector_Actual] / [SalesMinus%_Selector_FC])
			[SalesMinus_Selector_Actual] / [SalesMinus_Selector_FC]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales\Sales Minus
		lineageTag: 58279bab-4ae7-48b0-9bc2-8939d17a8b64

	measure Sales_Selector_ActualVSPrevYear = ([Sales_Selector_Actual] / [Sales_PrevYearActual_Selector]) - 1
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: 2eead52e-389d-46b0-bbaf-968bc3bcb537

	measure Sales_HariOverBPD_Selector =
			
			VAR vHari =
			    CALCULATE(
			        [Sales_Selector_Actual],
			        HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_Selector_Actual],
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			
			RETURN vHari / vBPD
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: 41f855c4-aa8e-4dde-9e4b-571823d78d33

	measure Sales_MeriOverBPD_Selector =
			
			VAR vMeri =
			    CALCULATE(
			        [Sales_Selector_Actual],
			        HIER_ProfitCenter[ProfitCenter_L9] = "Meri (BPD) - FY24"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_Selector_Actual],
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			
			RETURN vMeri / vBPD
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: 52cb56c8-1af6-4b07-a4b6-160a35cb20b4

	measure Sales_MeriOverBPD_Selector_PrevYear =
			
			VAR vMeri =
			    CALCULATE(
			        [Sales_PrevYearActual_Selector],
			        HIER_ProfitCenter[ProfitCenter_L9] = "Meri (BPD) - FY24"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_PrevYearActual_Selector],
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			
			RETURN vMeri / vBPD
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: c0de32de-adbf-4dec-9602-2afffaa45ee0

	measure Sales_HariOverBPD_Selector_PrevYear =
			
			VAR vHari =
			    CALCULATE(
			        [Sales_PrevYearActual_Selector],
			        HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24"
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_PrevYearActual_Selector],
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			
			RETURN vHari / vBPD
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales
		lineageTag: ec287c92-6662-4648-9165-a4a514c19822

	measure AccGroup_Detailed_Budget = ```
			
			    CALCULATE(
			        SUM(FACT_FIN_ProfitAndLoss_Detailed[Value]),
			        FACT_FIN_ProfitAndLoss_Detailed[Scenario] = "BP (Final cut)"
			    )
			```
		lineageTag: 39a1ad64-d4b2-48d5-9f32-9482b1610955

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AccGroup_Detailed_Actual = ```
			
			    CALCULATE(
			        SUM(FACT_FIN_ProfitAndLoss_Detailed[Value]),
			        FACT_FIN_ProfitAndLoss_Detailed[Scenario] = "Actual"
			    )
			```
		lineageTag: bec517e2-0a80-4d49-b486-1bf64256f688

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AccGroup_Detailed_Variance = ```
			
			    IF(
			        OR([AccGroup_Detailed_Actual] = 0, [AccGroup_Detailed_Budget] = 0),
			        BLANK(),
			        ([AccGroup_Detailed_Actual] / [AccGroup_Detailed_Budget]) - 1
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: dc375f02-c43a-4380-880b-898bafaf38ed

	measure 1stRebate_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [1stRebate_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: d2f59ede-47cd-4c3b-9ba1-66c84cacc9db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00021",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: 5192d98a-1e0b-4918-936c-397a9c5b2152

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00030",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: 77c94b2a-052c-4df0-8d81-357c74209946

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00040",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: 076f024a-d738-4bba-8a03-35a45885335b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebate_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "A00020",
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20"
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: c0f665bc-b1bf-4654-89c2-0d2f702ff443

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [2ndRebate_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: 32a9b42e-67a8-414d-be0c-cc9be1b8fef9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [Discount_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: 0ca4f607-3d69-4bd9-a8c4-e9fe1ed07811

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [PriceProtection_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Sales Minus Breakdown
		lineageTag: da9ef921-9f87-4861-aea9-21a8bb8ab9d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebate_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [1stRebate_MTH],
			        "YTD", [1stRebate_YTD]
			    )
		displayFolder: Sales Minus Breakdown
		lineageTag: e8fa04d8-dc0d-41f2-b6b5-a4461e5e9be1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [2ndRebate_MTH],
			        "YTD", [2ndRebate_YTD]
			    )
		displayFolder: Sales Minus Breakdown
		lineageTag: 32b85ffb-aba5-4afc-b8ef-2f02e066e231

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Discount_MTH],
			        "YTD", [Discount_YTD]
			    )
		displayFolder: Sales Minus Breakdown
		lineageTag: 62f9b6f1-4e98-41a6-beac-018a54b81d5d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [PriceProtection_MTH],
			        "YTD", [PriceProtection_YTD]
			    )
		displayFolder: Sales Minus Breakdown
		lineageTag: e7c98097-d046-4d70-8b55-1925b386c995

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebate_Selector_Actual =
			
			CALCULATE(
			    [1stRebate_Selector],
			    DIM_Scenario[Scenario] = "Actual"
			)
		displayFolder: Sales Minus Breakdown
		lineageTag: d9ab9107-f440-4689-995e-89f3dc079cb0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate_Selector_Actual =
			
			CALCULATE(
			    [2ndRebate_Selector],
			    DIM_Scenario[Scenario] = "Actual"
			)
		displayFolder: Sales Minus Breakdown
		lineageTag: a4ee4c39-d340-48ab-a968-78d65931dd88

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount_Selector_Actual =
			
			CALCULATE(
			    [Discount_Selector],
			    DIM_Scenario[Scenario] = "Actual"
			)
		displayFolder: Sales Minus Breakdown
		lineageTag: 4db179cd-732c-4962-969e-db71ca5bcb0c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection_Selector_Actual =
			
			CALCULATE(
			    [PriceProtection_Selector],
			    DIM_Scenario[Scenario] = "Actual"
			)
		displayFolder: Sales Minus Breakdown
		lineageTag: dcd810f2-746f-4581-9b7c-42d9b4e64879

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebate_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([1stRebate_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 7dbf05b9-10ea-47d3-8bc5-20dbb6efafc0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([2ndRebate_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 4b3dc83c-5186-4e2e-96b0-4ae92220de87

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([Discount_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 3cb985b9-888c-47de-b27a-113be5447a88

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([PriceProtection_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 55c512a1-139f-4ff8-ad1b-201e18468ba6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebate_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([1stRebate_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: b892e4fa-9c79-4ba6-bcdf-232fbd7ab015

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([2ndRebate_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: fb966c2e-f430-481a-9fdd-914aba1da2be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([Discount_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 1778c644-8916-417f-a14c-9f4f4cf97bfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([PriceProtection_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 1be3471b-1e17-4392-8db2-1f97cd2cd1fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinusBreakdown_LineGraph_Actual =
			
			VAR selectedBreakdown = SELECTEDVALUE('Selector Table - Sales Minus'[Breakdown])
			
			RETURN
			    SWITCH(
			        selectedBreakdown,
			        "Total Sales Minus %", [SalesMinus%_LineGraph_Actual],
			        "1st Tier Rebate %", [1stRebate%_LineGraph_Actual],
			        "2nd Tier Rebate %", [2ndRebate%_LineGraph_Actual],
			        "Discount %", [Discount%_LineGraph_Actual],
			        "Price Protection %", [PriceProtection%_LineGraph_Actual]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales Minus Breakdown
		lineageTag: ca28345b-2414-4ea8-9786-436bf4723e0a

	measure SalesMinusBreakdown_LineGraph_FC =
			
			VAR selectedBreakdown = SELECTEDVALUE('Selector Table - Sales Minus'[Breakdown])
			
			RETURN
			    SWITCH(
			        selectedBreakdown,
			        "Total Sales Minus %", [SalesMinus%_LineGraph_FC],
			        "1st Tier Rebate %", [1stRebate%_LineGraph_FC],
			        "2nd Tier Rebate %", [2ndRebate%_LineGraph_FC],
			        "Discount %", [Discount%_LineGraph_FC],
			        "Price Protection %", [PriceProtection%_LineGraph_FC]
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales Minus Breakdown
		lineageTag: 5c88bcc2-da06-4cd5-864a-ffc649400ba4

	measure ExRate_LineGraph_Actual = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        SUM(FACT_FIN_Exchange_Rate[Value]), 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "Actual"
			    )
			return result
			```
		formatString: 0.0#########;0.0;-0.0#########
		lineageTag: e790c096-7ef4-41b9-a8b5-c411951648ae

		annotation PBI_FormatHint = {"isCustom":true}

	measure ExRate_LineGraph_FC0 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        SUM(FACT_FIN_Exchange_Rate[Value]), 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "FC0"
			    )
			return result
			```
		lineageTag: aeef2ce6-afef-4eca-88b5-484fa4b5a925

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExRate_LineGraph_FC1 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        SUM(FACT_FIN_Exchange_Rate[Value]), 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "FC1 (2nd Cut Final)"
			    )
			return result
			```
		formatString: 0.0#########;0.0;-0.0#########
		lineageTag: 22406c4c-3c97-4297-930f-cb07411dd96f

		annotation PBI_FormatHint = {"isCustom":true}

	measure ExRate_LineGraph_FC2 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        SUM(FACT_FIN_Exchange_Rate[Value]), 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "FC2 (2nd Cut Final)"
			    )
			return result
			```
		formatString: 0.0#########;0.0;-0.0#########
		lineageTag: c4fead44-a234-4128-b5ec-ed5a1fab08ed

		annotation PBI_FormatHint = {"isCustom":true}

	measure ExRate_LineGraph_FC3 = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        SUM(FACT_FIN_Exchange_Rate[Value]), 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "FC3 (2nd Cut Final)"
			    )
			return result
			```
		formatString: 0.0#########;0.0;-0.0#########
		lineageTag: cc11571e-7673-43fd-88cf-30a2b87351a6

		annotation PBI_FormatHint = {"isCustom":true}

	measure ExRate_LineGraph_BP = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        SUM(FACT_FIN_Exchange_Rate[Value]), 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "BP (Final cut)"
			    )
			return result
			```
		formatString: 0.0#########;0.0;-0.0#########
		lineageTag: 543b4385-0a65-482b-9603-b88814e5f6d3

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SalesbyESC HariMeri' = ```
			
			    FORMAT(
			        SELECTEDVALUE(DIM_Calendar[FY Year Month]), "MMM YY")
			```
		displayFolder: Dynamic Text
		lineageTag: 36626c51-f8de-4f04-a0f6-8d79cf2b8b0b

	measure 'SalesMinus Breakdown' = ```
			
			    "Sales Minus - " & 
			    SELECTEDVALUE('Selector Table - Sales Minus'[Breakdown])
			```
		displayFolder: Dynamic Text
		lineageTag: cdb7f93e-c7d8-4e2b-ba57-6ae88ceff91a

	measure 'SalesbyESC HariMeri Arrow' = ```
			
			    IF([SalesMinus_ActualvsPrevYear_Selector] >=0,
			    UNICHAR(129137),
			    UNICHAR(129139))
			```
		displayFolder: Dynamic Text
		lineageTag: 6db546c1-77f5-4d87-856c-96c0a8f39ec7

	measure ExchangeImpact_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [ExchangeImpact_MTH],
			        "YTD", [ExchangeImpact_YTD]
			    )
		formatString: #,##0.00;-#,##0.00
		lineageTag: 03056917-bbe7-463d-bbb4-2fec6e0dacba

		annotation PBI_FormatHint = {"isCustom":true}

	measure Sales_Selector_LineGraph_Actual_HariVSTotalBPD =
			
			VAR vHari = CALCULATE([Sales_Selector_LineGraph_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24")
			VAR vBPD = CALCULATE([Sales_Selector_LineGraph_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20")
			
			RETURN vHari / vBPD
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\LineGraph
		lineageTag: fe6ac780-d3fa-4605-9243-8c9593888885

	measure Sales_Selector_LineGraph_FC_HariVSTotalBPD = ```
			
			Var vRefScenario = SELECTEDVALUE('Selector Table (Hari Target)'[Scenario])
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = year(CurrentDateCY)
			
			VAR StartFYDate = date(CurrentYearFY, 4, 1)
			VAR StartDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], StartFYDate)
			
			// Note: Because our calendar table DAY is 01-Mar-24 instead of EOMONTH date
			VAR EndFYDate = date(CurrentYearFY, 3, 1)
			VAR EndDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], EndFYDate)
			
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			
			var PresentedDate = SELECTEDVALUE('Presentation Calendar'[FY Year Month])
			VAR PresentedDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], PresentedDate)
			var LastPresentedDate = StartYTDDate
			
			var selectedPresMonth = SELECTEDVALUE('Presentation Calendar'[Month])
			var selectedPresMonthNo = LOOKUPVALUE('Presentation Calendar - Month'[Sort], 'Presentation Calendar - Month'[Month], selectedPresMonth)
			
			var selectedMonth = SELECTEDVALUE(DIM_Month[Month])
			var selectedMonthNo = LOOKUPVALUE(DIM_Month[Sort], DIM_Month[Month], selectedMonth)
			
			VAR vHari = CALCULATE([sales_mth], HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24",       
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartDateCY && DIM_Calendar[Year Month] <= EndDateCY
			        ), REMOVEFILTERS(DIM_Scenario[Scenario]),
			        USERELATIONSHIP('Selector Table (Hari Target)'[Scenario], DIM_Scenario[Scenario]))
			        
			VAR vBPD = CALCULATE([Sales_MTH], HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartDateCY && DIM_Calendar[Year Month] <= EndDateCY
			        ), 
			        USERELATIONSHIP('Selector Table (Hari Target)'[Scenario], DIM_Scenario[Scenario]))
			
			RETURN 
			if ( 1 <= selectedPresMonthNo && selectedPresMonthNo <= selectedMonthNo, vHari / vBPD, BLANK())
			// if ( LastPresentedDate <= PresentedDateCY && PresentedDateCY <= CurrentDateCY, vHari / vBPD, BLANK())
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\LineGraph
		lineageTag: 80820bf9-2eca-42e0-bc9d-53cfe4f67cbf

	measure TrafficLight_Scorecard_Sales_troubleshoot =
			
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsPrevYear =
			    IF([Scorecard_Sales_Selector_ActualvsPrevYear] >= 1,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsFC =
			    IF([Scorecard_Sales_Selector_ActualvsFC] >= 1,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return [Scorecard_Sales_Selector_ActualvsPrevYear]
		lineageTag: 10fdfb51-672c-46e8-8fb5-bb0c72091e87

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TrafficLight_ESC_Revenue_ProductGroup = ```
			
			 
			var selectedScenario = "Actual"
			var selectedProductGroup = SELECTEDVALUE('Selector Table - Product Category'[Product Category])
			var actualScenario = "Actual"
			 
			return
			            SWITCH(selectedProductGroup,
			                "CISS", CALCULATE([TrafficLight_PG_Sales], HIER_ProfitCenter[ProfitCenter_L9] = "CISS_FY20"),
			                "SIDM", CALCULATE([TrafficLight_PG_Sales], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "SIDM/PLQ (Local)"),
			                "SP", CALCULATE([TrafficLight_PG_Sales], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Small Printer (Local)"),
			                "Corporate BU", CALCULATE([TrafficLight_PG_Sales], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Corporate BU"),
			                "Printer others", CALCULATE([TrafficLight_PG_Sales_PrinterOthers], DIM_Scenario[Scenario] = actualScenario),
			                "LFP (excl Corp)", CALCULATE([TrafficLight_PG_Sales_LFP], DIM_Scenario[Scenario] = actualScenario),
			                "VI", CALCULATE([TrafficLight_PG_Sales], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "VI - PH16"),
			                "IIJ", CALCULATE([TrafficLight_PG_Sales], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "IIJ"),
			                "RS", CALCULATE([TrafficLight_PG_Sales], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "FA - PH16")
			            )
			```
		displayFolder: Pareto
		lineageTag: 957b5dbc-e221-4002-86d2-a63a405fd2b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_PG_ActualVSPrevYear = ([Sales_Selector_Actual] / [Sales_PrevYearActual_Selector])
		displayFolder: Sales
		lineageTag: 3eb6eef7-d7ec-4829-959f-cf8ae163587b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_PG_ActualVSFC = ([Sales_Selector_Actual] / [Sales_FC_Selector])
		displayFolder: Sales
		lineageTag: 150f2c69-b495-4e06-b67b-afa86402f864

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TrafficLight_PG_Sales =
			
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsPrevYear =
			    IF([Sales_Selector_PG_ActualVSPrevYear] >= 1,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsFC =
			    IF([Sales_Selector_PG_ActualVSFC] >= 1,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return ActualvsPrevYear + ActualvsFC
		formatString: 0
		lineageTag: 7c308ea1-112f-486c-9611-e912ad6c4ee2

	measure Sales_Selector_PGPrinterOthers_ActualVSPrevYear =
			
			VAR cp_local_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "CP (Local) - FY20")
			VAR media_others_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Media Others - PH16")
			VAR liatris_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Liatris (Local) - FY20")
			VAR colour_label_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Colour Label/LW (Local)")
			
			VAR cp_local_prevyear = CALCULATE([Sales_PrevYearActual_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "CP (Local) - FY20")
			VAR media_others_prevyear = CALCULATE([Sales_PrevYearActual_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Media Others - PH16")
			VAR liatris_prevyear = CALCULATE([Sales_PrevYearActual_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Liatris (Local) - FY20")
			VAR colour_label_prevyear = CALCULATE([Sales_PrevYearActual_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Colour Label/LW (Local)")
			
			VAR vActual = cp_local_actual + media_others_actual + liatris_actual + colour_label_actual
			VAR vPrev = cp_local_prevyear + media_others_prevyear + liatris_prevyear + colour_label_prevyear
			
			RETURN vActual / vPrev
		displayFolder: Sales
		lineageTag: 3670e7e3-fa52-451d-b82a-1896b7a0ab19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_PGPrinterOthers_ActualVSFC =
			
			VAR cp_local_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "CP (Local) - FY20")
			VAR media_others_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Media Others - PH16")
			VAR liatris_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Liatris (Local) - FY20")
			VAR colour_label_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Colour Label/LW (Local)")
			
			VAR cp_local_fc = CALCULATE([Sales_FC_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "CP (Local) - FY20")
			VAR media_others_fc = CALCULATE([Sales_FC_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Media Others - PH16")
			VAR liatris_fc = CALCULATE([Sales_FC_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Liatris (Local) - FY20")
			VAR colour_label_fc = CALCULATE([Sales_FC_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Colour Label/LW (Local)")
			
			VAR vActual = cp_local_actual + media_others_actual + liatris_actual + colour_label_actual
			VAR vFC = cp_local_fc + media_others_fc + liatris_fc + colour_label_fc
			
			RETURN vActual / vFC
		displayFolder: Sales
		lineageTag: 69ba7a4a-b2f5-4e9e-a39e-4b516a7f2482

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TrafficLight_PG_Sales_PrinterOthers =
			
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsPrevYear =
			    IF([Sales_Selector_PGPrinterOthers_ActualVSPrevYear] >= 1,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsFC =
			    IF([Sales_Selector_PGPrinterOthers_ActualVSFC] >= 1,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return ActualvsPrevYear + ActualvsFC
		formatString: 0
		lineageTag: 921fc3c8-eb3c-4fe8-8a45-ba5cb994cbd5

	measure Sales_Selector_PGLFP_ActualVSFC =
			
			VAR lfp_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "LFP (Local) - FY20")
			VAR corp_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Corporate (Local) - FY20")
			
			VAR lfp_fc = CALCULATE([Sales_FC_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "LFP (Local) - FY20")
			VAR corp_fc = CALCULATE([Sales_FC_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Corporate (Local) - FY20")
			
			VAR vActual = lfp_actual - corp_actual
			VAR vFC = lfp_fc - corp_fc
			
			RETURN vActual / vFC
		displayFolder: Sales
		lineageTag: dbe07863-3645-46ac-aed9-512e41458323

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_PGLFP_ActualVSPrevYear =
			
			VAR lfp_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "LFP (Local) - FY20")
			VAR corp_actual = CALCULATE([Sales_Selector_Actual], HIER_ProfitCenter[ProfitCenter_L9] = "Corporate (Local) - FY20")
			
			VAR lfp_prev = CALCULATE([Sales_PrevYearActual_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "LFP (Local) - FY20")
			VAR corp_prev = CALCULATE([Sales_PrevYearActual_Selector], HIER_ProfitCenter[ProfitCenter_L9] = "Corporate (Local) - FY20")
			
			VAR vActual = lfp_actual - corp_actual
			VAR vPrev = lfp_prev - corp_prev
			
			RETURN vActual / vPrev
		displayFolder: Sales
		lineageTag: 9e3a0575-e338-4088-83f4-50c1ec1b496d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TrafficLight_PG_Sales_LFP =
			
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsPrevYear =
			    IF([Sales_Selector_PGLFP_ActualVSPrevYear] >= 1,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsFC =
			    IF([Sales_Selector_PGLFP_ActualVSFC] >= 1,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return ActualvsPrevYear + ActualvsFC
		formatString: 0
		lineageTag: 47cef62d-a079-4f98-be26-81e652fb3847

	measure COGS_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "Cost of Goods Sold"
			    )
			```
		displayFolder: COGS
		lineageTag: e298d9c4-00bd-4021-8ec8-a31def546f50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [COGS_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: COGS
		lineageTag: 5c9c866d-962a-412a-a969-fc0cde78d0d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [COGS_MTH],
			        "YTD", [COGS_YTD]
			    )
		displayFolder: COGS
		lineageTag: 61f52048-7408-4ac1-aa62-d488fe0a573c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS_Selector_Actual = ```
			
			    CALCULATE(
			        [COGS_Selector],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		displayFolder: COGS
		lineageTag: 9e9461fb-77ba-48a0-98ce-004cab13fcd0

	measure GrossProfit_MTH = ```
			
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "DZZZZZ"
			    )
			```
		displayFolder: Gross Profit
		lineageTag: 030ae66b-99bd-4881-9b14-b24fcd4acc07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossProfit_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [GrossProfit_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Gross Profit
		lineageTag: b51acb31-54a3-4f33-a835-f8e26ad59b3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossProfit_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [GrossProfit_MTH],
			        "YTD", [GrossProfit_YTD]
			    )
		displayFolder: Gross Profit
		lineageTag: 3f473e05-3158-4fd2-a508-bf0d18f3348a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossProfit_Selector_Actual = ```
			
			    CALCULATE(
			        [GrossProfit_Selector],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		displayFolder: Gross Profit
		lineageTag: b3b0aaa7-6990-4327-a889-cca02b3a25d1

	measure COGS_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [COGS_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		displayFolder: COGS
		lineageTag: a7603741-760d-4a4b-87ff-c28d3466d111

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossProfit_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [GrossProfit_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		displayFolder: Gross Profit
		lineageTag: b212fd74-0a66-41c7-be7e-1aac232ac809

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossProfit_ActualvsPrevYear_Selector = ([GrossProfit_Selector_Actual] - [GrossProfit_PrevYearActual_Selector]) / [GrossProfit_Selector_Actual]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Gross Profit
		lineageTag: d13a4bb1-a0d6-4843-9f9f-5a46d214f06c

	measure COGS_ActualvsPrevYear_Selector = ([COGS_Selector_Actual] - [COGS_PrevYearActual_Selector]) / [COGS_Selector_Actual]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: COGS
		lineageTag: faa3d8a0-3094-4599-9585-69776d8c11f0

	measure Scorecard_HariRatio_YTD_FC =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR vHari =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Country[Country] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24",
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			
			VAR vBPD =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Country[Country] = selectedCountry,
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20",
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			
			RETURN vHari / vBPD
		displayFolder: 13Mar\Scorecard
		lineageTag: 151f49c3-e86f-42fa-b0ca-c0431d4d1ade

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scorecard_HariRatio_Selector_Actual =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR result =
			    CALCULATE(
			        SWITCH(
			            SelectedType,
			            "Month", CALCULATE([Scorecard_HariRatio_MTH], DIM_Scenario[Scenario] = "Actual"),
			            "YTD", CALCULATE([Scorecard_HariRatio_YTD], DIM_Scenario[Scenario] = "Actual")
			        ),
			        REMOVEFILTERS(HIER_ProfitCenter)
			    )
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: b59c5ccf-67e5-4c83-99b1-c784458c4ad7

		formatStringDefinition = "0.0%;-0.0%;NA"

	measure ScorecardBU_SalesAchievement%_ActualvsPrevYear_Selector = ```
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			 
			RETURN
			    CALCULATE([Sales_Achievement_vsPrevYear_Selector], HIER_ProfitCenter[ProfitCenter_L9] = selectedBU, DIM_Country[Country] = "Finance Consol without EPIL")
			```
		displayFolder: 13Mar\Scorecard
		lineageTag: 92137080-df71-4894-b1b0-7b62938ef1a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TrafficLight_Scorecard_Sales_BU =
			
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsPrevYear =
			    IF([ScorecardBU_SalesAchievement%_ActualvsPrevYear_Selector] >= 1,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsFC =
			    IF([ScorecardBU_SalesAchievement%_Selector] >= 1,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return ActualvsPrevYear + ActualvsFC
		formatString: 0
		lineageTag: 36058dab-451b-45e0-b32c-851ddfabc27d

	measure Sales_Achievement_ActualvsPrevYear_Selector = ([Sales_Achievement_Selector] / [Sales_Achievement_vsPrevYear_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Sales Achievement
		lineageTag: fcac0d09-dbe9-4074-876f-73fd1449c930

	measure ExRate_BarVariance_ActualvsFC0 = ```
			
			    IF(
			        OR([ExRate_LineGraph_Actual] = 0, [ExRate_LineGraph_FC0] = 0),
			        BLANK(),
			        [ExRate_LineGraph_Actual] / [ExRate_LineGraph_FC0]
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 66f9ba97-8ac9-4e1c-9ead-8d4d22375b45

	measure ExRate_BarVariance_ActualvsFC1 = ```
			
			    IF(
			        OR([ExRate_LineGraph_Actual] = 0, [ExRate_LineGraph_FC1] = 0),
			        BLANK(),
			        [ExRate_LineGraph_Actual] / [ExRate_LineGraph_FC1]
			    )
			```
		lineageTag: f591a39f-59d4-46a5-8dae-99cd575d27a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExRate_BarVariance_ActualvsFC2 = ```
			
			    IF(
			        OR([ExRate_LineGraph_Actual] = 0, [ExRate_LineGraph_FC2] = 0),
			        BLANK(),
			        [ExRate_LineGraph_Actual] / [ExRate_LineGraph_FC2]
			    )
			```
		lineageTag: 13832f45-3269-4924-b4e1-00ab685e83a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExRate_BarVariance_ActualvsFC3 = ```
			
			    IF(
			        OR([ExRate_LineGraph_Actual] = 0, [ExRate_LineGraph_FC3] = 0),
			        BLANK(),
			        [ExRate_LineGraph_Actual] / [ExRate_LineGraph_FC3]
			    )
			```
		lineageTag: fc1de5b5-c3fe-48a4-8db7-44ae1fc2a623

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExRate_BarVariance_ActualvsBP = ```
			
			    IF(
			        OR([ExRate_LineGraph_Actual] = 0, [ExRate_LineGraph_BP] = 0),
			        BLANK(),
			        [ExRate_LineGraph_Actual] / [ExRate_LineGraph_BP]
			    )
			```
		lineageTag: e2f7ce57-faa4-40c0-9443-9d954753c8dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExRate_BarVariance_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			var selectedPresentationMonth = SELECTEDVALUE('Presentation Calendar - Month'[Month])
			RETURN
			SWITCH(selectedPresentationMonth,
			    "Apr", [ExRate_BarVariance_ActualvsBP],
			    "May", [ExRate_BarVariance_ActualvsBP],
			    "Jun", [ExRate_BarVariance_ActualvsFC1],
			    "Jul", [ExRate_BarVariance_ActualvsFC1],
			    "Aug", [ExRate_BarVariance_ActualvsFC1],
			    "Sep", [ExRate_BarVariance_ActualvsFC2],
			    "Oct", [ExRate_BarVariance_ActualvsFC2],
			    "Nov", [ExRate_BarVariance_ActualvsFC2],
			    "Dec", [ExRate_BarVariance_ActualvsFC3],
			    "Jan", [ExRate_BarVariance_ActualvsFC3],
			    "Feb", [ExRate_BarVariance_ActualvsFC3],
			    "Mar", [ExRate_BarVariance_ActualvsFC3])
			
			    // SWITCH(
			    //     selectedScenario,
			    //     "BP (Final cut)", [ExRate_BarVariance_ActualvsBP],
			    //     "FC0", [ExRate_BarVariance_ActualvsFC0],
			    //     "FC1 (2nd Cut Final)", [ExRate_BarVariance_ActualvsFC1],
			    //     "FC2 (2nd Cut Final)", [ExRate_BarVariance_ActualvsFC2],
			    //     "FC3 (2nd cut Final)", [ExRate_BarVariance_ActualvsFC3]
			    // ))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6eda894c-168a-45e9-b309-7b1948960789

	measure BusinessProfit%_Selector_LineGraph_Actual = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        // [BusinessProfit_Selector_Actual] / [Sales_Selector_Actual], 
			        [ScorecardBP_BusinessProfitDivideSales],
			        KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			    )
			return result
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Business Profit
		lineageTag: e354e630-3de6-47ff-b393-da859204b2a4

	measure BusinessProfit%Target_Upper_Selector_LineGraph_Actual = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [ScorecardBP_TargetBPUpperQuartile_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Business Profit
		lineageTag: 678a1f82-8328-4a3a-a8e4-300bd4aef7f7

	measure BusinessProfit%Target_Upper = CALCULATE(sum(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]))
		displayFolder: Business Profit
		lineageTag: 1a174eb7-5841-438c-9826-799a0be288c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit%Target_Lower = CALCULATE(sum(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]))
		displayFolder: Business Profit
		lineageTag: 5a1df309-2c5f-49a6-9254-a3635405e86d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit%Target_Lower_Selector_LineGraph_Actual = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [ScorecardBP_TargetBPLowerQuartile_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 
			        'Presentation Calendar'[Year Month])
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Business Profit
		lineageTag: ccdd4e9e-a9ce-4e66-9ef5-643c4e532aec

	measure SGA_Spending_Overspend =
			
			
			// VAR vDiff = [SgaAccount_Selector_Actual] - [SgaAccount_FC_Selector]
			
			// // Divide EIN and EVNL by 1mil
			// VAR vDiffMil =
			// SWITCH(
			//     SELECTEDVALUE('DIM_Country - Alias & Ordering'[Country]),
			//     "EIN-IDR", vDiff / 1000000,
			//     "Total EVNL", vDiff / 1000000,
			//     vDiff
			// )
			
			// RETURN
			//     IF(
			//         vDiffMil >= 0,
			//         vDiffMil,
			//         BLANK()
			//     )
			
			VAR vDiff = [SgaAccount_Selector_Actual] - [SgaAccount_FC_Selector]
			
			RETURN
			    IF(
			        vDiff >= 0,
			        vDiff,
			        BLANK()
			    )
		displayFolder: SGA
		lineageTag: 9419d098-73e2-4ae7-8486-b293e92f2838

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Spending_Underspend =
			
			// VAR vDiff = [SgaAccount_Selector_Actual] - [SgaAccount_FC_Selector]
			
			// // Divide EIN and EVNL by 1mil
			// VAR vDiffMil =
			// SWITCH(
			//     SELECTEDVALUE('DIM_Country - Alias & Ordering'[Country]),
			//     "EIN-IDR", vDiff / 1000000,
			//     "Total EVNL", vDiff / 1000000,
			//     vDiff
			// )
			
			// RETURN
			//     IF(
			//         vDiffMil < 0,
			//         ABS(vDiffMil),
			//         BLANK()
			//     )
			
			VAR vDiff = [SgaAccount_Selector_Actual] - [SgaAccount_FC_Selector]
			
			RETURN
			    IF(
			        vDiff < 0,
			        ABS(vDiff),
			        BLANK()
			    )
		displayFolder: SGA
		lineageTag: 30e05774-1a21-45ec-a290-e74f8b6a80f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_SpendBarChart_Overspend% = ```
			
			VAR selectedSgaAccount = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    SWITCH(
			        selectedSgaAccount,
			        "A&P", [TotalA&P_Overspend] / CALCULATE([TotalA&P_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "AS", [ASCost_Overspend] / CALCULATE([ASCost_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "Logistics", [TotalLogistics_Overspend] / CALCULATE([TotalLogistics_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "Salaries", [Salaries_Overspend] / CALCULATE([Salaries_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "Others", [SGAOthers_Overspend] / CALCULATE([SGAOthers_Selector], DIM_Scenario[Scenario] = selectedScenario)      
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA
		lineageTag: d3a9c618-bdb6-46fa-96e3-7e2573558827

	measure SGA_SpendBarChart_Underspend% = ```
			
			VAR selectedSgaAccount = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    SWITCH(
			        selectedSgaAccount,
			        "A&P", [TotalA&P_Underspend] / CALCULATE([TotalA&P_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "AS", [ASCost_Underspend] / CALCULATE([ASCost_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "Logistics", [TotalLogistics_Underspend] / CALCULATE([TotalLogistics_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "Salaries", [Salaries_Underspend] / CALCULATE([Salaries_Selector], DIM_Scenario[Scenario] = selectedScenario),
			        "Others", [SGAOthers_Underspend] / CALCULATE([SGAOthers_Selector], DIM_Scenario[Scenario] = selectedScenario) 
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA
		lineageTag: bdeda794-23f0-4152-bab2-5a9f7fb420cd

	measure TotalLogistics_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalLogistics_MTH],
			        "YTD", [TotalLogistics_YTD]
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 2b36a496-b8c3-4421-80b0-b04ee5630d7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [ASCost_MTH],
			        "YTD", [ASCost_YTD]
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 107b748d-77eb-424e-835f-67c4a9d7b0da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Salaries_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [Salaries_MTH],
			        "YTD", [Salaries_YTD]
			    )
		displayFolder: SGA\SGA Position
		lineageTag: acbe8f57-a68b-4796-a4c3-c3750680bc26

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGAOthers_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [SGAOthers_MTH],
			        "YTD", [SGAOthers_YTD]
			    )
		displayFolder: SGA\SGA Position
		lineageTag: bd311fa7-4974-4807-9676-4e93d4a4517d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_Overspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([TotalA&P_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([TotalA&P_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff >= 0,
			        vDiff,
			        BLANK()
			    )
		displayFolder: SGA
		lineageTag: 18959c64-f6b8-45e6-9c4e-05d2297d907d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_Overspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([ASCost_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([ASCost_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff >= 0,
			        vDiff,
			        BLANK()
			    )
		displayFolder: SGA
		lineageTag: 19dfe07d-1b8f-42ae-becf-3ed95d25d9c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Salaries_Overspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([Salaries_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([Salaries_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff >= 0,
			        vDiff,
			        BLANK()
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 6b389c21-111a-4a9e-bff5-c89db82ab682

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGAOthers_Overspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([SGAOthers_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([SGAOthers_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff >= 0,
			        vDiff,
			        BLANK()
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 2a6f33f5-48f8-4639-8709-e35d236b01d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_Underspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([TotalA&P_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([TotalA&P_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff < 0,
			        ABS(vDiff),
			        BLANK()
			    )
		displayFolder: SGA
		lineageTag: f6067770-1714-4384-a6db-3f91cfb0e620

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_Underspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([TotalLogistics_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([TotalLogistics_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff < 0,
			        ABS(vDiff),
			        BLANK()
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 97a0598e-69b4-4492-850a-079501839b8c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASCost_Underspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([ASCost_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([ASCost_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff < 0,
			        ABS(vDiff),
			        BLANK()
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 1f73437b-e917-4d43-8b6d-a7e17315d86e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Salaries_Underspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([Salaries_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([Salaries_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff < 0,
			        ABS(vDiff),
			        BLANK()
			    )
		displayFolder: SGA\SGA Position
		lineageTag: a99403a7-af1a-4d93-a48e-2bcb4dbbe628

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGAOthers_Underspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([SGAOthers_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([SGAOthers_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff < 0,
			        ABS(vDiff),
			        BLANK()
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 217db2e5-4155-48fb-848a-9df6ca92d02c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_Overspend =
			
			VAR selectedFC = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR vActual = CALCULATE([TotalLogistics_Selector], DIM_Scenario[Scenario] = "Actual")
			VAR vFC = CALCULATE([TotalLogistics_Selector], DIM_Scenario[Scenario] = selectedFC)
			
			VAR vDiff = vActual - vFC
			
			RETURN
			    IF(
			        vDiff >= 0,
			        vDiff,
			        BLANK()
			    )
		displayFolder: SGA\SGA Position
		lineageTag: 8d53178e-d6c8-4085-8c20-2fa6c4fc65a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Spending_Actual =
			
			// // This measure will subtract from Actual value when Overspend occurs. Formula will be Actual - Overspend to obtain Actual spending, otherwise the Overspend will be double counted.
			
			// VAR result = [SgaAccount_Selector_Actual] - [SGA_Spending_Overspend]
			
			// // Divide EIN and EVNL by 1mil
			// RETURN
			// SWITCH(
			//     SELECTEDVALUE('DIM_Country - Alias & Ordering'[Country]),
			//     "EIN-IDR", result / 1000000,
			//     "Total EVNL", result / 1000000,
			//     result
			// )
			
			// This measure will subtract from Actual value when Overspend occurs. Formula will be Actual - Overspend to obtain Actual spending, otherwise the Overspend will be double counted.
			
			[SgaAccount_Selector_Actual] - [SGA_Spending_Overspend]
		displayFolder: SGA
		lineageTag: fc0206bb-189c-4978-8d12-06069c84d991

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure sga_spend_test =
			
			VAR selectedSgaAccount = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			
			RETURN
			    SWITCH(
			        selectedSgaAccount,
			        "A&P", [TotalA&P_Selector],
			        "AS", [ASCost_Selector],
			        "Logistics", [TotalLogistics_Selector],
			        "Salaries", [Salaries_Selector],
			        "Others", [SGAOthers_Selector]
			    )
		displayFolder: SGA
		lineageTag: 16f9f991-96c7-4560-96ec-3b63426a1484

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_Bullet_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SgaAccount_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = "Actual")
			return result
		displayFolder: SGA Position
		lineageTag: c4ef4c3c-3c82-4091-ace3-cf03d0a81bce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector =
			
			VAR selectedAccount = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			
			RETURN
			    SWITCH(
			        selectedAccount,
			        "Total", [SGA_Selector],
			        "A&P", [TotalA&P_Selector],
			        "AS", [ASCost_Selector],
			        "Logistics", [TotalLogistics_Selector],
			        "Salaries", [Salaries_Selector],
			        "Others", [SGAOthers_Selector]
			    )
		displayFolder: SGA Position
		lineageTag: 9585c4d1-6516-44b4-b666-71d5bb5bdf52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_Target =
			
			VAR selectedTarget = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			
			VAR EndYTDDate = date(year(StartYTDDate), month(StartYTDDate) + 12, 1)
			
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, EndYTDDate)
			
			var result = CALCULATE([SgaAccount_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedTarget)
			return result
		displayFolder: SGA Position
		lineageTag: 20c18a82-146f-425b-a42a-d74e0e746f86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Base = 0
		formatString: 0
		lineageTag: aeb1ec0e-d3bd-40a7-b699-44c95d4cf78d

	measure SgaAccount_Selector_Bullet_Future = ```
			
			VAR selectedTarget = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			Var CurrentMonthCY = month(CurrentDateCY)
			var presentationDate = SELECTEDVALUE('Presentation Calendar'[FY Year Month])
			var presentationDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], presentationDate)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR StartYTDDate_NextFY = date(year(StartYTDDate) + 1, 4, 1)
			VAR StartYTDDate_NextFY_CY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], StartYTDDate_NextFY)
			
			var selectedPresMonth = SELECTEDVALUE('Presentation Calendar'[Month])
			var selectedPresMonthNo = LOOKUPVALUE('Presentation Calendar - Month'[Sort], 'Presentation Calendar - Month'[Month], selectedPresMonth)
			
			var selectedMonth = SELECTEDVALUE(DIM_Month[Month])
			var selectedMonthNo = LOOKUPVALUE(DIM_Month[Sort], DIM_Month[Month], selectedMonth)
			
			VAR Mth_Diff = 12 - DATEDIFF(StartYTDDate,CurrentDateCY,  MONTH) - 1
			 
			var mth_future =
			    CALCULATE(
			        // [TotalA&P_MTH_Target],
			        [SgaAccount_MTH_Target],
			        // KEEPFILTERS(previousDates),
			        // REMOVEFILTERS('DIM_Calendar'[FY Year Month]),
			        ALL('DIM_Calendar'[FY Year Month]),
			        // presentationDateCY > CurrentDateCY && presentationDateCY < StartYTDDate_NextFY_CY,
			        DIM_Calendar[Year Month] > CurrentDateCY && DIM_Calendar[Year Month] < StartYTDDate_NextFY_CY,
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			    )
			 
			var total_actual =
			    // CALCULATE([TotalA&P_MTH_Actual],
			    CALCULATE(
			        [SgaAccount_MTH_Actual],
			        FILTER(all(DIM_Calendar[Year Month]), DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= CurrentDateCY)
			    )
			 
			var total_target =
			    CALCULATE(
			        // [TotalA&P_MTH_Target],
			        [SgaAccount_MTH_Target],
			        FILTER(all(DIM_Calendar[Year Month]), DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= CurrentDateCY)
			    )
			 
			var difference = total_target - total_actual
			 
			var diff_avg = difference / Mth_Diff
			 
			return
			SWITCH(TRUE(), selectedPresMonthNo > selectedMonthNo && selectedPresMonthNo <= 12, mth_future + diff_avg, blank())
			```
		displayFolder: SGA Position
		lineageTag: 67e10b79-0a80-47ac-b288-3932d811636b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_MTH_Actual =
			
			VAR selectedAccount = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			VAR actualScenario = "Actual"
			
			RETURN
			    SWITCH(
			        selectedAccount,
			        "Total", CALCULATE([SGA_MTH], DIM_Scenario[Scenario] = actualScenario),
			        "A&P", CALCULATE([TotalA&P_MTH], DIM_Scenario[Scenario] = actualScenario),
			        "AS", CALCULATE([ASCost_MTH], DIM_Scenario[Scenario] = actualScenario),
			        "Logistics", CALCULATE([TotalLogistics_MTH], DIM_Scenario[Scenario] = actualScenario),
			        "Salaries", CALCULATE([Salaries_MTH], DIM_Scenario[Scenario] = actualScenario),
			        "Others", CALCULATE([SGAOthers_MTH], DIM_Scenario[Scenario] = actualScenario)
			    )
		displayFolder: SGA Position
		lineageTag: d959b043-48de-4362-84e9-e4236ca1a21c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_MTH_Target =
			
			VAR selectedAccount = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			VAR selectedTarget = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    SWITCH(
			        selectedAccount,
			        "Total", CALCULATE([SGA_MTH], DIM_Scenario[Scenario] = selectedTarget),
			        "A&P", CALCULATE([TotalA&P_MTH], DIM_Scenario[Scenario] = selectedTarget),
			        "AS", CALCULATE([ASCost_MTH], DIM_Scenario[Scenario] = selectedTarget),
			        "Logistics", CALCULATE([TotalLogistics_MTH], DIM_Scenario[Scenario] = selectedTarget),
			        "Salaries", CALCULATE([Salaries_MTH], DIM_Scenario[Scenario] = selectedTarget),
			        "Others", CALCULATE([SGAOthers_MTH], DIM_Scenario[Scenario] = selectedTarget)
			    )
		displayFolder: SGA Position
		lineageTag: f75e2308-3ac6-4558-8e9a-5bb18c08a388

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_MTH_Adj = ```
			
			    CALCULATE(
			        SUM(INPUT_SGA_Adjustments[Amount])
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: 3dc44103-0aea-41e5-81f2-2c98ff36fc5b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_Bullet_Adj =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([TotalA&P_MTH_Adj], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = "Actual")
			return result
		displayFolder: SGA Position
		lineageTag: 8a5a5dbe-1390-4950-a152-296317b25f06

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven%_Target_MTH =
			
			VAR slowInven = SUM(FACT_InventoryTarget[Slow Moving Amt])
			VAR avgSales = SUM(FACT_InventoryTarget[Avg 12 Mths])
			
			VAR result = slowInven/avgSales
			
			RETURN IFERROR(result, 0)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1b9b593e-2789-499d-8046-8b3a3818c296

	measure SlowInven%_PrevMTH =
			
			VAR selectedPeriod = SELECTEDVALUE(DIM_Calendar[Year Month])
			VAR prevMonth = EOMONTH(selectedPeriod, -1)
			
			RETURN
			    CALCULATE(
			        [SlowInven%_MTH],
			        DATEADD('DIM_Calendar'[Year Month], -1, MONTH)
			    )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f995363a-8e1f-4aae-a95e-fef06d50e46c

	measure TrafficLight_Inventory = ```
			
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsTarget =
			    IF([SlowInven%_MTH_WithConsol] <= [SlowInven%_Target_MTH_WithConsol],
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsPrevMonth =
			    IF([SlowInven%_MTH_WithConsol] <= [SlowInven%_PrevMTH_WithConsol],
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return 
			    IF(
			        ActualvsTarget = 1,
			        2,
			        IF(
			            ActualvsPrevMonth = 1,
			            1,
			            0
			        )
			    )
			```
		formatString: 0
		lineageTag: 2310d92d-bcff-4a69-b1d8-0df5ed24d488

	measure Sales_HariTarget = ```
			
			Var vRefScenario = SELECTEDVALUE('Selector Table (Hari Target)'[Scenario])
			 
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = year(CurrentDateCY)
			 
			VAR StartFYDate = date(CurrentYearFY, 4, 1)
			VAR StartDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], StartFYDate)
			 
			// Note: Because our calendar table DAY is 01-Mar-24 instead of EOMONTH date
			VAR EndFYDate = date(CurrentYearFY, 3, 1)
			VAR EndDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], EndFYDate)
			
			var selectedCountry = SELECTEDVALUE(HIER_Country[Country_L1])
			 
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			 
			VAR vHari = 
			    CALCULATE(
			        [sales_mth], 
			        HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24",      
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartDateCY && DIM_Calendar[Year Month] <= EndDateCY
			        ), 
			        REMOVEFILTERS(DIM_Scenario[Scenario]),
			        USERELATIONSHIP('Selector Table (Hari Target)'[Scenario], DIM_Scenario[Scenario]), 
			        USERELATIONSHIP(HIER_Country[Country_L1], 'Selector Table - Country'[Country])
			    )
			
			VAR vBPD = 
			    CALCULATE(
			        [Sales_MTH], 
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20",
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartDateCY && DIM_Calendar[Year Month] <= EndDateCY
			        ), 
			        USERELATIONSHIP('Selector Table (Hari Target)'[Scenario], DIM_Scenario[Scenario]), 
			        USERELATIONSHIP(HIER_Country[Country_L1], 'Selector Table - Country'[Country])
			    )
			VAR result = vHari / vBPD
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 25512a8b-e4a0-423c-a099-3a981a9f660a

	measure Scorecard_Inventory_MTH =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    CALCULATE(
			        [SlowInven%_MTH_WithConsol],
			        HIER_Country[Country_L1] = selectedCountry
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13Mar\Scorecard
		lineageTag: 80ec1693-c6c4-492e-9b26-62baa91fab9a

	measure 'OverviewbyPG Sales Achievement Title' = ```
			
			    IF(
			        HASONEVALUE('Selector Table - Scenario'[Scenario]),
			        "Sales Achievement vs " & SELECTEDVALUE('Selector Table - Scenario'[Alias]),
			        "Please select comparison")
			
			```
		displayFolder: Dynamic Text
		lineageTag: 6e7dadd7-3385-4ba0-ac36-54f9b77c63b3

	measure SUM_Value =
			
			VAR selectedCurrency = SELECTEDVALUE('Selector Table - Currency'[Currency])
			
			RETURN
			    IF(
			        selectedCurrency = "SGD",
			        SUM(FACT_Consol[SGD]),
			        SUM(FACT_Consol[LCY])
			    )
		formatString: 0
		lineageTag: 6ec2700c-708a-4ab7-99c7-ec0c2f2ee458

	measure BusinessProfit_MTH_PrevYear =
			
			var F2ZZZZ =
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "F2ZZZZ",
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			
			var C20622 =
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = "C20622",
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			
			return F2ZZZZ + C20622
		displayFolder: Business Profit
		lineageTag: 3851e266-0b2e-4f02-a82c-f4f8742524e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit_YTD_PrevYear = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [BusinessProfit_MTH_PrevYear],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Business Profit
		lineageTag: 27e70259-6bdc-43ea-ab21-69b122b73d19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBP_BusinessProfit_PrevYear_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE([BusinessProfit_YTD_PrevYear], HIER_Country[Country_L1] = "EIN-IDR"),
			        "EMSB", CALCULATE([BusinessProfit_YTD_PrevYear], HIER_Country[Country_L1] = "EMSB"),
			        "EPC", CALCULATE([BusinessProfit_YTD_PrevYear], HIER_Country[Country_L1] = "EPC"),
			        "ETH_Total", CALCULATE([BusinessProfit_YTD_PrevYear], HIER_Country[Country_L1] = "ETH_Total"),
			        "Total EVNL", CALCULATE([BusinessProfit_YTD_PrevYear], HIER_Country[Country_L1] = "Total EVNL"),
			        "ED - PH16", CALCULATE([BusinessProfit_YTD_PrevYear], HIER_Country[Country_L1] = "Finance Consol without EPIL", HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16"),
			        "ESP", CALCULATE([BusinessProfit_YTD_PrevYear], DIM_Country[Country] = "ESP")
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 32a29c5c-49b9-4750-bed0-48a3ec211496

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBP_TargetBP_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EIN"),
			        "EMSB", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EMSB"),
			        "EPC", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EPC"),
			        "ETH_Total", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "ETH"),
			        "Total EVNL", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EVNL"),
			        "MD", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "ESP (MD)"),
			        "ESP", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "ESP (BPD)")
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13Mar\Scorecard
		lineageTag: 7ecd8836-f7a0-448d-a4a0-0e226f7b9ff9

	measure Sales_Selector_LineGraph_Actual_MU = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [Sales_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        // DIM_Country[Country] = "Finance Consol without EPIL",
			        DIM_Scenario[Scenario] = "Actual",
			        DIM_ProfitCenter[MUCons] = "MU"
			    )
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: 25d2927c-16d7-4261-a1fd-d174bc2d2df9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_Actual_Cons = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [Sales_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        // DIM_Country[Country] = "Finance Consol without EPIL",
			        DIM_Scenario[Scenario] = "Actual",
			        DIM_ProfitCenter[MUCons] = "Cons"
			    )
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: 535b0175-dfe9-40a5-aed9-679c2b5da7e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'New Measure'
		lineageTag: b0dab14b-fb41-40ea-8477-3f09eafcdbf2

	measure 'New Measure 1'
		lineageTag: d4d6ae0b-3b06-4550-b750-5b8875ef65ec

	measure 'New Measure 2'
		lineageTag: af626d76-a539-4fdf-80b7-7a84593459cd

	measure TotalLogistics_Selector_LineGraph_EINIDR = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalLogistics_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EIN-IDR"
			    )
			return result
			```
		displayFolder: SGA\SGA Position
		lineageTag: ec3a130a-faf5-47b2-8c6c-a0fbaf34705a

	measure TotalLogistics_Selector_LineGraph_EMSB = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalLogistics_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EMSB"
			    )
			return result
			```
		displayFolder: SGA Position
		lineageTag: 3f76e1b3-7f8e-487d-857c-11cfdc881140

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_Selector_LineGraph_EPC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalLogistics_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EPC"
			    )
			return result
			```
		displayFolder: SGA Position
		lineageTag: d99c734e-a2a2-4eae-8c0f-85c692ca661e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_Selector_LineGraph_ETH = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalLogistics_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        HIER_Country[Country_L1] = "ETH_Total"
			    )
			return result
			```
		lineageTag: d2752248-976a-4737-bb57-ae3ddd5f6a27

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_Selector_LineGraph_ESD = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalLogistics_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "ESD"
			    )
			return result
			```
		lineageTag: 7baf5013-3bea-4966-a9ab-c581b668b3dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_Selector_LineGraph_EVNL = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalLogistics_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EVNL"
			    )
			return result
			```
		lineageTag: b6fcb2fe-3db0-412d-803a-11a22dbbbb89

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalLogistics_Selector_LineGraph_IDC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [TotalLogistics_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "IDC"
			    )
			return result
			```
		lineageTag: 8a224dbd-e95e-4b40-b05b-cf81ad802237

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGABreakdown_LineGraph_Selector =
			
			VAR selectedAccount = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account])
			
			RETURN
			    SWITCH(
			        selectedAccount,
			        "A&P", [TotalA&P_Selector_LineGraph_Countries]
			    )
		lineageTag: 33fae519-a7fe-4dbc-950d-2b88d1a73e4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalA&P_Selector_LineGraph_Countries =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", [TotalA&P_Selector_LineGraph_EINIDR],
			        "EMSB", [TotalA&P_Selector_LineGraph_EMSB],
			        "EPC", [TotalA&P_Selector_LineGraph_EPC],
			        "ESD", [TotalA&P_Selector_LineGraph_ESD],
			        "ETH_Total", [TotalA&P_Selector_LineGraph_ETH],
			        "EVNL", [TotalA&P_Selector_LineGraph_EVNL],
			        "IDC", [TotalA&P_Selector_LineGraph_IDC]
			    )
		lineageTag: 5285b29e-c783-49d1-82ce-f7a0be67058a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SlowInven%_MTH testnum' =
			
			VAR vSlowInven =
			    CALCULATE(
			        SUMX(FACT_Inventory, FACT_Inventory[ACT_EXRATE_SGD] * FACT_Inventory[Value]),
			        NOT FACT_Inventory[SMS] IN {"<30Days", ">=30&<60Days", ">=60Days", ">=90Days", ">=120Days", ">=150Days"},
			        NOT LEFT(FACT_Inventory[ProfitCenter], 3) = "P14",
			        NOT FACT_Inventory[Exclude_SKU_Filter] = "Reporting",
			        ALL(FACT_Inventory[Country])
			    )
			
			VAR vRollingAvgSales =
			    CALCULATE(
			        CALCULATE([SUM_Value], 'Selector Table - Currency'[Currency] = "SGD"),
			        DATESINPERIOD('DIM_Calendar'[Year Month], LASTDATE(DIM_Calendar[Year Month]), -12, MONTH),
			        NOT LEFT(FACT_Consol[ProfitCenter], 3) = "P14",
			        LEN(FACT_Consol[ProfitCenter]) < 7,
			        FACT_Consol[Account] = "AZZZZZ",
			        FACT_Consol[Scenario] = "Actual"
			    )
			
			RETURN vSlowInven
		lineageTag: 3283b17f-d06e-43d7-af4b-ffb9f91d02c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SlowInven%_MTH testdenom' =
			
			VAR vSlowInven =
			    CALCULATE(
			        SUMX(FACT_Inventory, FACT_Inventory[ACT_EXRATE_SGD] * FACT_Inventory[Value]),
			        NOT FACT_Inventory[SMS] IN {"<30Days", ">=30&<60Days", ">=60Days", ">=90Days", ">=120Days", ">=150Days"},
			        NOT LEFT(FACT_Inventory[ProfitCenter], 3) = "P14",
			        NOT FACT_Inventory[Exclude_SKU_Filter] = "Reporting"
			    )
			
			VAR vRollingAvgSales =
			    CALCULATE(
			        CALCULATE([SUM_Value], 'Selector Table - Currency'[Currency] = "SGD"),
			        DATESINPERIOD('DIM_Calendar'[Year Month], LASTDATE(DIM_Calendar[Year Month]), -12, MONTH),
			        NOT LEFT(FACT_Consol[ProfitCenter], 3) = "P14",
			        LEN(FACT_Consol[ProfitCenter]) < 7,
			        FACT_Consol[Account] = "AZZZZZ",
			        FACT_Consol[Scenario] = "Actual",
			        FACT_Consol[Country] = "Finance Consol without EPIL"
			    )
			
			RETURN (vRollingAvgSales/12)
		lineageTag: 437748ff-a2fe-4dd9-9fdf-25533c0f2c16

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGARatio_Selector_LineGraph_CONSOL = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "Finance Consol without EPIL"
			    )
			return result
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 52d541fd-fbd8-4b58-a1a3-d67c535c3770

	measure SgaAccount_Selector_LineGraph =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([SgaAccount_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		lineageTag: 6c7c31fd-22bd-4613-938a-c399708a432b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_EINIDR = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EIN-IDR"
			    )
			return result
			```
		lineageTag: 690fd007-1c28-4191-88be-5991ad8c85d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_EMSB = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EMSB"
			    )
			return result
			```
		lineageTag: b9c899f1-dfea-44db-80f0-b8090cdd4d6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_EPC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "EPC"
			    )
			return result
			```
		lineageTag: d56641d1-2f9c-46e0-956e-c850f64bd414

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_ESD = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "ESD"
			    )
			return result
			```
		lineageTag: 9d181ac6-ee69-4266-98d0-d1cf785a6f67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_ETH = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        HIER_Country[Country_L1] = "ETH_Total"
			    )
			return result
			```
		lineageTag: 1757ffb6-d9ef-48e2-9bea-82b329a498d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_EVNL = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        HIER_Country[Country_L1] = "Total EVNL"
			    )
			return result
			```
		lineageTag: f424f65f-1560-4e7e-a7fe-6ffeeb4fef03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_LineGraph_CONSOL = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "Finance Consol without EPIL"
			    )
			return result
			```
		lineageTag: 0ff10664-a2e9-46c9-a3d5-1716b6bbeea8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SGABreakdown Spending Selector' = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account]) & " Account Spending"
		displayFolder: Dynamic Text
		lineageTag: 5f5d9fd7-02e6-455d-82a8-baacdcd116be

	measure ScorecardBP_BusinessProfitDivideSales_PrevMth =
			
			VAR selectedPeriod = SELECTEDVALUE(DIM_Calendar[Year Month])
			VAR prevMonth = EOMONTH(selectedPeriod, -1)
			
			RETURN
			    CALCULATE(
			        [ScorecardBP_BusinessProfitDivideSales],
			        DATEADD('DIM_Calendar'[Year Month], -1, MONTH)
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13Mar\Scorecard
		lineageTag: 3b1b7efa-431e-46f6-8932-f8ae4bdea32f

	measure 'Scorecard Previous Month Display' =
			
			VAR SelectedYearMonth = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR DateValue = DATEVALUE(SelectedYearMonth)
			VAR PreviousMonthDate = EDATE(DateValue, -1)
			RETURN
			FORMAT(PreviousMonthDate, "MMM 'YY")
		displayFolder: Dynamic Text
		lineageTag: 408bdbe0-a88b-4afd-80e4-a9ba6a41a02b

	measure TrafficLight_Scorecard_BP =
			
			VAR lowerQuartile = [ScorecardBP_TargetBPLowerQuartile_Selector]
			VAR upperQuartile = [ScorecardBP_TargetBPUpperQuartile_Selector]
			VAR actual = [ScorecardBP_BusinessProfitDivideSales]
			
			// Returns -1 if there is no lower/upper quartile range provided from the input sheet
			// Returns 1 if business profit is within interquartile range, 0 otherwise.
			RETURN
			    IF(
			        ISBLANK(lowerQuartile),
			        -1,
			        IF(
			            actual >= lowerQuartile && actual <= upperQuartile,
			            1,
			            0
			        )
			    )
		formatString: 0
		lineageTag: c42861db-0627-47a8-ba7a-dc9483eec6cc

	measure ScorecardBP_TargetBPLowerQuartile_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EIN"),
			        "EMSB", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EMSB"),
			        "EPC", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EPC"),
			        "ETH_Total", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "ETH"),
			        "Total EVNL", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EVNL"),
			        "MD", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "ESP (MD)"),
			        "ESP", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "ESP (BPD)"),
			        "Finance Consol Without EPIL", CALCULATE(MAX(INPUT_BusinessProfitTarget[Lower Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "Consol")
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: 41ea9b9b-495d-41da-be87-811610e0d64d

	measure ScorecardBP_TargetBPUpperQuartile_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EIN"),
			        "EMSB", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EMSB"),
			        "EPC", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EPC"),
			        "Total EVNL", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "EVNL"),
			        "ETH_Total", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "ETH"),
			        "MD", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "ESP (MD)"),
			        "ESP", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "ESP (BPD)"),
			        "Finance Consol Without EPIL", CALCULATE(MAX(INPUT_BusinessProfitTarget[Upper Quartile Target Business Profit %]), INPUT_BusinessProfitTarget[ESCs] = "Consol")
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: b35fef49-29a3-4e0e-a07d-0770e0530de0

	measure BusinessProfit%_Selector_Actual_LCY =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			VAR result =
			    SWITCH(selectedCountry,
			        "MD", CALCULATE([BusinessProfitRatio_Selector], REMOVEFILTERS(HIER_ProfitCenter[ProfitCenter_L9]), HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", HIER_Country[Country_L1] = "ESP", DIM_Scenario[Scenario] = "Actual", 'Selector Table - Currency'[Currency] = "LCY"),
			        "ESD", BLANK(),
			        CALCULATE([BusinessProfitRatio_Selector], REMOVEFILTERS(HIER_ProfitCenter[ProfitCenter_L9]), HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", HIER_Country[Country_L1] = selectedCountry, DIM_Scenario[Scenario] = "Actual", 'Selector Table - Currency'[Currency] = "LCY")
			    )
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13Mar\Scorecard
		lineageTag: 4bab6ab2-9d52-4936-92f6-db2079190feb

	measure SgaAccount_Selector_Actual = CALCULATE([SgaAccount_Selector], DIM_Scenario[Scenario] = "Actual")
		displayFolder: SGA Position
		lineageTag: 26318688-fb54-4d2f-9f3e-83741e862050

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_FC_Selector =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    CALCULATE(
			        [SgaAccount_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
		displayFolder: SGA
		lineageTag: 18be37a8-ba48-46c2-9e1d-d62891c51668

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExRate_LineGraph_MinRange =
			
			VAR tempTable = {[MinExRate_LineGraph_Actual], [MinExRate_LineGraph_BP], [MinExRate_LineGraph_FC1], [MinExRate_LineGraph_FC2], [MinExRate_LineGraph_FC3]}
			VAR minValue = MINX(tempTable, [Value])
			
			RETURN 0.95 * minValue
		formatString: 0.0000000000
		lineageTag: 5db552d9-62b0-42dd-ba43-db5c2aa3e918

	measure MinExRate_LineGraph_FC0 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MIN(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC0"            
			        )
			    )
			RETURN MINX(AllMonths, [Value])
			```
		lineageTag: b17f4309-57e8-4363-988e-e2dab26411b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinExRate_LineGraph_Actual = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MIN(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "Actual"            
			        )
			    )
			RETURN MINX(AllMonths, [Value])
			```
		lineageTag: 97c667a8-dc93-43bb-9611-f9a58f740204

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinExRate_LineGraph_BP = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MIN(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "BP (Final cut)"            
			        )
			    )
			RETURN MINX(AllMonths, [Value])
			```
		lineageTag: cda9b498-0a07-4a45-ab12-ad5dc48b2342

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinExRate_LineGraph_FC1 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MIN(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC1 (2nd Cut Final)"            
			        )
			    )
			RETURN MINX(AllMonths, [Value])
			```
		lineageTag: a60dc574-1639-4258-90b2-5f244db6e32a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinExRate_LineGraph_FC2 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MIN(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC2 (2nd Cut Final)"            
			        )
			    )
			RETURN MINX(AllMonths, [Value])
			```
		lineageTag: 204d0cb8-02f6-45d9-a0f9-e68c00327321

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MinExRate_LineGraph_FC3 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MIN(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC3 (2nd Cut Final)"            
			        )
			    )
			RETURN MINX(AllMonths, [Value])
			```
		lineageTag: 7563bb45-f664-40df-9df1-aefc6ae3155e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SUM_Value_SGA =
			
			VAR selectedCurrency = SELECTEDVALUE('Selector Table - Currency'[Currency])
			
			RETURN
			    IF(
			        selectedCurrency = "SGD",
			        SUM(FACT_Consol_SGA[SGD]),
			        SUM(FACT_Consol_SGA[LCY])
			    )
		lineageTag: 070b3ccc-294d-44cd-9f5d-b65aca07d2f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OverviewByPG Currency' =
			
			VAR selectedCurrency = SELECTEDVALUE('Selector Table - Currency'[Currency])
			
			RETURN CONCATENATE("Revenue by ", selectedCurrency)
		displayFolder: Dynamic Text
		lineageTag: 9e84d5e6-24d2-4a99-ab1e-fe8c790db8e5

	measure 1stRebateDivideGrossSales_Selector = [1stRebate_Selector_Actual] / [GrossSale_Selector_Actual]
		displayFolder: Sales Minus Breakdown
		lineageTag: 537416b5-20b3-44e5-ba07-524c56a5a509

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SalesMinus Tactical' = SELECTEDVALUE('Selector Table - Tactical'[Tactical])
		displayFolder: Dynamic Text
		lineageTag: fe01792d-727b-43d4-9beb-1223fe7eb006

	measure 'SalesMinus Tactical YTD Actual' = "YTD " & SELECTEDVALUE(DIM_Calendar[Month])
		displayFolder: Dynamic Text
		lineageTag: 73aaf500-92ef-49e9-8bb3-1f80fb0a1103

	measure 'SalesMinus Tactical YTD FC' = SELECTEDVALUE('Selector Table - Scenario'[Alias]) & " YTD " & SELECTEDVALUE(DIM_Calendar[Month])
		displayFolder: Dynamic Text
		lineageTag: 55760281-51ff-48b8-9106-c0fc04110a14

	measure SlowInven%_MTH_WithConsol =
			
			SWITCH(
			    SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA General]),
			    "Consol",
			    CALCULATE(
			        [SlowInven%_MTH],
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'),
			        REMOVEFILTERS(FACT_Consol[Country]),
			        FACT_Consol[Country] = "Finance Consol without EPIL"
			    ),
			    [SlowInven%_MTH]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8bcaec77-38db-47b0-b05b-3e5bbf259e16

	measure SlowInven%_PrevMTH_WithConsol =
			
			SWITCH(
			    SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA General]),
			    "Consol",
			    CALCULATE(
			        [SlowInven%_PrevMTH],
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'),
			        REMOVEFILTERS(FACT_Consol[Country]),
			        FACT_Consol[Country] = "Finance Consol without EPIL"
			    ),
			    [SlowInven%_PrevMTH]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2c53a350-f2d4-40b9-ae8b-ec89ad16465a

	measure SlowInven%_Target_MTH_WithConsol =
			
			SWITCH(
			    SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA General]),
			    "Consol",
			    CALCULATE(
			        [SlowInven%_Target_MTH],
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'),
			        REMOVEFILTERS('FACT_InventoryTarget'[ESC])
			    ),
			    [SlowInven%_Target_MTH]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1d153d8d-9898-4744-9651-87ccfb7e8e93

	measure 'Scorecard HariTarget' = "Hari Ratio " & SELECTEDVALUE('Selector Table (Hari Target)'[Alias]) & " (Full Year)"
		displayFolder: Dynamic Text
		lineageTag: f9729e2d-805a-4fea-93da-8f55f0c14c0a

	measure ScorecardBU_SlowInven%_Selector = ```
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			
			RETURN
			    CALCULATE(
			        [SlowInven%_MTH], 
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'), 
			        REMOVEFILTERS(FACT_Consol[Country]),
			        // ALL(FACT_Inventory[Currency]),
			        // REMOVEFILTERS(FACT_Inventory[Currency]),
			        // REMOVEFILTERS(FACT_Inventory[Country]),
			        // ALL(FACT_Inventory[Country]),
			        FACT_Consol[Country] = "Finance Consol without EPIL",
			        // FACT_Inventory[Country] = "EPC",
			        // 'HIER_ProfitCenter (Inventory Target)'[ProfitCenter_L9] = selectedBU
			        // HIER_ProfitCenter[ProfitCenter_L9] = selectedBU,
			        'HIER_ProfitCenter (Inventory)'[BU_id] = selectedBU
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13Mar\Scorecard
		lineageTag: eac0d645-93af-4c47-a577-9b901f796f49

	measure Sales_MTH_WOElim =
			
			var selectedCountry = SELECTEDVALUE(DIM_Country[Country])
			var vAccount = if ( selectedCountry = "Finance Consol without EPIL", "AZZZZZ", "AZZZZZ (without elim)")
			
			return
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = vAccount
			    )
		displayFolder: Sales
		lineageTag: afcd4f7e-7b8e-4ab6-9cf5-2e780e7c9573

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_MTH_Actual_WOElim =
			
			
			var selectedCountry = SELECTEDVALUE(DIM_Country[Country])
			var vAccount = if ( selectedCountry = "Finance Consol without EPIL", "AZZZZZ", "AZZZZZ (without elim)")
			
			return
			    CALCULATE(
			        [SUM_Value],
			        FACT_Consol[Account] = vAccount,
			        DIM_Scenario[Scenario] = "Actual"
			    )
		displayFolder: Sales
		lineageTag: 15d97b3a-611e-4f46-88e3-75765f78fc14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_YTD_Actual_WOElim = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			return 
			    CALCULATE(
			        [Sales_MTH_WOElim],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        ),
			        DIM_Scenario[Scenario] = "Actual"
			    )
			```
		displayFolder: Sales
		lineageTag: 21ba4f4b-fa0e-46b3-991c-b027de4ec54d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_YTD_WOElim = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [Sales_MTH_WOElim],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		displayFolder: Sales
		lineageTag: e3cffd84-f1ca-4030-9347-e303f6dc8ce5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebate%_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([1stRebate_Selector_Actual]/[GrossSale_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 3f405c82-9fee-439b-82a9-d6162dbbc36d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 1stRebate%_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([1stRebate_Selector]/[GrossSale_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 745fe7ec-9ad5-4805-a950-5b50ca52b31e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate%_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([2ndRebate_Selector_Actual]/[GrossSale_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 02259c58-65f7-49e9-98dd-05cc23ce637c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2ndRebate%_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([2ndRebate_Selector]/[GrossSale_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: c0dc27d1-ba4a-4cc5-8b47-07b05bc39855

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount%_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([Discount_Selector_Actual]/[GrossSale_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 2e91c3aa-3736-4054-985d-e09eb7bc18e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Discount%_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([Discount_Selector]/[GrossSale_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: ab8cf0db-beb1-475b-9b7f-2480709d2762

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection%_LineGraph_Actual =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = CALCULATE([PriceProtection_Selector_Actual]/[GrossSale_Selector_Actual], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]))
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 2e441586-de17-4ce9-af21-cab2ccd5018e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PriceProtection%_LineGraph_FC =
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR result = CALCULATE([PriceProtection_Selector]/[GrossSale_Selector], KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), DIM_Scenario[Scenario] = selectedScenario)
			return result
		displayFolder: Sales Minus Breakdown
		lineageTag: 0b91b500-64a8-42f7-8089-70507f65bb9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalSGA_MTH = ```
			
			    CALCULATE(
			        [SUM_Value_SGA]
			    )
			```
		lineageTag: d7f42674-cd51-4e6d-819a-ba75763b2a31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalSGA_YTD = ```
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			 
			return
			    CALCULATE(
			        [TotalSGA_MTH],
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			        )
			    )
			```
		lineageTag: ed53d8b6-d519-4b0d-99f2-cbd384a4d108

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalSGA_Selector =
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			RETURN
			    SWITCH(
			        SelectedType,
			        "Month", [TotalSGA_MTH],
			        "YTD", [TotalSGA_YTD]
			    )
		lineageTag: 6d45e65e-aad4-438e-9ccf-b591a81014b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ESC_Revenue_Waterfall_MinRange =
			
			
			var selectedScenario = SELECTEDVALUE(DIM_Scenario[Scenario])
			var selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			var userSelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR fcValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20")
			VAR actualValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20")
			
			VAR minValue = MIN(fcValue, actualValue)
			
			RETURN 0.75 * minValue
		lineageTag: 82802b06-fdbe-491f-b693-f9d75c6164b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ProductCategory_Revenue_Waterfall_MinRange =
			
			
			var selectedScenario = SELECTEDVALUE(DIM_Scenario[Scenario])
			var selectedProductCategory = SELECTEDVALUE('Selector Table - Product Category'[Product Category])
			var userSelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR fcValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20")
			VAR actualValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20")
			
			VAR minValue = MIN(fcValue, actualValue)
			
			RETURN 0.75 * minValue
		lineageTag: c11b06dd-362b-4565-a1ec-c6ce71e4fb57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OverviewByPG RevenueByESC Bar' =
			
			VAR selectedPG = SELECTEDVALUE('DIM_ProfitCenter - Alias & Ordering'[OverviewByProdGroupSlicer - Alias])
			
			RETURN CONCATENATE("Revenue by ESC - ", selectedPG)
		displayFolder: Dynamic Text
		lineageTag: 9880480a-64f0-4907-b4e0-1ef53b76ff74

	measure 'Scorecard BP YTD %' = ```
			
			    "YTD " &
			    SELECTEDVALUE(DIM_Calendar[FY Year]) & " " & SELECTEDVALUE(DIM_Calendar[Month]) & " (%) "
			```
		displayFolder: Dynamic Text
		lineageTag: bf595a31-0770-4da8-9799-b87cb7ecd682

	measure ExchangeImpact_MTH =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Alias])
			VAR selectedPeriod = SELECTEDVALUE('DIM_Calendar'[FY Year Month])
			
			VAR EMSB_LCY = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "EMSB", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "LCY")
			VAR EPC_LCY = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "EPC", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "LCY")
			VAR EIN_LCY = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "EIN-IDR", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "LCY")
			VAR ETH_LCY = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "ETH", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "LCY")
			VAR IDC_LCY = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "IDC", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "LCY")
			VAR EVNL_LCY = CALCULATE([Sales_MTH_Actual], HIER_Country[Country_L1] = "Total EVNL", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "LCY")
			
			VAR MYR_Rates = CALCULATE(MAX(FACT_FIN_Exchange_Rate[Value]), FACT_FIN_Exchange_Rate[Currency] = "MYR", FACT_FIN_Exchange_Rate[Scenario] = selectedScenario)
			VAR PHP_Rates = CALCULATE(SELECTEDVALUE(FACT_FIN_Exchange_Rate[Value]), FACT_FIN_Exchange_Rate[Currency] = "PHP", FACT_FIN_Exchange_Rate[Scenario] = selectedScenario)
			VAR IDR_Rates = CALCULATE(SELECTEDVALUE(FACT_FIN_Exchange_Rate[Value]), FACT_FIN_Exchange_Rate[Currency] = "IDR", FACT_FIN_Exchange_Rate[Scenario] = selectedScenario)
			VAR THB_Rates = CALCULATE(SELECTEDVALUE(FACT_FIN_Exchange_Rate[Value]), FACT_FIN_Exchange_Rate[Currency] = "THB", FACT_FIN_Exchange_Rate[Scenario] = selectedScenario)
			VAR VND_Rates = CALCULATE(SELECTEDVALUE(FACT_FIN_Exchange_Rate[Value]), FACT_FIN_Exchange_Rate[Currency] = "VND", FACT_FIN_Exchange_Rate[Scenario] = selectedScenario)
			
			Var vEMSB = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "EMSB", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "SGD") - (EMSB_LCY * MYR_Rates)
			var vEPC = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "EPC", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "SGD") - (EPC_LCY * PHP_Rates)
			VAR vEINIDR = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "EIN-IDR", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "SGD") - (EIN_LCY * IDR_Rates)
			VAR vETH = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "ETH", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "SGD") - (ETH_LCY * THB_Rates)
			VAR vIDC = CALCULATE([Sales_MTH_Actual], FACT_Consol[Country] = "IDC", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "SGD") - (IDC_LCY * THB_Rates)
			VAR vEVNL = CALCULATE([Sales_MTH_Actual], HIER_Country[Country_L1] = "Total EVNL", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20", 'Selector Table - Currency'[Currency] = "SGD") - (EVNL_LCY * VND_Rates)
			VAR vTotal = vEMSB + vEPC + vEINIDR + vETH + vIDC + vEVNL
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EMSB", vEMSB,
			        "EPC", vEPC,
			        "EIN-IDR", vEINIDR,
			        "ETH", vETH,
			        "IDC", vIDC,
			        "Total EVNL", vEVNL,
			        "Total", vTotal
			    )
		lineageTag: 47ef2771-7230-49ec-951a-097cbef5ca26

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ExchangeImpact_YTD =
			
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentMonthFY = MONTH(CurrentDateFY)
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR StartYTDDate =
			// If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			// Creates temp table where 1st column is the Year Months in the YTD range, 2nd column is the ExchangeImpact_MTH value for each Year Month
			VAR TempTable = SUMMARIZE(
			    FILTER(
			        ALL(DIM_Calendar),
			        DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			    ),
			    DIM_Calendar[Year Month],
			    "ExchangeImpact_MTH_Value", CALCULATE([ExchangeImpact_MTH])
			)
			
			// Sums up the 2nd column of the temp table
			RETURN
			    SUMX(
			        TempTable,
			        [ExchangeImpact_MTH_Value]
			    )
		lineageTag: f061f472-2f98-4610-a39f-8101bd30c95e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last Refresh Date Text' =
			
			CONCATENATE("Last Refresh: ", FORMAT(SELECTEDVALUE('Last Refresh Date'[Last Refresh Date]), "dd mmm yy h:nn AM/PM"))
		displayFolder: Dynamic Text
		lineageTag: 74d4a602-5bdf-4238-8cd6-5d71d71965fa

	measure Sales_ActualvsFC_Selector_text = "vs Actual: " & FORMAT([Sales_ActualvsFC_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: 441dfe1c-aaf6-46a2-8cd4-1d76fd8d8afb

	measure Sales_ActualvsPrevYear_Selector_text = "vs Actual: " & FORMAT([Sales_ActualvsPrevYear_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: 5803fb92-c8f0-4f4c-aac5-961537bb522f

	measure SGA_ActualvsFC_Selector_text = "vs Actual: " & FORMAT([SGA_ActualvsFC_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: a1025683-398d-4f5d-8610-1a0d10f18f9b

	measure SGA_ActualvsPrevYear_Selector_text = "vs Actual: " & FORMAT([SGA_ActualvsPrevYear_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: 0c0db6d0-2597-414f-a539-f6209d46a2fa

	measure SGA_Ratio_ActualvsFC_Selector_text = ```
			"vs Actual: " & FORMAT([SGA_Ratio_ActualvsFC_Selector], "0.0%")
			
			```
		displayFolder: Sales
		lineageTag: 581c780e-3b50-4f70-a44b-16ce091d5bbe

	measure SGA_Ratio_ActualvsPrevYear_Selector_text = "vs Actual: " & FORMAT([SGA_Ratio_ActualvsPrevYear_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: e0e0e883-7958-4085-bead-5711325388b1

	measure BusinessProfit_ActualvsFC_Selector_text = "vs Actual: " & FORMAT([BusinessProfit_ActualvsFC_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: 68b99d60-768a-448b-8361-95daefc9ebe9

	measure BusinessProfit_ActualvsPrevYear_Selector_text = "vs Actual: " & FORMAT([BusinessProfit_ActualvsPrevYear_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: baed04cf-8d00-4ae0-8647-682ace6dfd68

	measure BusinessProfitRatio_ActualvsFC_Selector_text = "vs Actual: " & FORMAT([BusinessProfitRatio_ActualvsFC_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: 52d29bba-9bf6-40a0-b558-5400a1553ae0

	measure BusinessProfitRatio_ActualvsPrevYear_Selector_text = "vs Actual: " & FORMAT([BusinessProfitRatio_ActualvsPrevYear_Selector], "0.0%")
		displayFolder: Sales
		lineageTag: c354fdf2-6301-48a1-b50d-1ebd28564b3a

	measure TrafficLight_Inventory_Scorecard = ```
			
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR vActual = CALCULATE([SlowInven%_MTH_WithConsol], HIER_Country[Country_L1] = selectedCountry)
			VAR vTarget = CALCULATE([SlowInven%_Target_MTH_WithConsol], HIER_Country[Country_L1] = selectedCountry)
			VAR vPrevMonth = CALCULATE([SlowInven%_PrevMTH_WithConsol], HIER_Country[Country_L1] = selectedCountry)
			// If Actual vs Prev Year >= 100%, var = 1  else var = 0
			VAR ActualvsTarget =
			    IF(vActual <= vTarget,
			        1,
			        0
			    )
			
			// If Actual vs FC >= 100%, var = 1  else var = 0
			VAR ActualvsPrevMonth =
			    IF(vActual <= vPrevMonth,
			        1,
			        0
			    )
			
			// Sum both variables, should result in a value between 0~2. Red=0 | Orange=1 | Green=2
			return 
			    IF(
			        ActualvsTarget = 1,
			        2,
			        IF(
			            ActualvsPrevMonth = 1,
			            1,
			            0
			        )
			    )
			```
		formatString: 0
		lineageTag: 12755ec0-cc78-440f-92dd-c1518a48d93c

	measure Scorecard_SlowInven% =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			VAR result =
			    CALCULATE(
			        SWITCH(
			            selectedCountry,
			            "Finance Consol without EPIL",
			            CALCULATE(
			                [SlowInven%_MTH],
			                REMOVEFILTERS('DIM_Country - Alias & Ordering'),
			                REMOVEFILTERS(FACT_Consol[Country]),
			                FACT_Consol[Country] = "Finance Consol without EPIL"
			            ),
			            CALCULATE(
			                [SlowInven%_MTH],
			                HIER_Country[Country_L1] = selectedCountry
			            )
			        ),
			        REMOVEFILTERS(HIER_ProfitCenter)
			    )
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
		lineageTag: e5b0fc1a-1810-4a4d-80a9-347e42edc705

		formatStringDefinition = "0.0%;-0.0%;NA"

	measure Scorecard_TargetBP_Selector =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EIN"),
			        "EMSB", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EMSB"),
			        "EPC", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EPC"),
			        "ETH_Total", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "ETH"),
			        "Total EVNL", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "EVNL"),
			        "MD", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "ESP (MD)"),
			        "ESP", CALCULATE(MAX(INPUT_BusinessProfitTarget[Target Business Profit]), INPUT_BusinessProfitTarget[ESCs] = "ESP (BPD)")
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 74024195-f5e7-492e-a106-f15eedbb0204

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GrossSale_Selector_Actual_DisplayZero =
			
			VAR result = [GrossSale_Selector_Actual]
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
		displayFolder: Gross Sales
		lineageTag: a0bb2fdf-37bb-444e-8fd6-e7df67561261

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input_Comments_ESC Rev Bridge' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "ESC Revenue Bridge")
		displayFolder: Input_Comments
		lineageTag: bce7f64e-96ff-4adc-8648-ec4487c3a89f

	measure 'Input_Comments_Product Categories Revenue Bridge' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "Product Categories Revenue Bridge")
		displayFolder: Input_Comments
		lineageTag: 8323d1d9-d4e1-4643-8411-6b9df977f0ae

	measure 'Input_Comments_Sales Minus % Over Time' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "Sales Minus % Over Time")
		displayFolder: Input_Comments
		lineageTag: 5d326e46-138d-4c50-bd11-1ea64444fc92

	measure 'Input_Comments_SGA Position' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "SGA Position")
		displayFolder: Input_Comments
		lineageTag: fb10d91b-85aa-4df8-9650-c4efad819675

	measure 'Input_Comments_SGA Ratio Analysis' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "SGA Ratio Analysis")
		displayFolder: Input_Comments
		lineageTag: daba99bb-1055-4a16-9f4c-373f155e4669

	measure 'Input_Comments_BPD Slow Moving Inventory' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "BPD Slow Moving Inventory")
		displayFolder: Input_Comments
		lineageTag: 9f0734d3-0052-4c9d-a301-78f34fc2274d

	measure 'Input_Comments_Inventory Analysis' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "Inventory Analysis")
		displayFolder: Input_Comments
		lineageTag: fad6978a-15db-495f-998e-271cc756bff6

	measure 'Input_Comments_BU Analysis' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "BU Analysis")
		displayFolder: Input_Comments
		lineageTag: 5bc5b5e4-f6b0-499d-a1d4-cd4d5e2f504a

	measure SgaAccount_Ratio_Selector_Actual = DIVIDE([SgaAccount_Selector_Actual], [Sales_Selector_Actual])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA Position
		lineageTag: ce4e4eec-a0be-4700-be6a-b8cc5313abf2

	measure SgaAccount_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [SgaAccount_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		displayFolder: SGA
		lineageTag: 48e44634-8b47-4481-b702-ce7aad55e307

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_ActualvsPrevYear_Selector = ([SgaAccount_Selector_Actual] / [SgaAccount_PrevYearActual_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA
		lineageTag: ba7b2338-bede-4bb5-a56a-4941cd10781b

	measure Measure
		displayFolder: SGA Ratio
		lineageTag: 1717ba19-ee5d-477a-a434-add11c2a36d8

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure SgaAccount_Ratio_Selector = DIVIDE([SgaAccount_Selector], [Sales_Selector])
		displayFolder: SGA Position
		lineageTag: ecb83249-a55f-41ad-8105-95bf0aa682c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Ratio_PrevYearActual_Selector = ```
			
			    CALCULATE(
			        [SgaAccount_Ratio_Selector],
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			    )
			```
		displayFolder: SGA Position
		lineageTag: e68d5d00-10e6-4756-b1fa-3d932d8b4067

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Ratio_ActualvsPrevYear_Selector = ([SgaAccount_Ratio_Selector_Actual] / [SgaAccount_Ratio_PrevYearActual_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA Ratio
		lineageTag: 6ef5efc7-e220-44b4-8f6e-c7ae3c46ce94

	measure 'SGABreakdown Trend Selector' = SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account]) & " Account % Trend"
		displayFolder: Dynamic Text
		lineageTag: bbf942d7-e79d-48b6-bf0c-831a50eebd32

	measure ScorecardBP_BusinessProfit_Selector_FC =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE([BusinessProfit_YTD], HIER_Country[Country_L1] = "EIN-IDR", DIM_Scenario[Scenario] = selectedScenario),
			        "EMSB", CALCULATE([BusinessProfit_YTD], HIER_Country[Country_L1] = "EMSB", DIM_Scenario[Scenario] = selectedScenario),
			        "EPC", CALCULATE([BusinessProfit_YTD], HIER_Country[Country_L1] = "EPC", DIM_Scenario[Scenario] = selectedScenario),
			        "ETH_Total", CALCULATE([BusinessProfit_YTD], HIER_Country[Country_L1] = "ETH_Total", DIM_Scenario[Scenario] = selectedScenario),
			        "Total EVNL", CALCULATE([BusinessProfit_YTD], HIER_Country[Country_L1] = "Total EVNL", DIM_Scenario[Scenario] = selectedScenario),
			        "MD", CALCULATE([BusinessProfit_YTD], DIM_Country[Country] = "ESP", HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", DIM_Scenario[Scenario] = selectedScenario),
			        "ESP", CALCULATE([BusinessProfit_YTD], DIM_Country[Country] = "ESP", DIM_Scenario[Scenario] = selectedScenario)
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 60b063a2-ab02-4f43-a83e-70325fba5f35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBP_Sales_Selector_FC =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE([Sales_YTD_WOElim], HIER_Country[Country_L1] = "EIN-IDR", DIM_Scenario[Scenario] = selectedScenario),
			        "EMSB", CALCULATE([Sales_YTD_WOElim], HIER_Country[Country_L1] = "EMSB", DIM_Scenario[Scenario] = selectedScenario),
			        "EPC", CALCULATE([Sales_YTD_WOElim], HIER_Country[Country_L1] = "EPC", DIM_Scenario[Scenario] = selectedScenario),
			        "ETH_Total", CALCULATE([Sales_YTD_WOElim], HIER_Country[Country_L1] = "ETH_Total", DIM_Scenario[Scenario] = selectedScenario),
			        "Total EVNL", CALCULATE([Sales_YTD_WOElim], HIER_Country[Country_L1] = "Total EVNL", DIM_Scenario[Scenario] = selectedScenario),
			        "MD", CALCULATE([Sales_YTD_WOElim], HIER_Country[Country_L1] = "Finance Consol without EPIL", HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16", DIM_Scenario[Scenario] = selectedScenario),
			        "ESP", CALCULATE([Sales_YTD_WOElim], DIM_Country[Country] = "ESP", DIM_Scenario[Scenario] = selectedScenario)
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 380a31e0-9fc4-4071-9ec6-9b7e03b226bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ScorecardBP_BusinessProfitDivideSales_FC = [ScorecardBP_BusinessProfit_Selector_FC] / [ScorecardBP_Sales_Selector_FC]
		displayFolder: 13Mar\Scorecard
		lineageTag: 0d31bd83-df89-4bc8-8b65-5975ec80483e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfit%_Selector_LineGraph_FC = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [ScorecardBP_BusinessProfitDivideSales_FC],
			        KEEPFILTERS(previousDates), REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			    )
			return result
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Business Profit
		lineageTag: 3833d147-c5f9-482b-9fe8-ad06d3e55f0c

	measure SGARatio_Selector_LineGraph_ESP = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Ratio_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "ESP"
			    )
			return result
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 978575cb-ede1-46a8-bedf-5360720d2447

	measure SgaAccount_Selector_LineGraph_ESP = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [SgaAccount_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			        DIM_Country[Country] = "ESP"
			    )
			return result
			```
		lineageTag: f3b81dbb-c63b-4dc6-95da-07bb23701d00

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Input_Comments_Total Tactical Analysis' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "Total Tactical Analysis")
		displayFolder: Input_Comments
		lineageTag: f0d267a0-ecff-4571-a39e-5c8a8c71e122

	measure 'Input_Comments_BPD AS Cost Position' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "BPD AS Cost Position")
		displayFolder: Input_Comments
		lineageTag: aa915f96-353f-48a4-b841-f8389079ae8c

	measure 'Input_Comments_Total Company Scorecard Significant Matters to Highlight' = CALCULATE(max(FACT_Comments[Comments]),FACT_Comments[Visual] = "Total Company Scorecard Significant Matters to Highlight")
		displayFolder: Input_Comments
		lineageTag: d22481e2-59cd-4af2-8ea5-a12d1fe704f8

	measure ScorecardBP_Comment =
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			RETURN
			    SWITCH(
			        selectedCountry,
			        "EIN-IDR", CALCULATE(SELECTEDVALUE(FACT_Comments_ESC[Comment]), FACT_Comments_ESC[ESC] = "EIN"),
			        "EMSB", CALCULATE(SELECTEDVALUE(FACT_Comments_ESC[Comment]), FACT_Comments_ESC[ESC] = "EMSB"),
			        "EPC", CALCULATE(SELECTEDVALUE(FACT_Comments_ESC[Comment]), FACT_Comments_ESC[ESC] = "EPC"),
			        "ETH_Total", CALCULATE(SELECTEDVALUE(FACT_Comments_ESC[Comment]), FACT_Comments_ESC[ESC] = "ETH"),
			        "Total EVNL", CALCULATE(SELECTEDVALUE(FACT_Comments_ESC[Comment]), FACT_Comments_ESC[ESC] = "EVNL"),
			        "MD", CALCULATE(SELECTEDVALUE(FACT_Comments_ESC[Comment]), FACT_Comments_ESC[ESC] = "ESP (MD)"),
			        "ESP", CALCULATE(SELECTEDVALUE(FACT_Comments_ESC[Comment]), FACT_Comments_ESC[ESC] = "ESP (BPD)")
			    )
		displayFolder: 13Mar\Scorecard
		lineageTag: 7b512006-80d0-46fd-987e-69ef1ad7c290

	measure Scorecard_HariTarget =
			
			CALCULATE(
			    [Sales_HariTarget],
			    REMOVEFILTERS(HIER_ProfitCenter)
			)
		displayFolder: 13Mar\Scorecard
		lineageTag: f98c93b3-cce1-48df-84eb-a85e2855db26

		formatStringDefinition = "0.0%;-0.0%;NA"

	measure Scorecard_BusinessProfit =
			
			CALCULATE(
			    [BusinessProfit%_Selector_Actual_LCY],
			    REMOVEFILTERS(HIER_ProfitCenter)
			)
		displayFolder: 13Mar\Scorecard
		lineageTag: 71f48ede-952f-4c5e-8734-65b1595048c8

		formatStringDefinition = "0.0%;-0.0%;NA"

	measure TrafficLightArrow_SalesByESC =
			
			IF(
			    [Sales_Selector_ActualVSPrevYear] >= 0,
			    UNICHAR(9650),
			    UNICHAR(9660)
			)
		lineageTag: ab6c42e3-8f1f-4840-a298-87d573d61fbb

	measure TrafficLight_Scorecard_BP_TotalCompany =
			
			VAR lowerQuartile = [ScorecardBP_TargetBPLowerQuartile_Selector]
			VAR upperQuartile = [ScorecardBP_TargetBPUpperQuartile_Selector]
			VAR actual = [Scorecard_BusinessProfit]
			
			// Returns -1 if there is no lower/upper quartile range provided from the input sheet
			// Returns 1 if business profit is within interquartile range, 0 otherwise.
			RETURN
			    IF(
			        ISBLANK(lowerQuartile),
			        -1,
			        IF(
			            actual >= lowerQuartile && actual <= upperQuartile,
			            1,
			            0
			        )
			    )
		formatString: 0
		lineageTag: 1c189621-2d36-4190-b29e-07dbd7e3979e

	measure ScorecardBU_SlowInven%_Target = ```
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			
			RETURN
			    CALCULATE(
			        [SlowInven%_Target_MTH],
			        // REMOVEFILTERS('DIM_Country - Alias & Ordering'), 
			        // REMOVEFILTERS(FACT_Consol[Country]),
			        // ALL(FACT_Inventory[Currency]),
			        // REMOVEFILTERS(FACT_Inventory[Currency]),
			        // REMOVEFILTERS(FACT_Inventory[Country]),
			        // ALL(FACT_Inventory[Country]),
			        // FACT_Consol[Country] = "Finance Consol without EPIL",
			        // FACT_Inventory[Country] = "EPC",
			        'HIER_ProfitCenter (Inventory Target)'[ProfitCenter_L9] = selectedBU
			        // HIER_ProfitCenter[ProfitCenter_L9] = selectedBU
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 13Mar\Scorecard
		lineageTag: 2fc84b29-53ce-4008-b9fe-3c95b4715b5c

	measure ScorecardBU_SlowInven%_PrevMth = ```
			
			VAR selectedBU = SELECTEDVALUE('Selector Table - BU'[BU_id])
			
			RETURN
			    CALCULATE(
			        [SlowInven%_PrevMTH], 
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'), 
			        REMOVEFILTERS(FACT_Consol[Country]),
			        // ALL(FACT_Inventory[Currency]),
			        // REMOVEFILTERS(FACT_Inventory[Currency]),
			        // REMOVEFILTERS(FACT_Inventory[Country]),
			        // ALL(FACT_Inventory[Country]),
			        FACT_Consol[Country] = "Finance Consol without EPIL",
			        // FACT_Inventory[Country] = "EPC",
			        // 'HIER_ProfitCenter (Inventory Target)'[ProfitCenter_L9] = selectedBU
			        // HIER_ProfitCenter[ProfitCenter_L9] = selectedBU,
			        'HIER_ProfitCenter (Inventory)'[BU_id] = selectedBU
			    )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 13Mar\Scorecard
		lineageTag: adadec2d-6ba0-49ef-be94-0a87d8d49eda

	measure ScorecardBU_SlowInven%_TrafficLight = ```
			
			IF(
			    [ScorecardBU_SlowInven%_Selector] <= [ScorecardBU_SlowInven%_Target], 
			    2,
			    IF(
			        [ScorecardBU_SlowInven%_Selector] <= [ScorecardBU_SlowInven%_PrevMth],
			        1,
			        0
			    )
			)    
			```
		formatString: 0
		displayFolder: 13Mar\Scorecard
		lineageTag: 88a4b0c8-d3e9-43c9-98d6-887735dfae6a

	measure SalesMinus_Selector_PrevYear = ```
			
			VAR SelectedType = SELECTEDVALUE('SelectorTable'[Selector], "Month")
			VAR result = 
			CALCULATE(
			    SWITCH(SelectedType, "Month", [SalesMinus_MTH], "YTD", [SalesMinus_YTD]),
			    DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr"
			)
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
			    
			```
		displayFolder: Sales\Sales Minus
		lineageTag: aea62416-a098-46a7-b9b2-d3cd38753fbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_ActualvsFC_Selector = ([SgaAccount_Selector_Actual] / [SgaAccount_FC_Selector])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA
		lineageTag: 05c4fd87-e27a-4ab7-b44b-ee1c45d7c9ff

	measure SgaAccount_Ratio_Selector_FC = DIVIDE([SgaAccount_FC_Selector], [Sales_FC_Selector])
		displayFolder: SGA Position
		lineageTag: 937b4c13-2cf1-4aee-b629-33402474fb70

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Ratio_ActualvsFC_Selector = ([SgaAccount_Ratio_Selector_Actual] / [SgaAccount_Ratio_Selector_FC])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA Ratio
		lineageTag: 092b54c0-0e74-42f8-a67b-b86f3a59ac44

	measure TrafficLightArrow_Hari =
			
			IF(
			    [Sales_Selector_ActualVSPrevYear] >= 0,
			    UNICHAR(9650),
			    UNICHAR(9660)
			)
		lineageTag: a7c4dfa1-d843-4cc8-831d-d03d4ea46941

	measure Sales_HariTarget_Scorecard = ```
			
			Var vRefScenario = SELECTEDVALUE('Selector Table (Hari Target)'[Scenario])
			 
			VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentYearFY = YEAR(CurrentDateFY)
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR CurrentYearCY = year(CurrentDateCY)
			 
			VAR StartFYDate = date(CurrentYearFY, 4, 1)
			VAR StartDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], StartFYDate)
			 
			// Note: Because our calendar table DAY is 01-Mar-24 instead of EOMONTH date
			VAR EndFYDate = date(CurrentYearFY, 3, 1)
			VAR EndDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], EndFYDate)
			
			var selectedCountry = SELECTEDVALUE(HIER_Country[Country_L1])
			 
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			 
			VAR vHari = 
			    CALCULATE(
			        [sales_mth], 
			        HIER_ProfitCenter[ProfitCenter_L9] = "Hari (BPD) - FY24",      
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartDateCY && DIM_Calendar[Year Month] <= EndDateCY
			        ), 
			        REMOVEFILTERS(DIM_Scenario[Scenario]),
			        USERELATIONSHIP('Selector Table (Hari Target)'[Scenario], DIM_Scenario[Scenario]), 
			        USERELATIONSHIP(HIER_Country[Country_L1], 'Selector Table - Country'[Country])
			    )
			
			VAR vBPD = 
			    CALCULATE(
			        [Sales_MTH], 
			        HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20",
			        FILTER(
			            ALL(DIM_Calendar[Year Month]),
			            DIM_Calendar[Year Month] >= StartDateCY && DIM_Calendar[Year Month] <= EndDateCY
			        ), 
			        USERELATIONSHIP('Selector Table (Hari Target)'[Scenario], DIM_Scenario[Scenario]), 
			        USERELATIONSHIP(HIER_Country[Country_L1], 'Selector Table - Country'[Country])
			    )
			VAR result = vHari / vBPD
			
			RETURN
			    IF(
			        ISBLANK(result),
			        0,
			        result
			    )
			```
		lineageTag: bcba9bb0-e648-4dc5-92b2-f092999961a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_FC =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			RETURN CALCULATE([SgaAccount_Selector], DIM_Scenario[Scenario] = selectedScenario)
		displayFolder: SGA Position
		lineageTag: 49731be0-84e6-4bf3-826e-ba1acaecfa40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_VarianceValue = ([SgaAccount_Selector_Actual] - [SgaAccount_Selector_FC])
		displayFolder: SGA\SGA Position
		lineageTag: 2968e73e-31a2-4008-a2c2-486b0f351517

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Selector_VariancePercent = [SgaAccount_Selector_Actual] / [SgaAccount_Selector_FC]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 14f7fe62-f51b-4b40-b8a2-2d4dd29ce83f

	measure SgaAccount_DivideSales_Actual =
			
			VAR SgaAccount =
			    CALCULATE(
			        [SgaAccount_Selector],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR Sales =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			RETURN SgaAccount / Sales
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 59822811-d624-4bde-bae6-037631ed0f9c

	measure SgaAccount_DivideSales_FC =
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			VAR SgaAccount =
			    CALCULATE(
			        [SgaAccount_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			
			VAR Sales =
			    CALCULATE(
			        [Sales_YTD],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			
			RETURN SgaAccount / Sales
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 0ab4813c-a7c7-42ea-9e6c-ef4f86106db8

	measure SgaAccount_DivideSales_ActualMinusFC = ([SgaAccount_DivideSales_Actual] - [SgaAccount_DivideSales_FC])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: d23fadfd-737e-44e5-9e5e-b8afe2872979

	measure SgaAccount_Country_YTD_Actual = ```
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			VAR esp_value = CALCULATE([SgaAccount_Selector_Actual], DIM_Country[Country] = "ESP")
			VAR esd_value = CALCULATE([SgaAccount_Selector_Actual], DIM_Country[Country] = "ESD")
			VAR espEVNL_value = CALCULATE([SgaAccount_Selector_Actual], DIM_Country[Country] = "ESP-EVNL")
			VAR ETH_value = CALCULATE([SgaAccount_Selector_Actual], DIM_Country[Country] = "ETH")
			VAR IDC_value = CALCULATE([SgaAccount_Selector_Actual], DIM_Country[Country] = "IDC")
			VAR MD_value = CALCULATE([SgaAccount_Selector_Actual], REMOVEFILTERS(HIER_ProfitCenter), DIM_Country[Country] = "Finance Consol without EPIL", HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16")
			
			RETURN    
			    SWITCH(
			        selectedCountry,
			        "RHQ", (esp_value - esd_value - espEVNL_value),
			        "ETH_Total", (ETH_value + IDC_value),
			        "Total EVNL", CALCULATE([SgaAccount_Selector_Actual], HIER_Country[Country_L1] = selectedCountry),
			        "MD", MD_value,
			        CALCULATE([SgaAccount_Selector_Actual], DIM_Country[Country] = selectedCountry)
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: a51cc96c-7a45-43cc-b26e-d4cc3eb3ab84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Country_YTD_FC = ```
			
			VAR selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			
			VAR esp_value = CALCULATE([SgaAccount_Selector_FC], DIM_Country[Country] = "ESP")
			VAR esd_value = CALCULATE([SgaAccount_Selector_FC], DIM_Country[Country] = "ESD")
			VAR espEVNL_value = CALCULATE([SgaAccount_Selector_FC], DIM_Country[Country] = "ESP-EVNL")
			VAR ETH_value = CALCULATE([SgaAccount_Selector_FC], DIM_Country[Country] = "ETH")
			VAR IDC_value = CALCULATE([SgaAccount_Selector_FC], DIM_Country[Country] = "IDC")
			VAR MD_value = CALCULATE([SgaAccount_Selector_FC], REMOVEFILTERS(HIER_ProfitCenter), DIM_Country[Country] = "Finance Consol without EPIL", HIER_ProfitCenter[ProfitCenter_L9] = "ED - PH16")
			
			RETURN    
			    SWITCH(
			        selectedCountry,
			        "RHQ", (esp_value - esd_value - espEVNL_value),
			        "ETH_Total", (ETH_value + IDC_value),
			        "Total EVNL", CALCULATE([SgaAccount_Selector_FC], HIER_Country[Country_L1] = selectedCountry),
			        "MD", MD_value,
			        CALCULATE([SgaAccount_Selector_FC], DIM_Country[Country] = selectedCountry)
			    )
			```
		displayFolder: SGA\SGA Position
		lineageTag: f4c8ce96-9490-49d1-9841-08f7d20da3d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Country_YTD_ActualMinusFC = [SgaAccount_Country_YTD_Actual] - [SgaAccount_Country_YTD_FC]
		displayFolder: SGA\SGA Position
		lineageTag: d44961ce-9090-4edf-a2f1-e06f7d783f07

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Country_YTD_ActualDivideFC = [SgaAccount_Country_YTD_Actual] / [SgaAccount_Country_YTD_FC]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: SGA\SGA Position
		lineageTag: 54439d3c-7e2a-4e6b-a46a-18c8571849e4

	measure 'SGABreakdown BPD SGA Table' = ```
			
			    "BPD " &
			    SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account]) & 
			    " Position" &
			    " (" & SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA Overview&Breakdown Slicer]) & ")"
			```
		displayFolder: Dynamic Text
		lineageTag: 0d2f5636-f4a0-4d1c-9728-020dadb3475b

	measure 'SGABreakdown BPD SGA Table %' = ```
			
			    SELECTEDVALUE('Selector Table - SGA Acc'[SGA Account]) & " %"
			```
		displayFolder: Dynamic Text
		lineageTag: 8cc68f7b-730c-4ca0-a96e-98511dff0917

	measure ExRate_LineGraph_MaxRange =
			
			VAR tempTable = {[MaxExRate_LineGraph_Actual], [MaxExRate_LineGraph_BP], [MaxExRate_LineGraph_FC1], [MaxExRate_LineGraph_FC2], [MaxExRate_LineGraph_FC3]}
			VAR maxValue = MAXX(tempTable, [Value])
			
			RETURN 1.02 * maxValue
		formatString: 0.0000000000
		lineageTag: f991ad4d-a9e1-4b04-a10f-34c4ae11f134

	measure MaxExRate_LineGraph_FC0 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MAX(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC0"            
			        )
			    )
			RETURN MAXX(AllMonths, [Value])
			```
		formatString: 0.0000000000
		lineageTag: 20286f4c-b3ad-4a28-803d-07e18122e853

	measure MaxExRate_LineGraph_Actual = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MAX(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "Actual"            
			        )
			    )
			RETURN MAXX(AllMonths, [Value])
			```
		formatString: 0.0000000000
		lineageTag: acc822f3-52c4-4f68-84a4-29514d5a63f0

	measure MaxExRate_LineGraph_BP = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MAX(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "BP (Final cut)"            
			        )
			    )
			RETURN MAXX(AllMonths, [Value])
			```
		formatString: 0.0000000000
		lineageTag: 7e6a18aa-1188-42e9-8c60-e234e671e8c6

	measure MaxExRate_LineGraph_FC1 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MAX(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC1 (2nd Cut Final)"            
			        )
			    )
			RETURN MAXX(AllMonths, [Value])
			```
		formatString: 0.0000000000
		lineageTag: e945b669-24f7-4ffd-a672-7946a75e51ab

	measure MaxExRate_LineGraph_FC2 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MAX(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC2 (2nd Cut Final)"            
			        )
			    )
			RETURN MAXX(AllMonths, [Value])
			```
		formatString: 0.0000000000
		lineageTag: ea0cf468-068f-49ae-bf98-253c141d488e

	measure MaxExRate_LineGraph_FC3 = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			VAR AllMonths = 
			    SUMMARIZE(
			        'DIM_Calendar',
			        DIM_Calendar[FY Year Month],
			        "Value", 
			        CALCULATE(
			            MAX(FACT_FIN_Exchange_Rate[Value]), 
			            KEEPFILTERS(PreviousDates), 
			            REMOVEFILTERS('DIM_Calendar'), 
			            USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			            DIM_Scenario[Scenario] = "FC3 (2nd Cut Final)"            
			        )
			    )
			RETURN MAXX(AllMonths, [Value])
			```
		formatString: 0.0000000000
		lineageTag: 6a670485-d070-4fc8-b1ed-12ce554858b8

	measure Sales_Selector_LineGraph_PrevYear_MU = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [Sales_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr",
			        DIM_ProfitCenter[MUCons] = "MU"
			    )
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: 15b9ff0d-b8cd-42b0-b433-ba4deff2e783

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_PrevYear_Cons = ```
			
			Var ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = year(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			     IF(
			         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			         DATE(CurrentYearCY - 1, 4, 1),
			         DATE(CurrentYearCY, 4, 1)
			     )
			var previousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			var result = 
			    CALCULATE(
			        [Sales_Selector], 
			        KEEPFILTERS(previousDates), 
			        REMOVEFILTERS('DIM_Calendar'), 
			        USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]), 
			        DIM_Scenario[Scenario] = "FIN_Actual_Last_Yr",
			        DIM_ProfitCenter[MUCons] = "Cons"
			    )
			return result
			```
		displayFolder: Sales\LineGraph
		lineageTag: af498b5b-7cd3-4883-aebf-0816e52cc945

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_MINRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMIN = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMIN = MINX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMIN = MINX(PrevYearActual, [Value])
			
			VAR MINValue = MIN(ActualMIN, MIN(ForecastMIN, PrevYearActualMIN))
			
			VAR scaleFactor = 0.5
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: d614e4d7-c0d3-4b18-9c5e-dee582a9e574

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_MAXRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMAX = MAXX(PrevYearActual, [Value])
			
			VAR MAXValue = MAX(ActualMAX, MAX(ForecastMAX, PrevYearActualMAX))
			
			
			VAR scaleFactor = 1.2
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: e5e11981-ba95-4482-9171-8a84438a12db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Selector_LineGraph_MAXRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMAX = MAXX(PrevYearActual, [Value])
			
			VAR MAXValue = MAX(ActualMAX, MAX(ForecastMAX, PrevYearActualMAX))
			
			VAR scaleFactor = 1.2
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: c67bcc6a-2973-4e8a-82f8-3b2f93bba827

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Selector_LineGraph_MINRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMIN = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMIN = MINX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMIN = MINX(PrevYearActual, [Value])
			
			VAR MINValue = MIN(ActualMIN, MIN(ForecastMIN, PrevYearActualMIN))
			
			VAR scaleFactor = 0.5
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: cdb6dc8a-fb8f-42c6-984c-317b530c8b0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGA_Ratio_Selector_LineGraph_MINRange = ```
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Ratio_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMIN = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Ratio_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMIN = MINX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Ratio_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMIN = MINX(PrevYearActual, [Value])
			
			VAR MINValue = MIN(ActualMIN, MIN(ForecastMIN, PrevYearActualMIN))
			
			VAR scaleFactor = 0.5
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 670d5288-408a-4073-935c-193347be0a18

	measure SGA_Ratio_Selector_LineGraph_MAXRange = ```
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Ratio_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Ratio_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SGA_Ratio_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMAX = MAXX(PrevYearActual, [Value])
			
			VAR MAXValue = MAX(ActualMAX, MAX(ForecastMAX, PrevYearActualMAX))
			
			VAR scaleFactor = 1.2
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 0f6ddf16-ba92-479e-8c79-e81c97df0939

	measure BusinessProfit_Selector_LineGraph_MAXRange = ```
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfit_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfit_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfit_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMAX = MAXX(PrevYearActual, [Value])
			
			VAR MAXValue = MAX(ActualMAX, MAX(ForecastMAX, PrevYearActualMAX))
			
			VAR scaleFactor = 1.2
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: f2bf2a36-ecf8-467a-8e26-179f653f021b

	measure BusinessProfit_Selector_LineGraph_MINRange = ```
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfit_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMIN = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfit_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMIN = MINX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfit_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMIN = MINX(PrevYearActual, [Value])
			
			VAR MINValue = MIN(ActualMIN, MIN(ForecastMIN, PrevYearActualMIN))
			
			VAR scaleFactor = 0.5
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: aa83bcc2-992b-465e-8625-77f86347d363

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BusinessProfitRatio_Selector_LineGraph_MINRange = ```
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfitRatio_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMIN = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfitRatio_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMIN = MINX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfitRatio_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMIN = MINX(PrevYearActual, [Value])
			
			VAR MINValue = MIN(ActualMIN, MIN(ForecastMIN, PrevYearActualMIN))
			
			VAR scaleFactor = 0.5
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 418913c9-d7fb-4b2f-ad7b-fcfa9131c882

	measure BusinessProfitRatio_Selector_LineGraph_MAXRange = ```
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfitRatio_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfitRatio_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [BusinessProfitRatio_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMAX = MAXX(PrevYearActual, [Value])
			
			VAR MAXValue = MAX(ActualMAX, MAX(ForecastMAX, PrevYearActualMAX))
			
			VAR scaleFactor = 1.2
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 5742d05b-2909-4829-addc-0d1ba3598841

	measure Sales_Selector_LineGraph_Actual_HariVSTotalBPD_MAXRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_Actual_HariVSTotalBPD]
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_FC_HariVSTotalBPD]
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR MAXValue = MAX(ActualMAX, ForecastMAX)
			
			VAR scaleFactor = 1.3
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\LineGraph
		lineageTag: 0b5718b5-74b5-4d60-8b5d-9a26bd720489

	measure Sales_Selector_LineGraph_Actual_HariVSTotalBPD_MINRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_Actual_HariVSTotalBPD]
			            )
			        )
			    )
			VAR ActualMIN = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_FC_HariVSTotalBPD]
			            )
			        )
			    )
			VAR ForecastMIN = MINX(Forecast, [Value])
			
			VAR MINValue = MIN(ActualMIN, ForecastMIN)
			
			VAR scaleFactor = 0.7
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\LineGraph
		lineageTag: fd0e873b-4922-42dd-8cad-2e4c89a947c0

	measure Sales_Selector_ActualVSPrevYear_AbsoluteFormat =
			([Sales_Selector_Actual] / [Sales_PrevYearActual_Selector]) - 1
			
			// This measure is formatted to be "0.0%;0.0%" so that it does not show negative symbol when it is negative.
		formatString: 0.0%;0.0%
		displayFolder: Sales
		lineageTag: bea557bc-c830-44d3-afec-1b6a3f1e0e9d

		annotation PBI_FormatHint = {"isCustom":true}

	measure SGARatio_Parameter_Selector_LineGraph_MIN =
			
			VAR MinMaxString = [SGARatio_Parameter_Selector_LineGraph_AllValues]
			VAR SeparatorPosition = SEARCH("|", MinMaxString, 1, LEN(MinMaxString))
			VAR MinValue = VALUE(LEFT(MinMaxString, SeparatorPosition - 1))
			
			// RETURN MinValue
			RETURN IFERROR(VALUE(LEFT(MinMaxString, SeparatorPosition - 1)), BLANK())
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 59244182-14e8-4f67-bcde-55390bde6352

	measure SGARatio_Parameter_Selector_LineGraph_MAXRange =
			
			VAR maxValue = [SGARatio_Parameter_Selector_LineGraph_MAX]
			VAR minValue = [SGARatio_Parameter_Selector_LineGraph_MIN]
			
			VAR avgValue = (maxValue + minValue) / 2
			VAR extraRange = (maxValue - avgValue)
			VAR result = maxValue + (1 * extraRange)
			
			RETURN result
		lineageTag: eed29932-84c8-421e-958a-59ec44f46181

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Parameter_Selector_LineGraph_MAX = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Consol = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_CONSOL]
			            )
			        )
			    )
			VAR ConsolMAX = MAXX(Consol, [Value])
			
			VAR EINIDR = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EINIDR]
			            )
			        )
			    )
			VAR EINIDRMAX = MAXX(EINIDR, [Value])
			
			VAR EMSB = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EMSB]
			            )
			        )
			    )
			VAR EMSBMAX = MAXX(EMSB, [Value])
			
			VAR EPC = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EPC]
			            )
			        )
			    )
			VAR EPCMAX = MAXX(EPC, [Value])
			
			VAR ESD = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_ESD]
			            )
			        )
			    )
			VAR ESDMAX = MAXX(ESD, [Value])
			
			VAR ESP = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_ESP]
			            )
			        )
			    )
			VAR ESPMAX = MAXX(ESP, [Value])
			
			VAR ETHTotal = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_ETH]
			            )
			        )
			    )
			VAR ETHTotalMAX = MAXX(ETHTotal, [Value])
			
			VAR EVNL = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EVNL]
			            )
			        )
			    )
			VAR EVNLMAX = MAXX(EVNL, [Value])
			
			
			VAR MAXValue = MAXX(
			    {
			        (ConsolMAX),
			        (EINIDRMAX),
			        (EMSBMAX),
			        (EPCMAX),
			        (ESDMAX),
			        (ESPMAX),
			        (ETHTotalMAX),
			        (EVNLMAX)
			    },
			    [Value]
			)
			
			// VAR scaleFactor = 1.2
			// RETURN
			//     IF(
			//         MAXValue < 0, 
			//         MAXValue * (2-scaleFactor), 
			//         MAXValue * scaleFactor
			//     )
			
			RETURN MAXValue
			```
		lineageTag: bb5b64cc-9d98-4f39-85de-322f31bbe999

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Parameter_Selector_LineGraph_MIN = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Consol = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_CONSOL]
			            )
			        )
			    )
			VAR ConsolMIN = MINX(Consol, [Value])
			
			VAR EINIDR = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EINIDR]
			            )
			        )
			    )
			VAR EINIDRMIN = MINX(EINIDR, [Value])
			
			VAR EMSB = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EMSB]
			            )
			        )
			    )
			VAR EMSBMIN = MINX(EMSB, [Value])
			
			VAR EPC = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EPC]
			            )
			        )
			    )
			VAR EPCMIN = MINX(EPC, [Value])
			
			VAR ESD = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_ESD]
			            )
			        )
			    )
			VAR ESDMIN = MINX(ESD, [Value])
			
			VAR ESP = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_ESP]
			            )
			        )
			    )
			VAR ESPMIN = MINX(ESP, [Value])
			
			VAR ETHTotal = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_ETH]
			            )
			        )
			    )
			VAR ETHTotalMIN = MINX(ETHTotal, [Value])
			
			VAR EVNL = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SgaAccount_Selector_LineGraph_EVNL]
			            )
			        )
			    )
			VAR EVNLMIN = MINX(EVNL, [Value])
			
			
			VAR MINValue = MINX(
			    {
			        (ConsolMIN),
			        (EINIDRMIN),
			        (EMSBMIN),
			        (EPCMIN),
			        (ESDMIN),
			        (ESPMIN),
			        (ETHTotalMIN),
			        (EVNLMIN)
			    },
			    [Value]
			)
			
			RETURN MINValue
			```
		lineageTag: 51d758c5-8427-4856-bd32-62185c9cfbd6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Parameter_Selector_LineGraph_AVG = ([SgaAccount_Parameter_Selector_LineGraph_MAX] + [SgaAccount_Parameter_Selector_LineGraph_MIN]) / 2
		lineageTag: f17dbfa8-49bd-4895-be04-09e9133300e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Parameter_Selector_LineGraph_MINRange =
			
			VAR extraRange = ([SgaAccount_Parameter_Selector_LineGraph_AVG] - [SgaAccount_Parameter_Selector_LineGraph_MIN])
			VAR result = 0.5 * ([SgaAccount_Parameter_Selector_LineGraph_MIN] - extraRange)
			// VAR result = [SgaAccount_Parameter_Selector_LineGraph_MIN] - (0.5 * [SgaAccount_Parameter_Selector_LineGraph_AVG] - [SgaAccount_Parameter_Selector_LineGraph_MIN])
			RETURN result
			
			// RETURN
			//     CALCULATE(
			//         result,
			//         ALLSELECTED('Presentation Calendar - Month'[Month])
			//     )
			
			// VAR CurrentDateFY = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			// VAR CurrentMonthFY = MONTH(CurrentDateFY)
			// VAR CurrentYearFY = YEAR(CurrentDateFY)
			// VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], CurrentDateFY)
			// VAR CurrentMonthCY = MONTH(CurrentDateCY)
			// VAR CurrentYearCY = YEAR(CurrentDateCY)
			// VAR StartYTDDate =
			// // If current month is Jan/Feb/Mar, need to subtract 1 year from Calendar Year date.
			//      IF(
			//          CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			//          DATE(CurrentYearCY - 1, 4, 1),
			//          DATE(CurrentYearCY, 4, 1)
			//      )
			// VAR EndDate = EOMONTH(DATEVALUE(CurrentDateCY), 0)
			
			// // Creates temp table where 1st column is the Year Months in the YTD range, 2nd column is the ExchangeImpact_MTH value for each Year Month
			// VAR TempTable = SUMMARIZE(
			//     FILTER(
			//         ALL(DIM_Calendar),
			//         DIM_Calendar[Year Month] >= StartYTDDate && DIM_Calendar[Year Month] <= EndDate
			//     ),
			//     DIM_Calendar[Year Month],
			//     "MTH_Value", CALCULATE([SgaAccount_Parameter_Selector_LineGraph_AVG] - [SgaAccount_Parameter_Selector_LineGraph_MIN])
			// )
			
			// // Sums up the 2nd column of the temp table
			// RETURN
			//     SUMX(
			//         TempTable,
			//         [MTH_Value]
			//     )
		lineageTag: 0abc32a9-6b08-4545-bcc2-6e67d999e3cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SgaAccount_Parameter_Selector_LineGraph_MAXRange = ```
			
			VAR extraRange = ([SgaAccount_Parameter_Selector_LineGraph_MAX] - [SgaAccount_Parameter_Selector_LineGraph_AVG])
			// VAR result = 0.5 * ([SgaAccount_Parameter_Selector_LineGraph_MAX] + extraRange)
			VAR result = [SgaAccount_Parameter_Selector_LineGraph_MAX] + (0.5 * extraRange)
			RETURN result
			
			// VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			// VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			// VAR CurrentYearCY = YEAR(CurrentDateCY)
			// VAR CurrentMonthCY = MONTH(CurrentDateCY)
			// VAR StartYTDDate =
			//     IF(
			//         CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			//         DATE(CurrentYearCY - 1, 4, 1),
			//         DATE(CurrentYearCY, 4, 1)
			//     )
			// VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			// VAR Consol = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_CONSOL]
			//             )
			//         )
			//     )
			// VAR ConsolMAX = MAXX(Consol, [Value])
			
			// VAR EINIDR = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_EINIDR]
			//             )
			//         )
			//     )
			// VAR EINIDRMAX = MAXX(EINIDR, [Value])
			
			// VAR EMSB = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_EMSB]
			//             )
			//         )
			//     )
			// VAR EMSBMAX = MAXX(EMSB, [Value])
			
			// VAR EPC = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_EPC]
			//             )
			//         )
			//     )
			// VAR EPCMAX = MAXX(EPC, [Value])
			
			// VAR ESD = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_ESD]
			//             )
			//         )
			//     )
			// VAR ESDMAX = MAXX(ESD, [Value])
			
			// VAR ESP = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_ESP]
			//             )
			//         )
			//     )
			// VAR ESPMAX = MAXX(ESP, [Value])
			
			// VAR ETHTotal = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_ETH]
			//             )
			//         )
			//     )
			// VAR ETHTotalMAX = MAXX(ETHTotal, [Value])
			
			// VAR EVNL = 
			//     CALCULATETABLE(
			//         ADDCOLUMNS(
			//             SUMMARIZE(
			//                 'Presentation Calendar',
			//                 'Presentation Calendar'[Year Month]
			//             ),
			//             "Value", CALCULATE(
			//                 [SgaAccount_Selector_LineGraph_EVNL]
			//             )
			//         )
			//     )
			// VAR EVNLMAX = MAXX(EVNL, [Value])
			
			
			// VAR MAXValue = MAXX(
			//     {
			//         (ConsolMAX),
			//         (EINIDRMAX),
			//         (EMSBMAX),
			//         (EPCMAX),
			//         (ESDMAX),
			//         (ESPMAX),
			//         (ETHTotalMAX),
			//         (EVNLMAX)
			//     },
			//     [Value]
			// )
			
			// VAR scaleFactor = 1.2
			// RETURN
			//     IF(
			//         MAXValue < 0, 
			//         MAXValue * (2-scaleFactor), 
			//         MAXValue * scaleFactor
			//     )
			```
		lineageTag: 23a190cb-455b-46b1-a54f-dc5689fd8bb2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ESC_Revenue_Waterfall_MaxRange =
			
			
			var selectedScenario = SELECTEDVALUE(DIM_Scenario[Scenario])
			var selectedCountry = SELECTEDVALUE('Selector Table - Country'[Country])
			var userSelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR fcValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20")
			VAR actualValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "Finance (Local) - FY20")
			
			VAR maxValue = MAX(fcValue, actualValue)
			
			RETURN 1.05 * maxValue
		lineageTag: e3a777e0-ff0a-4941-81a0-f8a11b717057

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ProductCategory_Revenue_Waterfall_MaxRange =
			
			
			var selectedScenario = SELECTEDVALUE(DIM_Scenario[Scenario])
			var selectedProductCategory = SELECTEDVALUE('Selector Table - Product Category'[Product Category])
			var userSelectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR fcValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = userSelectedScenario, HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20")
			VAR actualValue = CALCULATE([Sales_Selector], DIM_Country[Country] = "Finance Consol without EPIL", DIM_Scenario[Scenario] = "Actual", HIER_ProfitCenter[ProfitCenter_L9] = "BPD (Local) - FY20")
			
			VAR maxValue = MAX(fcValue, actualValue)
			
			RETURN 1.05 * maxValue
		lineageTag: 777f2505-fef2-4434-91b0-f03381f8b135

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGARatio_Parameter_Selector_LineGraph_AllValues =
			
			VAR ReferenceDate = MAX(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY = 1 || CurrentMonthCY = 2 || CurrentMonthCY = 3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR AllValues =
			    UNION(
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_CONSOL]
			        ),
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_EINIDR]
			        ),
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_EMSB]
			        ),
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_EPC]
			        ),
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_ESD]
			        ),
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_ESP]
			        ),
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_ETHTotal]
			        ),
			        SUMMARIZE(
			            'Presentation Calendar',
			            'Presentation Calendar'[Year Month],
			            "Value", [SGARatio_Selector_LineGraph_EVNL]
			        )
			    )
			
			VAR MinValue = MINX(AllValues, [Value])
			VAR MaxValue = MAXX(AllValues, [Value])
			
			RETURN
			    FORMAT(MinValue, "0.00000") & "|" & FORMAT(MaxValue, "0.00000")
		lineageTag: 59e35685-08a7-4fd0-ae1f-4318b6a9b825

	measure SGARatio_Parameter_Selector_LineGraph_MAX =
			
			VAR MinMaxString = [SGARatio_Parameter_Selector_LineGraph_AllValues]
			VAR SeparatorPosition = SEARCH("|", MinMaxString, 1, LEN(MinMaxString))
			VAR MaxValueString = MID(MinMaxString, SeparatorPosition + 1, LEN(MinMaxString) - SeparatorPosition)
			
			RETURN IFERROR(VALUE(MaxValueString), BLANK())
		lineageTag: ead0a1aa-93c6-48b2-a384-e28cf5445f62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SGARatio_Parameter_Selector_LineGraph_MINRange =
			
			VAR maxValue = [SGARatio_Parameter_Selector_LineGraph_MAX]
			VAR minValue = [SGARatio_Parameter_Selector_LineGraph_MIN]
			
			VAR avgValue = (maxValue + minValue) / 2
			VAR extraRange = (avgValue - minValue)
			VAR result = minValue - (1 * extraRange)
			
			RETURN result
		lineageTag: 2cef2ed5-f7a0-4ebb-8232-9f86d55459c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SalesbyESC FC' = SELECTEDVALUE('Selector Table - Scenario'[Alias])
		displayFolder: Dynamic Text
		lineageTag: f4828781-8750-46a5-9dd1-4e17e1b48760

	measure SlowInven%_MINRange =
			
			VAR MINValue = MINX(
			    FILTER(
			        {
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_ESP] ), [SlowInven%_Selector_LineGraph_ESP]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EIN] ), [SlowInven%_Selector_LineGraph_EIN]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EPC] ), [SlowInven%_Selector_LineGraph_EPC]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_ETH] ), [SlowInven%_Selector_LineGraph_ETH]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EMSB] ), [SlowInven%_Selector_LineGraph_EMSB]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EVNL] ), [SlowInven%_Selector_LineGraph_EVNL]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_ESPCONSO] ), [SlowInven%_Selector_LineGraph_ESPCONSO])
			        },
			        [Value1] in ALLSELECTED ('SlowInven% Parameter'[Parameter Fields] )
			    ),
			    [Value2]
			)
			RETURN
			    0.1*MINValue
		lineageTag: 0ee6b639-cc35-42c6-aaf8-1a597d669962

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven%_MAXRange =
			
			VAR MAXValue = MAXX(
			    FILTER(
			        {
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_ESP] ), [SlowInven%_Selector_LineGraph_ESP]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EIN] ), [SlowInven%_Selector_LineGraph_EIN]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EPC] ), [SlowInven%_Selector_LineGraph_EPC]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_ETH] ), [SlowInven%_Selector_LineGraph_ETH]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EMSB] ), [SlowInven%_Selector_LineGraph_EMSB]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_EVNL] ), [SlowInven%_Selector_LineGraph_EVNL]),
			            ( NAMEOF( 'Measures Table'[SlowInven%_Selector_LineGraph_ESPCONSO] ), [SlowInven%_Selector_LineGraph_ESPCONSO])
			        },
			        [Value1] in ALLSELECTED ('SlowInven% Parameter'[Parameter Fields] )
			    ),
			    [Value2]
			)
			RETURN
			    0.15*MAXValue
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 38231f31-efc0-4d08-bedf-a3a455855fb4

	measure Sales_Selector_LineGraph_OverviewByPG_MINRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMIN = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMIN = MINX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMIN = MINX(PrevYearActual, [Value])
			
			VAR MINValue = MIN(ActualMIN, MIN(ForecastMIN, PrevYearActualMIN))
			
			VAR scaleFactor = 0.9
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 0fdef515-68fc-456e-bdcb-5571b1ed3ab7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_OverviewByPG_MAXRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month]),
			                DIM_Scenario[Scenario] = "Actual"
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_FC_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR PrevYearActual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_PrevYearActual_Selector], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearActualMAX = MAXX(PrevYearActual, [Value])
			
			VAR MAXValue = MAX(ActualMAX, MAX(ForecastMAX, PrevYearActualMAX))
			
			VAR scaleFactor = 1.1
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 5780dd96-d8a0-4cbe-ae69-72addfe22aa2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_MUCons_MINRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR ActualMU = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_Actual_MU], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ActualMUMin = MINX(ActualMU, [Value])
			
			VAR PrevYearMU = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_PrevYear_MU], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearMUMin = MINX(PrevYearMU, [Value])
			
			VAR ActualCons = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_Actual_Cons], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ActualConsMin = MINX(ActualCons, [Value])
			
			VAR PrevYearCons = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_PrevYear_Cons], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearConsMin = MINX(PrevYearCons, [Value])
			
			VAR MINValue = MIN(ActualMUMin, MIN(PrevYearMUMin, MIN(ActualConsMin, PrevYearConsMin)))
			
			VAR scaleFactor = 0.7
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 54379985-3861-45fe-aca5-4c223fbb81f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Selector_LineGraph_MUCons_MAXRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR ActualMU = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_Actual_MU], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ActualMUMAX = MAXX(ActualMU, [Value])
			
			VAR PrevYearMU = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_PrevYear_MU], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearMUMAX = MAXX(PrevYearMU, [Value])
			
			VAR ActualCons = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_Actual_Cons], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ActualConsMAX = MAXX(ActualCons, [Value])
			
			VAR PrevYearCons = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [Sales_Selector_LineGraph_PrevYear_Cons], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR PrevYearConsMAX = MAXX(PrevYearCons, [Value])
			
			VAR MAXValue = MAX(ActualMUMAX, MAX(PrevYearMUMAX, MAX(ActualConsMAX, PrevYearConsMAX)))
			
			VAR scaleFactor = 1.1
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 405d1a97-7fe5-4bbe-be11-c3ccaee0565f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinusBreakdown_LineGraph_MINRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SalesMinusBreakdown_LineGraph_Actual], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ActualMin = MINX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SalesMinusBreakdown_LineGraph_FC], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMin = MINX(Forecast, [Value])
			
			VAR MINValue = MIN(ActualMin, ForecastMin)
			
			VAR scaleFactor = 0.7
			RETURN
			    IF(
			        MINValue < 0, 
			        MINValue * (2-scaleFactor), 
			        MINValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 6ee384fb-5e38-46ab-b404-8226004e83fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinusBreakdown_LineGraph_MAXRange = ```
			
			VAR ReferenceDate = SELECTEDVALUE(DIM_Calendar[FY Year Month])
			VAR CurrentDateCY = LOOKUPVALUE(DIM_Calendar[Year Month], DIM_Calendar[FY Year Month], ReferenceDate)
			VAR CurrentYearCY = YEAR(CurrentDateCY)
			VAR CurrentMonthCY = MONTH(CurrentDateCY)
			VAR StartYTDDate =
			    IF(
			        CurrentMonthCY=1 || CurrentMonthCY=2 || CurrentMonthCY=3,
			        DATE(CurrentYearCY - 1, 4, 1),
			        DATE(CurrentYearCY, 4, 1)
			    )
			VAR PreviousDates = DATESBETWEEN('Presentation Calendar'[Year Month], StartYTDDate, CurrentDateCY)
			
			VAR Actual = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SalesMinusBreakdown_LineGraph_Actual], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ActualMAX = MAXX(Actual, [Value])
			
			VAR Forecast = 
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            SUMMARIZE(
			                'Presentation Calendar',
			                'Presentation Calendar'[Year Month]
			            ),
			            "Value", CALCULATE(
			                [SalesMinusBreakdown_LineGraph_FC], 
			                KEEPFILTERS(PreviousDates), 
			                REMOVEFILTERS('DIM_Calendar'), 
			                USERELATIONSHIP(DIM_Calendar[Year Month], 'Presentation Calendar'[Year Month])
			            )
			        )
			    )
			VAR ForecastMAX = MAXX(Forecast, [Value])
			
			VAR MAXValue = MAX(ActualMAX, ForecastMAX)
			
			VAR scaleFactor = 1.2
			RETURN
			    IF(
			        MAXValue < 0, 
			        MAXValue * (2-scaleFactor), 
			        MAXValue * scaleFactor
			    )
			```
		displayFolder: Overview\LineGraph
		lineageTag: 3f9d270f-d34b-46e8-9763-a0b4bdbae992

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SalesMinus%_Selector_Actual_Line =
			
			CALCULATE(
			    [SalesMinus%_Selector],
			    DIM_Scenario[Scenario] = "Actual"
			)
		displayFolder: Sales Minus
		lineageTag: e486d253-d63c-46e9-b8b6-103322a1ee59

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Achievement_PrinterOthers_Selector = ```
			
			CALCULATE(
			    [Sales_Achievement_Selector], 
			    HIER_ProfitCenter[ProfitCenter_L9] IN {"CP (Local) - FY20", "Media Others - PH16", "Liatris (Local) - FY20", "Colour Label/LW (Local)"}
			)
			```
		displayFolder: Waterfall
		lineageTag: 50be6d4d-3c83-4e0b-8bf0-72a3aa8f4f78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Achievement_LFP_Selector = ```
			
			
			VAR selectedScenario = SELECTEDVALUE('Selector Table - Scenario'[Scenario])
			
			VAR vActual = 
			    CALCULATE(
			        [Sales_LFP_Selector],
			        DIM_Scenario[Scenario] = "Actual"
			    )
			
			VAR vFC =
			    CALCULATE(
			        [Sales_LFP_Selector],
			        DIM_Scenario[Scenario] = selectedScenario
			    )
			
			return vActual/vFC
			
			
			//20240822
			//CALCULATE(
			//    [Sales_Achievement_Selector], 
			//    HIER_ProfitCenter[ProfitCenter_L9] IN {"LFP (Local) - FY20", "Corporate (Local) - FY20"}
			//)
			```
		displayFolder: Waterfall
		lineageTag: 995da200-6948-48ff-aaea-aca221849845

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ESC_SalesAchievement_ProductGroup = ```
			
			 
			var selectedScenario = "Actual"
			var selectedProductGroup = SELECTEDVALUE('Selector Table - Product Category'[Product Category])
			var actualScenario = "Actual"
			 
			return
			            SWITCH(selectedProductGroup,
			                "CISS", CALCULATE([Sales_Achievement_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "CISS_FY20"),
			                "SIDM", CALCULATE([Sales_Achievement_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "SIDM/PLQ (Local)"),
			                "SP", CALCULATE([Sales_Achievement_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Small Printer (Local)"),
			                "Corporate BU", CALCULATE([Sales_Achievement_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "Corporate BU"),
			                "Printer others", CALCULATE([Sales_Achievement_PrinterOthers_Selector], DIM_Scenario[Scenario] = actualScenario),
			                "LFP (excl Corp)", CALCULATE([Sales_Achievement_LFP_Selector], DIM_Scenario[Scenario] = actualScenario),
			                "VI", CALCULATE([Sales_Achievement_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "VI - PH16"),
			                "IIJ", CALCULATE([Sales_Achievement_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "IIJ"),
			                "RS", CALCULATE([Sales_Achievement_Selector], DIM_Scenario[Scenario] = actualScenario, HIER_ProfitCenter[ProfitCenter_L9] = "FA - PH16")
			            )
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Pareto
		lineageTag: 3ca27a31-2d11-4694-aa81-069a22b46b8f

	measure ProductGroup_BarChart_Selector =
			
			VAR vCategory = SELECTEDVALUE('Selector Table - Revenue/Achievement'[Category])
			
			RETURN
			    SWITCH(
			        vCategory,
			        "Revenue", [ESC_Revenue_ProductGroup],
			        "Achievement", [ESC_SalesAchievement_ProductGroup]
			    )
		displayFolder: Pareto
		lineageTag: 071ea5ed-8158-4299-a25a-f9feecf252cf

		formatStringDefinition =
				VAR vCategory = SELECTEDVALUE('Selector Table - Revenue/Achievement'[Category])
				RETURN
				    SWITCH(
				        vCategory,
				        "Revenue", "0.0",
				        "Achievement", "0%"
				    )

	measure ProductGroup_BarChart_Selector_DataLabel =
			
			VAR vCategory = SELECTEDVALUE('Selector Table - Revenue/Achievement'[Category])
			
			RETURN
			    SWITCH(
			        vCategory,
			        "Revenue", FORMAT([ESC_Revenue_ProductGroup]/1000000, "#,##0.0") & "M",
			        "Achievement", FORMAT([ESC_SalesAchievement_ProductGroup], "0.0%")
			    )
		displayFolder: Pareto
		lineageTag: 3a659eaa-73d5-47e2-a231-65a58a6ae846

	measure SlowInven_MTH =
			
			VAR vSlowInven =
			    CALCULATE(
			        SUMX(FACT_Inventory, FACT_Inventory[ACT_EXRATE_SGD] * FACT_Inventory[Value]),
			        NOT FACT_Inventory[SMS] IN {"<30Days", ">=30&<60Days", ">=60Days", ">=90Days", ">=120Days", ">=150Days"},
			        NOT LEFT(FACT_Inventory[ProfitCenter], 3) = "P14",
			        NOT FACT_Inventory[Exclude_SKU_Filter] = "Reporting"
			    )
			
			RETURN vSlowInven
		lineageTag: 7435fcca-6bef-44c4-8e14-72bb309d806f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven_MTH_Actual =
			
			CALCULATE(
			    [SlowInven_MTH],
			    DIM_Scenario[Scenario] = "Actual"
			)
		lineageTag: 340b1227-a4dc-4903-9b4f-40795f9e6681

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure 2'
		lineageTag: d1cc3841-a0e0-4c83-9e29-b6b1ff7d72c0

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure SlowInven_PrevMTH =
			
			VAR selectedPeriod = SELECTEDVALUE(DIM_Calendar[Year Month])
			VAR prevMonth = EOMONTH(selectedPeriod, -1)
			
			RETURN
			    CALCULATE(
			        [SlowInven_MTH],
			        DATEADD('DIM_Calendar'[Year Month], -1, MONTH)
			    )
		lineageTag: c87ffa97-2563-4fdf-bf95-adde025c7ffc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven_MTH_WithConsol_ActualMinusFC = [SlowInven_MTH_Actual_WithConsol] - [SlowInven_Target_MTH_WithConsol]
		lineageTag: 192340aa-b0f1-4740-8c58-0af63585cfdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven_Target_MTH =
			
			VAR slowInven = SUM(FACT_InventoryTarget[Slow Moving Amt])
			VAR result = slowInven
			
			RETURN IFERROR(result, 0)
		lineageTag: 1fe08c0f-2e2e-4294-a3a5-69dcbcc99373

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven_MTH_Actual_WithConsol =
			
			SWITCH(
			    SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA General]),
			    "Consol",
			    CALCULATE(
			        [SlowInven_MTH_Actual],
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'),
			        REMOVEFILTERS(FACT_Consol[Country]),
			        FACT_Consol[Country] = "Finance Consol without EPIL"
			    ),
			    [SlowInven_MTH_Actual]
			)
		lineageTag: 3d2f36b7-1238-4f52-98c8-544c043211ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven_PrevMTH_WithConsol =
			
			SWITCH(
			    SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA General]),
			    "Consol",
			    CALCULATE(
			        [SlowInven_PrevMTH],
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'),
			        REMOVEFILTERS(FACT_Consol[Country]),
			        FACT_Consol[Country] = "Finance Consol without EPIL"
			    ),
			    [SlowInven_PrevMTH]
			)
		lineageTag: e4a2bcb6-817c-4e5c-a6a6-485af3a8786f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven_Target_MTH_WithConsol =
			
			SWITCH(
			    SELECTEDVALUE('DIM_Country - Alias & Ordering'[SGA General]),
			    "Consol",
			    CALCULATE(
			        [SlowInven_Target_MTH],
			        REMOVEFILTERS('DIM_Country - Alias & Ordering'),
			        REMOVEFILTERS('FACT_InventoryTarget'[ESC])
			    ),
			    [SlowInven_Target_MTH]
			)
		lineageTag: 7975ab14-4326-4945-bd7b-2d7e928a133f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlowInven%_Selector_LineGraph =
			
			VAR selectedESC = SELECTEDVALUE('Selector Table - Country'[Alias])
			
			RETURN
			    SWITCH(
			        selectedESC,
			        "Consol", [SlowInven%_Selector_LineGraph_ESPCONSO],
			        "EIN", [SlowInven%_Selector_LineGraph_EIN],
			        "EMSB", [SlowInven%_Selector_LineGraph_EMSB],
			        "EPC", [SlowInven%_Selector_LineGraph_EPC],
			        "ESP", [SlowInven%_Selector_LineGraph_ESP],
			        "ETH", [SlowInven%_Selector_LineGraph_ETH],
			        "EVNL", [SlowInven%_Selector_LineGraph_EVNL]
			    )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 65ae5328-717c-4db9-be85-bf9bb1ae6177

	partition 'Measures Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

