table 'Selector Table - Revenue/Achievement'
	lineageTag: b1353982-436d-4da6-ab6f-54dc4e4e5766

	column Category
		dataType: string
		lineageTag: e7954ac5-86ac-4260-935a-9b28ebe663a0
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: c87e6b37-2fdc-4968-9e17-024b6c8efda9
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition 'Selector Table - Revenue/Achievement' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCkotS80rTVXSUTJUitWJVnJMzsgECuWm5pUAxYyUYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Category", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

