table 'Selector Table - TotalCo BPD ED'
	lineageTag: dea7a901-deca-458e-b6fd-2c680e178682

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 4f597916-5381-4210-9743-89a9c2ee3da3
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column ProfitCenter_Name
		dataType: string
		lineageTag: 37a0be7f-028c-4184-8de6-abd3d4859bd5
		summarizeBy: none
		sourceColumn: ProfitCenter_Name
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: 7aed8d97-cb89-4e25-8523-76af15205401
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	partition 'Selector Table - TotalCo BPD ED' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrJL0nMUXDOV4rViVYyAgo4BbiA2cZAti+QGQsA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sort = _t, ProfitCenter_Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sort", Int64.Type}, {"ProfitCenter_Name", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "ProfitCenter_Name", "ProfitCenter_Name - Copy"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column","MD","Product 1",Replacer.ReplaceText,{"ProfitCenter_Name - Copy"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Product 1","Product 2",Replacer.ReplaceText,{"ProfitCenter_Name - Copy"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","BPD","Product 1",Replacer.ReplaceText,{"ProfitCenter_Name - Copy"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Total Co","Total Product ",Replacer.ReplaceText,{"ProfitCenter_Name - Copy"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value3",{{"ProfitCenter_Name - Copy", "Product Category"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

